BEGIN;

-- ============================================================
-- POLO NORTE (Ahorro) — IDs 1-75
-- ============================================================

-- Campaign: El Presupuesto (IDs 1-15)
UPDATE submissions SET content='Un presupuesto es un plan que asigna tus ingresos a gastos, ahorro e inversión antes de que el mes comience. Sin él, el dinero simplemente desaparece.', tips='["Escríbelo antes de que empiece el mes, no durante","Distingue entre gastos fijos y variables para saber dónde tienes margen","Un presupuesto no es una restricción, es una decisión de cómo quieres vivir"]'::jsonb, quiz_question='¿Cuál es el primer paso para crear un presupuesto efectivo?', quiz_options='[{"text":"Abrir una cuenta de ahorro","correct":false},{"text":"Calcular todos tus ingresos netos mensuales","correct":true},{"text":"Listar todos tus gastos del mes pasado","correct":false},{"text":"Hablar con un asesor financiero","correct":false}]'::jsonb WHERE id=1;

UPDATE submissions SET content='Registrar cada ingreso —nómina, freelance, alquiler, dividendos— te da la base real sobre la que construir tu plan. Usar promedios si los ingresos son irregulares.', tips='["Usa el ingreso neto (después de impuestos), no el bruto","Si tienes ingresos variables, usa el promedio de los últimos 6 meses","Incluye ingresos ocasionales repartiéndolos entre los 12 meses"]'::jsonb, quiz_question='Si cobras 2.000€ en enero, 1.500€ en febrero y 2.500€ en marzo, ¿qué ingreso mensual base deberías usar para tu presupuesto?', quiz_options='[{"text":"2.500€ (el máximo)","correct":false},{"text":"1.500€ (el mínimo, por seguridad)","correct":false},{"text":"2.000€ (el promedio)","correct":true},{"text":"El del último mes siempre","correct":false}]'::jsonb WHERE id=2;

UPDATE submissions SET content='Los gastos fijos son iguales cada mes (alquiler, seguro, suscripciones). Los variables cambian (comida, ocio, ropa). Conocer esta diferencia te dice dónde puedes actuar.', tips='["Los gastos fijos son difíciles de reducir a corto plazo; trabaja en los variables","Revisa cada 6 meses si algún gasto «fijo» puede renegociarse","Los gastos variables son donde está la mayor palanca de ahorro inmediato"]'::jsonb, quiz_question='¿Cuál de estos gastos es variable?', quiz_options='[{"text":"Alquiler mensual","correct":false},{"text":"Cuota del préstamo del coche","correct":false},{"text":"Gasto en restaurantes","correct":true},{"text":"Seguro de hogar anual","correct":false}]'::jsonb WHERE id=3;

UPDATE submissions SET content='La regla 50/30/20 propone destinar el 50% de ingresos a necesidades, 30% a deseos y 20% a ahorro/deuda. Es un punto de partida, no una ley.', tips='["Ajusta los porcentajes a tu situación: vivir en Barcelona puede requerir 60% en necesidades","El 20% de ahorro es el mínimo recomendado, no el objetivo final","Empieza con esta regla y personalízala con el tiempo"]'::jsonb, quiz_question='Según la regla 50/30/20, si ganas 2.000€ netos, ¿cuánto deberías ahorrar o pagar deuda?', quiz_options='[{"text":"300€","correct":false},{"text":"400€","correct":true},{"text":"500€","correct":false},{"text":"600€","correct":false}]'::jsonb WHERE id=4;

UPDATE submissions SET content='Categorizar tus gastos (vivienda, alimentación, transporte, ocio, salud…) te muestra con claridad en qué se va tu dinero y dónde puedes recortar.', tips='["Empieza con 6-8 categorías principales, no más de 15","Revisa al final del mes si alguna categoría fue muy diferente a lo planeado","Las categorías personalizadas funcionan mejor que las genéricas de las apps"]'::jsonb, quiz_question='¿Por qué es útil categorizar los gastos en un presupuesto?', quiz_options='[{"text":"Para cumplir requisitos bancarios","correct":false},{"text":"Para identificar dónde se gasta más y poder ajustar","correct":true},{"text":"Para calcular impuestos correctamente","correct":false},{"text":"Es obligatorio para abrir una cuenta de ahorro","correct":false}]'::jsonb WHERE id=5;

UPDATE submissions SET content='Un presupuesto mensual cubre el día a día; uno anual anticipa gastos grandes como vacaciones, seguros anuales o reparaciones. Ambos se complementan.', tips='["Haz una lista de gastos anuales y divídelos entre 12 para reservar mes a mes","Los gastos anuales inesperados son la causa más común de romper el presupuesto","Enero es buen momento para revisar el presupuesto anual completo"]'::jsonb, quiz_question='¿Cuál es la ventaja de tener un presupuesto anual además del mensual?', quiz_options='[{"text":"Es más fácil de hacer","correct":false},{"text":"Permite anticipar y distribuir gastos grandes a lo largo del año","correct":true},{"text":"Los bancos lo exigen para ciertos productos","correct":false},{"text":"Evita pagar impuestos sobre el ahorro","correct":false}]'::jsonb WHERE id=6;

UPDATE submissions SET content='El presupuesto base cero asigna cada euro a una categoría hasta llegar a cero. Ingresos - gastos - ahorro - inversión = 0. Nada queda sin asignar.', tips='["Si sobra dinero al final, asígnalo conscientemente (más ahorro, más inversión, ocio extra)","Es el método más estricto pero el que más control da","Úsalo cuando sientas que «no sabes a dónde va el dinero»"]'::jsonb, quiz_question='En el presupuesto base cero, ¿qué pasa si al calcular queda dinero sin asignar?', quiz_options='[{"text":"Se deja como reserva automática","correct":false},{"text":"Se devuelve al banco","correct":false},{"text":"Se asigna conscientemente a alguna categoría hasta llegar a cero","correct":true},{"text":"Se usa para gastos de emergencia directamente","correct":false}]'::jsonb WHERE id=7;

UPDATE submissions SET content='El método del sobre divide el efectivo en sobres físicos por categoría. Cuando el sobre se vacía, ya no hay más para esa categoría ese mes. Elimina el gasto inconsciente.', tips='["Funciona especialmente bien para categorías donde tiendes a gastar de más","Puedes hacerlo digitalmente con subcuentas en el banco","El efecto psicológico de «ver» el dinero físico reduce el gasto"]'::jsonb, quiz_question='¿Qué ocurre en el método del sobre cuando se acaba el dinero de la categoría «ocio»?', quiz_options='[{"text":"Se puede tomar prestado de otro sobre","correct":false},{"text":"No se puede gastar más en ocio ese mes","correct":true},{"text":"Se recarga automáticamente a mitad de mes","correct":false},{"text":"Se solicita un adelanto al empleador","correct":false}]'::jsonb WHERE id=8;

UPDATE submissions SET content='Revisar tus gastos reales cada semana o mes es lo que convierte el presupuesto en una herramienta viva. Un presupuesto que no se revisa es papel mojado.', tips='["Dedica 15 minutos cada domingo a revisar los gastos de la semana","Compara lo planeado vs lo real en cada categoría","El seguimiento constante es más valioso que el presupuesto perfecto"]'::jsonb, quiz_question='¿Con qué frecuencia mínima deberías revisar tus gastos para que el presupuesto sea efectivo?', quiz_options='[{"text":"Una vez al año","correct":false},{"text":"Solo cuando hay problemas económicos","correct":false},{"text":"Mensualmente como mínimo, semanalmente lo ideal","correct":true},{"text":"Diariamente sin excepción","correct":false}]'::jsonb WHERE id=9;

UPDATE submissions SET content='El presupuesto se ajusta cuando cambian los ingresos, los gastos fijos o los objetivos. No es un documento estático; debe evolucionar con tu vida.', tips='["Revisa el presupuesto completo al cambiar de trabajo, tener un hijo o mudarte","Un aumento de sueldo no significa gastar más automáticamente","Cuando bajan ingresos, prioriza necesidades y corta deseos antes que ahorro"]'::jsonb, quiz_question='¿Cuándo deberías revisar y ajustar tu presupuesto completo?', quiz_options='[{"text":"Solo cuando hay deudas","correct":false},{"text":"Nunca, si funciona no lo toques","correct":false},{"text":"Ante cambios importantes en ingresos, gastos fijos u objetivos de vida","correct":true},{"text":"Cada 5 años aproximadamente","correct":false}]'::jsonb WHERE id=10;

UPDATE submissions SET content='Con ingresos irregulares, presupuesta sobre el mes más bajo de los últimos 12. En meses buenos, el exceso va a fondo de emergencia o ahorro extra.', tips='["Calcula tu ingreso mínimo garantizado y basa el presupuesto en él","En meses buenos, paga deuda o refuerza el fondo de emergencia primero","El ingreso variable requiere más disciplina presupuestaria, no menos"]'::jsonb, quiz_question='Si eres freelance y tu ingreso varía entre 1.200€ y 3.000€, ¿cómo deberías estructurar tu presupuesto base?', quiz_options='[{"text":"Basarlo en 3.000€ para no limitarte","correct":false},{"text":"Basarlo en 1.200€ y gestionar el exceso conscientemente","correct":true},{"text":"Hacer un presupuesto diferente cada mes","correct":false},{"text":"No hacer presupuesto con ingresos variables","correct":false}]'::jsonb WHERE id=11;

UPDATE submissions SET content='El ahorro debe aparecer en el presupuesto como un gasto más, no como «lo que sobre». Si esperas a que sobre, nunca sobra.', tips='["Automatiza el ahorro los primeros días del mes, antes de gastar","Trátalo como una factura que se paga a ti mismo","Empieza con un porcentaje pequeño que no duele y auméntalo gradualmente"]'::jsonb, quiz_question='¿Cuál es la estrategia más efectiva para garantizar que ahorras cada mes?', quiz_options='[{"text":"Ahorrar al final del mes lo que sobre","correct":false},{"text":"Pagar primero el ahorro, como si fuera una factura obligatoria","correct":true},{"text":"Abrir varias cuentas bancarias","correct":false},{"text":"Esperar a recibir un aumento para empezar a ahorrar","correct":false}]'::jsonb WHERE id=12;

UPDATE submissions SET content='Apps como YNAB, Fintonic, Wallet o una hoja de cálculo simple pueden hacer el seguimiento mucho más fácil. La mejor herramienta es la que realmente usas.', tips='["Prueba 2-3 herramientas antes de comprometerte con una","La sincronización bancaria automática reduce la fricción de registro","Una hoja de cálculo simple supera una app compleja que no abres"]'::jsonb, quiz_question='¿Cuál es el criterio más importante para elegir una herramienta de presupuesto?', quiz_options='[{"text":"Que tenga más funcionalidades","correct":false},{"text":"Que sea la más popular","correct":false},{"text":"Que la uses de forma consistente en tu día a día","correct":true},{"text":"Que sea gratuita","correct":false}]'::jsonb WHERE id=13;

UPDATE submissions SET content='En una familia o pareja, el presupuesto compartido requiere acuerdo sobre objetivos y transparencia total. Las finanzas son una de las principales causas de conflicto de pareja.', tips='["Tened una reunión mensual de finanzas de 30 minutos","Cada persona puede tener una pequeña asignación personal sin justificar","Los objetivos financieros comunes unen; los secretos financieros separan"]'::jsonb, quiz_question='¿Qué práctica es más recomendable para gestionar el presupuesto en pareja?', quiz_options='[{"text":"Que uno de los dos gestione todo y el otro no se involucre","correct":false},{"text":"Mantener finanzas completamente separadas siempre","correct":false},{"text":"Reuniones periódicas para revisar el presupuesto conjunto con transparencia","correct":true},{"text":"Que el que gana más decida el presupuesto","correct":false}]'::jsonb WHERE id=14;

UPDATE submissions SET content='Una revisión anual del presupuesto analiza qué funcionó, qué no, y ajusta objetivos para el año siguiente. Es el momento de planificar los gastos grandes del año.', tips='["Compara ingresos y gastos reales de todo el año vs lo planeado","Ajusta el presupuesto del año nuevo con los datos reales, no con suposiciones","Celebra los logros: si ahorraste más de lo planeado, reconócelo"]'::jsonb, quiz_question='¿Qué deberías hacer en una revisión anual del presupuesto?', quiz_options='[{"text":"Solo revisar el mes de diciembre","correct":false},{"text":"Comparar lo planeado vs lo real durante todo el año y ajustar objetivos","correct":true},{"text":"Cambiar completamente el método de presupuesto","correct":false},{"text":"Calcular cuánto pagaste en impuestos","correct":false}]'::jsonb WHERE id=15;

-- Campaign: El Fondo de Emergencia (IDs 16-30)
UPDATE submissions SET content='Un fondo de emergencia es dinero reservado exclusivamente para imprevistos reales: pérdida de empleo, enfermedad, avería grave. No es ahorro para vacaciones.', tips='["Mantenlo separado de tu cuenta corriente para reducir la tentación de gastarlo","Su objetivo es evitar que los imprevistos te generen deuda","El fondo de emergencia es el primer pilar de cualquier plan financiero"]'::jsonb, quiz_question='¿Cuál de estos gastos justifica usar el fondo de emergencia?', quiz_options='[{"text":"Unas vacaciones de verano","correct":false},{"text":"Un televisor en rebajas","correct":false},{"text":"Reparación urgente de la calefacción en invierno","correct":true},{"text":"Compra de ropa de temporada","correct":false}]'::jsonb WHERE id=16;

UPDATE submissions SET content='El tamaño recomendado es 3 meses de gastos esenciales si tienes empleo estable, y 6 meses si eres autónomo, tienes ingresos variables o tu sector es inestable.', tips='["Calcula solo gastos esenciales: alquiler, comida, suministros, transporte, seguros","Redondea hacia arriba; más es siempre mejor que menos","Revisa el importe cada año porque tus gastos esenciales cambian"]'::jsonb, quiz_question='Si tus gastos esenciales son 1.500€/mes y eres trabajador por cuenta ajena estable, ¿cuánto debería tener mínimo tu fondo de emergencia?', quiz_options='[{"text":"1.500€ (1 mes)","correct":false},{"text":"4.500€ (3 meses)","correct":true},{"text":"9.000€ (6 meses)","correct":false},{"text":"18.000€ (12 meses)","correct":false}]'::jsonb WHERE id=17;

UPDATE submissions SET content='El fondo de emergencia debe estar en un lugar líquido y seguro: cuenta de ahorro de alta rentabilidad, cuenta remunerada o depósito a corto plazo. No en bolsa ni en cripto.', tips='["Liquidez inmediata es más importante que rentabilidad en este fondo","Una cuenta remunerada al 2-3% TAE es ideal (protege de inflación parcialmente)","Nunca inviertas el fondo de emergencia en activos volátiles"]'::jsonb, quiz_question='¿Dónde es más adecuado guardar el fondo de emergencia?', quiz_options='[{"text":"En acciones de empresas sólidas","correct":false},{"text":"En Bitcoin como reserva de valor","correct":false},{"text":"En una cuenta de ahorro líquida y de bajo riesgo","correct":true},{"text":"En efectivo en casa","correct":false}]'::jsonb WHERE id=18;

UPDATE submissions SET content='Una emergencia real es un evento imprevisto, necesario y urgente. Una oportunidad de viaje o una oferta irresistible no son emergencias, aunque lo parezcan.', tips='["Antes de tocar el fondo, pregúntate: ¿es imprevisto, necesario y urgente?","Si dudas si es emergencia, probablemente no lo es","Crear una lista de «qué cuenta como emergencia» te protege de excusas futuras"]'::jsonb, quiz_question='¿Cuál de estos es un ejemplo válido de emergencia para usar el fondo?', quiz_options='[{"text":"Una oferta del 50% en una consola de videojuegos","correct":false},{"text":"Perder el empleo y necesitar cubrir gastos básicos durante la búsqueda","correct":true},{"text":"Las vacaciones de Navidad","correct":false},{"text":"Comprarte ropa de trabajo nueva","correct":false}]'::jsonb WHERE id=19;

UPDATE submissions SET content='Si no tienes fondo de emergencia, empieza con una meta pequeña: 500-1.000€. Eso ya elimina la mayoría de las emergencias cotidianas sin recurrir a deuda.', tips='["Comienza con 500€ como primera meta; es alcanzable en 2-3 meses","Automatiza una transferencia mensual fija a la cuenta del fondo","Cada pequeño importe que añades reduce tu vulnerabilidad financiera"]'::jsonb, quiz_question='Para alguien que empieza desde cero, ¿cuál es una primera meta realista para el fondo de emergencia?', quiz_options='[{"text":"6 meses de gastos completos inmediatamente","correct":false},{"text":"10.000€ antes de cualquier otra cosa","correct":false},{"text":"500-1.000€ como primer objetivo alcanzable","correct":true},{"text":"No hace falta si tienes tarjeta de crédito","correct":false}]'::jsonb WHERE id=20;

UPDATE submissions SET content='Tener el fondo de emergencia en una cuenta separada, idealmente en otro banco, reduce la tentación de «tomarlo prestado» para gastos del día a día.', tips='["Elige un banco sin tarjeta de débito asociada para esta cuenta","El pequeño inconveniente de transferir es una barrera saludable","Puedes llamarla «cuenta intocable» o «fondo X» para reforzar la intención"]'::jsonb, quiz_question='¿Por qué es recomendable mantener el fondo de emergencia en una cuenta separada?', quiz_options='[{"text":"Para obtener más intereses","correct":false},{"text":"Para reducir la tentación de gastarlo en cosas no urgentes","correct":true},{"text":"Por requisitos legales","correct":false},{"text":"Para que el banco no lo bloquee","correct":false}]'::jsonb WHERE id=21;

UPDATE submissions SET content='Después de usar el fondo de emergencia, reponlo lo antes posible. Es la primera prioridad hasta recuperar el colchón completo, antes que inversiones o gastos opcionales.', tips='["Calcula cuánto necesitas reponer y fija un plazo concreto","Pausa temporalmente las inversiones no críticas hasta reponer el fondo","Reponerlo rápido te prepara para la próxima emergencia"]'::jsonb, quiz_question='Tras usar 2.000€ del fondo de emergencia, ¿cuál debería ser tu prioridad financiera inmediata?', quiz_options='[{"text":"Empezar a invertir en bolsa para compensar","correct":false},{"text":"Reponer los 2.000€ lo antes posible","correct":true},{"text":"Esperar hasta tener el doble para reponer","correct":false},{"text":"No hace falta reponer si no fue toda la emergencia","correct":false}]'::jsonb WHERE id=22;

UPDATE submissions SET content='Un activo líquido se convierte en efectivo rápido sin perder valor. El fondo de emergencia debe ser siempre líquido; la iliquidez en una crisis es un problema grave.', tips='["Un depósito a plazo fijo no es líquido si tiene penalización por retirada anticipada","Acciones o fondos indexados son líquidos pero volátiles: pueden valer menos cuando los necesites","Liquidez + estabilidad de valor es la combinación correcta para el fondo de emergencia"]'::jsonb, quiz_question='¿Por qué la liquidez es más importante que la rentabilidad en el fondo de emergencia?', quiz_options='[{"text":"Porque los bancos lo exigen","correct":false},{"text":"Porque en una emergencia necesitas acceso inmediato al dinero","correct":true},{"text":"Porque los activos líquidos siempre son más rentables","correct":false},{"text":"Por razones fiscales","correct":false}]'::jsonb WHERE id=23;

UPDATE submissions SET content='El fondo de emergencia y el seguro son complementarios: el seguro cubre eventos grandes y predecibles (accidente, robo); el fondo cubre lo imprevisto y pequeño que los seguros no cubren.', tips='["No uses la existencia de seguros como excusa para no tener fondo de emergencia","Los seguros tienen franquicias y períodos de carencia; el fondo cubre esos huecos","Ambos juntos minimizan el impacto de cualquier imprevisto"]'::jsonb, quiz_question='¿Cuál es la relación correcta entre el fondo de emergencia y los seguros?', quiz_options='[{"text":"Son lo mismo, solo necesitas uno de los dos","correct":false},{"text":"Si tienes seguros completos no necesitas fondo de emergencia","correct":false},{"text":"Son complementarios: los seguros cubren eventos grandes, el fondo los pequeños imprevistos","correct":true},{"text":"El fondo de emergencia reemplaza cualquier seguro","correct":false}]'::jsonb WHERE id=24;

UPDATE submissions SET content='El error más común es usar el fondo para gastos anticipables (impuestos anuales, matrícula escolar) en lugar de crear fondos separados para esos gastos.', tips='["Crea un fondo separado para gastos anuales previsibles","El fondo de emergencia es solo para lo verdaderamente imprevisto","Confundir ambos deja el fondo siempre vacío y sin protección real"]'::jsonb, quiz_question='¿Qué error frecuente reduce la efectividad del fondo de emergencia?', quiz_options='[{"text":"Tenerlo en una cuenta remunerada","correct":false},{"text":"Usarlo para gastos previsibles como impuestos anuales","correct":true},{"text":"Tenerlo en otro banco","correct":false},{"text":"Revisarlo cada año","correct":false}]'::jsonb WHERE id=25;

UPDATE submissions SET content='Los autónomos y freelancers necesitan un fondo más grande (6-12 meses) porque sus ingresos son irregulares y no tienen prestación por desempleo pública como los asalariados.', tips='["Como autónomo, calcula el fondo sobre tus gastos esenciales, no sobre ingresos medios","Incluye en tu fondo la cuota de autónomos a la seguridad social","Un año de reserva no es exagerado si tienes clientes estacionales"]'::jsonb, quiz_question='¿Por qué un autónomo necesita un fondo de emergencia más grande que un asalariado?', quiz_options='[{"text":"Porque sus gastos son siempre mayores","correct":false},{"text":"Por requisitos fiscales especiales","correct":false},{"text":"Por ingresos irregulares y ausencia de prestación por desempleo","correct":true},{"text":"Porque los bancos les exigen más garantías","correct":false}]'::jsonb WHERE id=26;

UPDATE submissions SET content='En pareja o familia, el fondo de emergencia debe cubrir los gastos del hogar completo, no solo de una persona. Si un miembro pierde el ingreso, el otro no debe endeudarse.', tips='["Calculad el fondo sobre los gastos esenciales del hogar, no sobre ingresos","Si uno trabaja y el otro no, priorizad 6 meses mínimo","Hablad en pareja de qué cuenta como emergencia para evitar conflictos"]'::jsonb, quiz_question='En un hogar de dos personas con gastos esenciales de 2.000€/mes, ¿cuánto debería ser el fondo de emergencia mínimo?', quiz_options='[{"text":"1.000€ (mitad por persona)","correct":false},{"text":"2.000€ (1 mes)","correct":false},{"text":"6.000€ (3 meses del hogar completo)","correct":true},{"text":"500€ por persona","correct":false}]'::jsonb WHERE id=27;

UPDATE submissions SET content='Con inflación alta, el fondo de emergencia pierde poder adquisitivo. Una cuenta remunerada o fondo monetario reduce pero no elimina este efecto.', tips='["Con inflación al 5%, tu fondo pierde ~5% de valor real cada año","Una cuenta remunerada al 3% TAE reduce la pérdida real a ~2%","No tomes más riesgo del necesario por rendimiento; la función principal es protección"]'::jsonb, quiz_question='¿Qué estrategia es más adecuada para el fondo de emergencia durante períodos de alta inflación?', quiz_options='[{"text":"Invertirlo en bolsa para superar la inflación","correct":false},{"text":"Mantenerlo en efectivo debajo del colchón","correct":false},{"text":"Colocarlo en cuentas remuneradas o fondos monetarios de bajo riesgo","correct":true},{"text":"Convertirlo en Bitcoin como cobertura de inflación","correct":false}]'::jsonb WHERE id=28;

UPDATE submissions SET content='El fondo de emergencia no es para aprovechar oportunidades de inversión, aunque parezcan irresistibles. Usarlo así te deja expuesto justo cuando más lo necesites.', tips='["Si ves una «oportunidad», significa que hay riesgo; el fondo no es para riesgo","Si quieres invertir en oportunidades, crea un fondo de oportunidades separado","Mantener el fondo intacto te da la libertad de tomar decisiones desde la fortaleza"]'::jsonb, quiz_question='¿Deberías usar el fondo de emergencia para una oportunidad de inversión?', quiz_options='[{"text":"Sí, si la oportunidad es muy buena","correct":false},{"text":"Solo si estás seguro de recuperarlo en un mes","correct":false},{"text":"No, su función es protección, no inversión","correct":true},{"text":"Sí, si tienes más de 6 meses guardados","correct":false}]'::jsonb WHERE id=29;

UPDATE submissions SET content='Revisa el tamaño del fondo de emergencia al menos una vez al año. Si tus gastos esenciales subieron, el fondo necesita crecer para mantener la misma protección.', tips='["Revisión anual: calcula el fondo ideal con los gastos actuales, no los de hace 2 años","Al cambiar de ciudad, trabajo o situación familiar, revisa el fondo ese mismo mes","Un fondo que no se revisa puede quedarse obsoleto sin que lo notes"]'::jsonb, quiz_question='¿Con qué frecuencia deberías revisar si el tamaño de tu fondo de emergencia sigue siendo adecuado?', quiz_options='[{"text":"Nunca si ya lo tienes constituido","correct":false},{"text":"Al menos una vez al año y ante cambios importantes de vida","correct":true},{"text":"Solo cuando lo uses","correct":false},{"text":"Cada 5 años","correct":false}]'::jsonb WHERE id=30;

-- Campaign: Deuda Responsable (IDs 31-45)
UPDATE submissions SET content='No toda deuda es igual. La deuda productiva (hipoteca, inversión en educación o negocio) puede generar valor. La deuda consumista (tarjetas de crédito, préstamos para gadgets) destruye patrimonio.', tips='["Pregúntate: ¿esta deuda me generará más valor del que me costará en intereses?","Una hipoteca a tipo fijo bajo puede ser mejor que alquilar indefinidamente","Las deudas al 20%+ de interés nunca son productivas"]'::jsonb, quiz_question='¿Cuál de estas deudas se consideraría más «productiva»?', quiz_options='[{"text":"Crédito revolving al 22% para ropa","correct":false},{"text":"Préstamo personal para vacaciones","correct":false},{"text":"Hipoteca al 2% fijo para comprar un piso","correct":true},{"text":"Financiación de electrodoméstico al 15%","correct":false}]'::jsonb WHERE id=31;

UPDATE submissions SET content='La TIN (Tasa de Interés Nominal) y la TAE (Tasa Anual Equivalente) no son lo mismo. La TAE incluye comisiones y gastos, por eso es el indicador real del coste de una deuda.', tips='["Compara siempre por TAE, no por TIN","Una TIN baja con comisiones altas puede resultar más cara que un préstamo con TIN mayor","Antes de firmar cualquier crédito, exige ver la TAE en el contrato"]'::jsonb, quiz_question='¿Qué indicador deberías usar para comparar el coste real de diferentes préstamos?', quiz_options='[{"text":"TIN (Tasa de Interés Nominal)","correct":false},{"text":"TAE (Tasa Anual Equivalente)","correct":true},{"text":"El tipo de interés mensual","correct":false},{"text":"La cuota mensual más baja","correct":false}]'::jsonb WHERE id=32;

UPDATE submissions SET content='El método avalancha paga primero la deuda con mayor tipo de interés (ahorra más dinero). El método bola de nieve paga la más pequeña primero (da momentum psicológico). Ambos funcionan.', tips='["Matemáticamente, la avalancha ahorra más en intereses","Psicológicamente, eliminar deudas pequeñas da motivación para continuar","Elige el método que más probabilidad tiene de que lo mantengas"]'::jsonb, quiz_question='¿Cuál es la diferencia principal entre el método avalancha y bola de nieve para pagar deudas?', quiz_options='[{"text":"Avalancha paga primero la deuda más pequeña; bola de nieve la de mayor interés","correct":false},{"text":"Avalancha paga primero la de mayor interés; bola de nieve la más pequeña","correct":true},{"text":"Son el mismo método con diferente nombre","correct":false},{"text":"Avalancha es solo para hipotecas","correct":false}]'::jsonb WHERE id=33;

UPDATE submissions SET content='Pagar solo el mínimo en una tarjeta de crédito al 20% TAE puede hacer que una deuda de 3.000€ tarde décadas en pagarse y acabe costando el triple.', tips='["Calcula el coste total de solo pagar mínimos con una calculadora de amortización","Paga siempre más del mínimo, aunque sea poco más","Si no puedes pagar más del mínimo, la deuda ya es urgente"]'::jsonb, quiz_question='¿Qué problema tiene pagar solo el mínimo mensual en una tarjeta de crédito con interés alto?', quiz_options='[{"text":"El banco puede cancelar la tarjeta","correct":false},{"text":"La deuda crece o tarda décadas en amortizarse, costando mucho más","correct":true},{"text":"Afecta negativamente al IRPF","correct":false},{"text":"No hay problema si siempre pagas el mínimo a tiempo","correct":false}]'::jsonb WHERE id=34;

UPDATE submissions SET content='Las tarjetas de crédito son una herramienta útil si se liquidan completamente cada mes. Si no, los intereses (típicamente 20-25% TAE) las convierten en una trampa cara.', tips='["Usa la tarjeta solo si puedes pagar el saldo total a fin de mes","Activa alertas de gasto para no perder el control","Las tarjetas con cashback o puntos no compensan si no liquidas el saldo mensual"]'::jsonb, quiz_question='¿Cuándo una tarjeta de crédito no genera costes por intereses?', quiz_options='[{"text":"Cuando pagas solo el mínimo mensual","correct":false},{"text":"Cuando pagas el saldo completo cada mes antes de la fecha límite","correct":true},{"text":"Cuando tienes ingresos superiores a 3.000€/mes","correct":false},{"text":"Cuando la tarjeta tiene tasa de interés fija","correct":false}]'::jsonb WHERE id=35;

UPDATE submissions SET content='Los préstamos estudiantiles son una inversión en tu capacidad de generar ingresos. Pero solo tienen sentido si la carrera/formación tiene una salida laboral que permita devolverlos en un plazo razonable.', tips='["Calcula el salario medio de la carrera y el tiempo de amortización del préstamo","Un máster de 30.000€ que te sube el sueldo 500€/mes tarda 5 años en amortizarse","Evita financiar estudios sin salida laboral clara con deuda costosa"]'::jsonb, quiz_question='¿Cómo evalúas si un préstamo estudiantil vale la pena?', quiz_options='[{"text":"Por el prestigio de la institución educativa","correct":false},{"text":"Comparando el coste total del préstamo con el incremento de ingresos esperado","correct":true},{"text":"Si todos tus compañeros también lo piden","correct":false},{"text":"Si el tipo de interés es menor al 5%","correct":false}]'::jsonb WHERE id=36;

UPDATE submissions SET content='Una hipoteca es la mayor deuda de la vida de la mayoría de personas. La cuota no debería superar el 30-35% de los ingresos netos del hogar para no comprometer la calidad de vida.', tips='["Calcula el esfuerzo hipotecario: cuota mensual / ingresos netos * 100","Considera los gastos totales de compra (notaría, impuestos, registro): 10-15% del precio","Tipo fijo da certeza a largo plazo; tipo variable puede ser más barato pero con riesgo"]'::jsonb, quiz_question='Si los ingresos netos del hogar son 3.000€/mes, ¿cuál sería la cuota hipotecaria máxima recomendable?', quiz_options='[{"text":"1.500€ (50%)","correct":false},{"text":"900-1.050€ (30-35%)","correct":true},{"text":"600€ (20%)","correct":false},{"text":"Sin límite si tienes trabajo estable","correct":false}]'::jsonb WHERE id=37;

UPDATE submissions SET content='El ratio deuda/ingresos mide qué porcentaje de tus ingresos mensuales se destina a pagos de deuda. Por encima del 40% se considera zona de riesgo.', tips='["Incluye en el cálculo: hipoteca/alquiler, préstamos, tarjetas, cuotas de financiación","Si superas el 40%, prioriza reducir deuda antes que nuevas inversiones","Los bancos evalúan este ratio para conceder nuevos créditos"]'::jsonb, quiz_question='Si ganas 2.500€/mes y pagas 800€ de hipoteca + 200€ de préstamo personal, ¿cuál es tu ratio deuda/ingresos?', quiz_options='[{"text":"20%","correct":false},{"text":"32%","correct":false},{"text":"40%","correct":true},{"text":"48%","correct":false}]'::jsonb WHERE id=38;

UPDATE submissions SET content='Ante dificultades para pagar, habla con el acreedor antes de entrar en impago. Muchos aceptan reestructuraciones, períodos de carencia o quitas si se negocia a tiempo.', tips='["Contacta al acreedor al primer signo de dificultad, no cuando ya hay impagos","La reestructuración voluntaria es mejor que el impago involuntario","Busca asesoría de deuda gratuita (OCU, ADICAE) antes de tomar decisiones grandes"]'::jsonb, quiz_question='¿Qué deberías hacer si prevés que no podrás pagar una cuota de préstamo?', quiz_options='[{"text":"Ignorarlo y esperar a que pase","correct":false},{"text":"Pedir otro préstamo para cubrir ese pago","correct":false},{"text":"Contactar al acreedor proactivamente para negociar antes del impago","correct":true},{"text":"Cancelar la cuenta bancaria","correct":false}]'::jsonb WHERE id=39;

UPDATE submissions SET content='La consolidación de deudas une varias deudas en un solo préstamo, generalmente a menor tipo de interés. Puede reducir la cuota mensual, pero ojo: puede alargar el plazo y costar más en total.', tips='["Compara el coste total (intereses + comisiones) antes y después de consolidar","La consolidación solo tiene sentido si reduce el coste total, no solo la cuota","No consolides si luego vas a generar más deuda con las tarjetas liberadas"]'::jsonb, quiz_question='¿Cuándo tiene sentido consolidar deudas?', quiz_options='[{"text":"Siempre que la cuota mensual sea más baja","correct":false},{"text":"Cuando el coste total es menor y no genera nuevas deudas","correct":true},{"text":"Solo si tienes hipoteca","correct":false},{"text":"Nunca, siempre es mejor pagar por separado","correct":false}]'::jsonb WHERE id=40;

UPDATE submissions SET content='La quiebra personal o concurso de acreedores es el último recurso cuando la deuda es impagable. En España, la Ley de Segunda Oportunidad permite cierta exoneración de deuda bajo condiciones.', tips='["Busca asesoramiento legal gratuito antes de declararte en concurso","La Ley de Segunda Oportunidad existe desde 2015 y ha ayudado a miles de personas","El concurso tiene impacto en el historial crediticio pero da una salida real"]'::jsonb, quiz_question='¿Qué permite la Ley de Segunda Oportunidad en España?', quiz_options='[{"text":"Eliminar todas las deudas automáticamente","correct":false},{"text":"Exonerar parte o toda la deuda insolvente bajo condiciones específicas","correct":true},{"text":"Solo aplica a empresas, no a particulares","correct":false},{"text":"Congelar los tipos de interés de todas las deudas","correct":false}]'::jsonb WHERE id=41;

UPDATE submissions SET content='El historial crediticio registra tu comportamiento con las deudas. Pagos puntuales lo mejoran; impagos lo dañan. Un buen historial facilita acceso a crédito en mejores condiciones.', tips='["Paga siempre a tiempo, aunque sea el mínimo, para no dañar tu historial","En España, CIRBE (Banco de España) registra todos tus créditos vigentes","Puedes solicitar tu informe de riesgo en el Banco de España gratuitamente"]'::jsonb, quiz_question='¿Qué acción impacta positivamente en tu historial crediticio?', quiz_options='[{"text":"Tener muchas tarjetas de crédito","correct":false},{"text":"Pagar todas tus cuotas de forma puntual y consistente","correct":true},{"text":"Cancelar préstamos anticipadamente siempre","correct":false},{"text":"Mantener un saldo elevado en la cuenta corriente","correct":false}]'::jsonb WHERE id=42;

UPDATE submissions SET content='Los préstamos predatorios tienen tipos de interés abusivos (100%+ TAE en algunas financieras rápidas). Son legales pero extremadamente caros y difíciles de salir.', tips='["Desconfía de préstamos «sin papeles» o «aprobados en 10 minutos» a cualquier tipo","Un préstamo al 150% TAE duplica la deuda en menos de 1 año","En caso de urgencia, primero explora: familia, empleador, banco habitual, servicios sociales"]'::jsonb, quiz_question='¿Qué característica identifica un préstamo potencialmente predatorio?', quiz_options='[{"text":"Requiere mucha documentación","correct":false},{"text":"TAE extremadamente alta (50%+) y aprobación casi inmediata","correct":true},{"text":"Tiene cuotas mensuales","correct":false},{"text":"Lo ofrece un banco tradicional","correct":false}]'::jsonb WHERE id=43;

UPDATE submissions SET content='El BNPL (Buy Now Pay Later) como Klarna o Aplazame aplaza el pago, pero si no lo liquidas en plazo aplica intereses altos. Facilita el gasto impulsivo y puede acumular deuda sin notarlo.', tips='["Úsalo solo si lo liquidarás en el período gratuito de 0%","No uses BNPL para compras que no podrías permitirte pagando de una vez","Llevar seguimiento de varios BNPL activos simultáneamente es una trampa común"]'::jsonb, quiz_question='¿Cuál es el principal riesgo del BNPL (compra ahora paga después)?', quiz_options='[{"text":"Los comercios lo rechazan con frecuencia","correct":false},{"text":"Facilita el gasto impulsivo y puede acumular deuda con intereses altos si no se paga en plazo","correct":true},{"text":"Afecta al IRPF directamente","correct":false},{"text":"Solo funciona para compras superiores a 500€","correct":false}]'::jsonb WHERE id=44;

UPDATE submissions SET content='Vivir sin deudas consumistas no significa vivir sin crédito. Significa que cada deuda tiene un propósito claro, un plazo definido y no supera tu capacidad de pago.', tips='["Una vida sin deudas consumistas libera entre un 10-30% de los ingresos para ahorro e inversión","La ausencia de deuda es también ausencia de estrés financiero crónico","Llegar a deuda cero es un hito; mantenerla es el verdadero logro"]'::jsonb, quiz_question='¿Qué significa una vida financieramente sana en relación a la deuda?', quiz_options='[{"text":"No tener ninguna deuda de ningún tipo","correct":false},{"text":"Tener solo deudas productivas con propósito claro y capacidad de pago definida","correct":true},{"text":"Tener el máximo crédito disponible aunque no se use","correct":false},{"text":"Que todos los préstamos sean a tipo variable","correct":false}]'::jsonb WHERE id=45;

-- Campaign: Hábitos de Consumo (IDs 46-60)
UPDATE submissions SET content='Una necesidad es algo imprescindible para vivir y funcionar (comida, vivienda, transporte básico). Un deseo es algo que queremos pero podemos vivir sin ello. La confusión entre ambos es la raíz del gasto excesivo.', tips='["Antes de cada compra no rutinaria, pregúntate: ¿es necesidad o deseo?","Ni los deseos son malos; el problema es financiarlos con dinero que no tienes","Hay áreas grises: el móvil es necesidad y deseo. Lo importante es el nivel elegido"]'::jsonb, quiz_question='¿Cuál de estas compras sería claramente un «deseo» y no una «necesidad»?', quiz_options='[{"text":"Medicación prescrita por el médico","correct":false},{"text":"El último modelo de smartphone cuando el tuyo funciona bien","correct":true},{"text":"Transporte al trabajo","correct":false},{"text":"Alimentación básica semanal","correct":false}]'::jsonb WHERE id=46;

UPDATE submissions SET content='El cerebro asocia las compras con dopamina, creando un ciclo de gratificación instantánea. Entender este mecanismo ayuda a no confundir el impulso emocional con una necesidad real.', tips='["El impulso de compra suele durar menos de 20 minutos; esperar lo neutraliza","Las tiendas están diseñadas para maximizar compras impulsivas: colas largas, cajas junto a ofertas","Identifica tus «triggers» de compra impulsiva (estrés, aburrimiento, comparación social)"]'::jsonb, quiz_question='¿Por qué las compras impulsivas son tan comunes psicológicamente?', quiz_options='[{"text":"Porque los precios son demasiado bajos","correct":false},{"text":"Porque el cerebro libera dopamina al comprar, creando un ciclo de gratificación","correct":true},{"text":"Por falta de información sobre los productos","correct":false},{"text":"Por influencia exclusiva de la publicidad exterior","correct":false}]'::jsonb WHERE id=47;

UPDATE submissions SET content='El FOMO (fear of missing out) en consumo lleva a comprar lo que tienen los demás para no «quedarse atrás». La inflación del estilo de vida es cuando cada aumento de ingresos va seguido de más gastos.', tips='["El nivel de vida que muestran las redes sociales no es el real de casi nadie","El 74% de la riqueza no se muestra: los más ricos son los más discretos","Cada vez que suban tus ingresos, aumenta el ahorro antes que el gasto"]'::jsonb, quiz_question='¿Qué es la inflación del estilo de vida?', quiz_options='[{"text":"El incremento del IPC en productos de lujo","correct":false},{"text":"Cuando los gastos aumentan proporcionalmente a cada subida de ingresos","correct":true},{"text":"El coste de vivir en ciudades grandes","correct":false},{"text":"El encarecimiento de bienes de primera necesidad","correct":false}]'::jsonb WHERE id=48;

UPDATE submissions SET content='El minimalismo financiero no es vivir con lo mínimo, sino comprar con intención. Cada compra debería añadir valor real a tu vida, no solo ocupar espacio o satisfacer un impulso momentáneo.', tips='["Antes de comprar algo nuevo, pregúntate si te sigue generando valor en 6 meses","Tener menos cosas reduce el mantenimiento, el seguro y el espacio necesario","Lo que no usas en 1 año raramente lo usas en el siguiente"]'::jsonb, quiz_question='¿En qué se basa el minimalismo financiero?', quiz_options='[{"text":"En no comprar nada que no sea estrictamente necesario","correct":false},{"text":"En comprar de forma intencional, eligiendo solo lo que aporta valor real","correct":true},{"text":"En vivir con menos de 1.000€/mes siempre","correct":false},{"text":"En regalar todo lo que tienes y empezar desde cero","correct":false}]'::jsonb WHERE id=49;

UPDATE submissions SET content='Una auditoría de suscripciones lista todos los servicios recurrentes y evalúa cuáles realmente usas. El promedio de las familias paga por 12 suscripciones y usa activamente solo 4-5.', tips='["Revisa el extracto bancario del último mes y marca cada suscripción","Cancela inmediatamente las que no hayas usado en 60+ días","Agrupa con familia/amigos las que permiten cuentas compartidas"]'::jsonb, quiz_question='¿Con qué frecuencia deberías revisar tus suscripciones activas?', quiz_options='[{"text":"Nunca, si están en uso no hace falta","correct":false},{"text":"Solo cuando el banco te lo pide","correct":false},{"text":"Al menos cada 3-6 meses para detectar las que ya no usas","correct":true},{"text":"Una vez al contratar cada una","correct":false}]'::jsonb WHERE id=50;

UPDATE submissions SET content='Comparar precios antes de comprar cualquier producto no rutinario puede ahorrar entre un 10-40%. Internet lo hace más fácil que nunca, pero requiere unos minutos de hábito.', tips='["Para compras online: usa extensiones de comparación de precios en el navegador","Para supermercado: el precio por unidad (€/kg) es la métrica real, no el precio del envase","La comparación no aplica solo al precio; calidad, garantía y servicio también cuentan"]'::jsonb, quiz_question='¿Cuál es la métrica más útil para comparar productos del supermercado?', quiz_options='[{"text":"El precio total del envase","correct":false},{"text":"El tamaño del envase","correct":false},{"text":"El precio por unidad de medida (€/kg, €/litro)","correct":true},{"text":"La marca más conocida","correct":false}]'::jsonb WHERE id=51;

UPDATE submissions SET content='Comprar de segunda mano (ropa, electrónica, muebles, coches) puede dar el 80% del valor a un 30-50% del precio. El estigma de lo «usado» es cultural, no racional.', tips='["Plataformas como Wallapop, Vinted, eBay o Milanuncios ofrecen grandes oportunidades","Los coches de segunda mano deprecian menos que los nuevos; el nuevo pierde el 20% al salir del concesionario","Para electrónica: busca «reacondicionado certificado» con garantía"]'::jsonb, quiz_question='¿Qué ventaja financiera principal tiene comprar de segunda mano frente a nuevo?', quiz_options='[{"text":"Mayor garantía del fabricante","correct":false},{"text":"Acceso al mismo valor funcional a un coste significativamente menor","correct":true},{"text":"Es siempre de mayor calidad","correct":false},{"text":"No paga IVA","correct":false}]'::jsonb WHERE id=52;

UPDATE submissions SET content='El gasto en alimentación es uno de los mayores y más controlables del presupuesto. Planificar menús semanales, cocinar en casa y reducir el desperdicio puede bajar hasta un 40% este gasto.', tips='["Planifica la semana antes de ir al supermercado con lista en mano","Cocina en batch (2h los domingos para 4-5 días) ahorra tiempo y dinero","El 30% de la comida que compramos en España se tira; es dinero literalmente a la basura"]'::jsonb, quiz_question='¿Qué hábito reduce más eficazmente el gasto en alimentación?', quiz_options='[{"text":"Comprar solo marcas blancas","correct":false},{"text":"Planificar menús semanales antes de ir al supermercado","correct":true},{"text":"Comer fuera solo los fines de semana","correct":false},{"text":"Hacer una compra grande mensual","correct":false}]'::jsonb WHERE id=53;

UPDATE submissions SET content='La tecnología deprecia rápido. El móvil del año pasado hace el 95% de lo que hace el de este año al 50% del precio. Actualizar por actualizar es gasto puro.', tips='["Antes de cambiar de dispositivo: ¿el actual hace lo que necesito? Si sí, no lo cambies","El ciclo de reemplazo ideal de un smartphone es 3-4 años, no 1-2","Los gadgets «de moda» suelen estar en reventa a mitad de precio en 6 meses"]'::jsonb, quiz_question='¿Cuándo está justificado actualizar un dispositivo tecnológico desde una perspectiva financiera?', quiz_options='[{"text":"Cuando sale una nueva versión","correct":false},{"text":"Cuando el actual ya no cumple adecuadamente las funciones que necesitas","correct":true},{"text":"Cada 2 años como máximo","correct":false},{"text":"Cuando el precio baja un 10%","correct":false}]'::jsonb WHERE id=54;

UPDATE submissions SET content='La presión social para gastar (quedadas caras, regalos desproporcionados, vacaciones de lujo) es real. Aprender a decir «no» o proponer alternativas más económicas es una habilidad financiera clave.', tips='["Propón alternativas: cena en casa vs restaurante, escapada cercana vs vuelo largo","Los amigos que te presionan a gastar lo que no tienes no son buenos aliados financieros","Ser honesto sobre tu presupuesto es más respetable que endeudarse por quedar bien"]'::jsonb, quiz_question='¿Cuál es la estrategia más sana para manejar la presión social al gasto?', quiz_options='[{"text":"Aceptar siempre para no crear conflictos sociales","correct":false},{"text":"Proponer alternativas asequibles o decir no honestamente sin sentir vergüenza","correct":true},{"text":"Pedir dinero prestado para no quedarse fuera","correct":false},{"text":"Evitar cualquier evento social para no gastar","correct":false}]'::jsonb WHERE id=55;

UPDATE submissions SET content='El consumo consciente pregunta: ¿quién lo fabricó? ¿en qué condiciones? ¿cuánto durará? ¿qué pasa cuando lo tiro? El coste real de un producto va más allá del precio en la etiqueta.', tips='["Comprar menos pero de mayor calidad suele ser más económico a largo plazo","Un calzado de 150€ que dura 5 años es más barato que uno de 40€ que dura 8 meses","El coste medioambiental también importa: fast fashion es barato a corto, caro a largo"]'::jsonb, quiz_question='¿Qué concepto describe mejor el «coste total» de un producto?', quiz_options='[{"text":"Solo el precio de compra","correct":false},{"text":"El precio más los gastos de mantenimiento y reemplazo durante su vida útil","correct":true},{"text":"El precio menos los descuentos obtenidos","correct":false},{"text":"El coste de financiarlo si se paga a plazos","correct":false}]'::jsonb WHERE id=56;

UPDATE submissions SET content='La regla de las 48/72 horas propone esperar ese tiempo antes de hacer cualquier compra no planificada. La mayoría de los impulsos de compra desaparecen solos en ese período.', tips='["Para compras grandes, espera 72h; para compras medianas, 24-48h","Si después del período sigues queriéndolo y encaja en el presupuesto, cómpralo sin culpa","Añadir el artículo a un «listado de deseos» y revisarlo cada semana también funciona"]'::jsonb, quiz_question='¿Cuál es el objetivo principal de la regla de espera antes de comprar?', quiz_options='[{"text":"Conseguir mejores precios esperando rebajas","correct":false},{"text":"Dejar que el impulso emocional se disipe para tomar una decisión más racional","correct":true},{"text":"Verificar si el producto tiene mejores valoraciones","correct":false},{"text":"Dar tiempo a que el banco apruebe el gasto","correct":false}]'::jsonb WHERE id=57;

UPDATE submissions SET content='Pagar con efectivo genera más «dolor» que con tarjeta porque el dinero es físicamente visible. Esto lleva a gastar menos en efectivo. Quienes usan tarjeta gastan estadísticamente más.', tips='["Para categorías donde tiendes a gastar de más, prueba usar efectivo","El pago sin contacto y el autopago en apps eliminan el «dolor» psicológico de pagar","No es que el efectivo sea mejor; es que hace más consciente el gasto"]'::jsonb, quiz_question='¿Por qué pagar con efectivo puede reducir el gasto impulsivo respecto a la tarjeta?', quiz_options='[{"text":"El efectivo tiene tipo de cambio más favorable","correct":false},{"text":"El efectivo hace el coste más tangible y visible, aumentando la conciencia del gasto","correct":true},{"text":"Los comercios ofrecen descuentos con efectivo","correct":false},{"text":"Las tarjetas cobran comisiones por cada compra","correct":false}]'::jsonb WHERE id=58;

UPDATE submissions SET content='Revisar y analizar el gasto discrecional (ocio, ropa, restaurantes, caprichos) mes a mes te ayuda a detectar patrones y tomar decisiones más informadas sobre dónde y cómo disfrutas tu dinero.', tips='["Separa el gasto discrecional del necesario en tu presupuesto para verlo claramente","No se trata de eliminar el gasto discrecional sino de elegirlo conscientemente","Si no llevas registro, nunca sabrás cuánto gastas realmente en cada cosa"]'::jsonb, quiz_question='¿Qué beneficio tiene registrar el gasto discrecional mes a mes?', quiz_options='[{"text":"Reduce automáticamente ese tipo de gastos","correct":false},{"text":"Permite detectar patrones y tomar decisiones más conscientes sobre el ocio y los caprichos","correct":true},{"text":"Lo exige la agencia tributaria","correct":false},{"text":"Genera deducciones fiscales","correct":false}]'::jsonb WHERE id=59;

UPDATE submissions SET content='El gasto discrecional no es el enemigo; es parte del bienestar. El objetivo es que cada euro discrecional sea elegido conscientemente, no que desaparezca por inercia o impulso.', tips='["Asigna un presupuesto de «dinero libre» sin justificación; úsalo sin culpa","La privación excesiva crea rebotes de gasto compulsivo","Disfrutar conscientemente del dinero es también educación financiera"]'::jsonb, quiz_question='¿Cuál es la actitud más sana hacia el gasto discrecional (ocio, caprichos)?', quiz_options='[{"text":"Eliminarlo completamente para maximizar el ahorro","correct":false},{"text":"Dejarlo fluir libremente porque la vida es corta","correct":false},{"text":"Asignarle un presupuesto y disfrutarlo conscientemente dentro de ese límite","correct":true},{"text":"Solo permitirlo cuando la cuenta supere cierto saldo","correct":false}]'::jsonb WHERE id=60;

-- Campaign: Metas Financieras (IDs 61-75)
UPDATE submissions SET content='Una meta financiera SMART es Específica (qué), Medible (cuánto), Alcanzable (realista), Relevante (importa de verdad) y Temporal (cuándo). Sin estas condiciones, es solo un deseo vago.', tips='["«Ahorrar más» no es una meta; «ahorrar 300€/mes para fondo de emergencia en 12 meses» sí lo es","La temporalidad crea urgencia real; sin fecha límite, todo se pospone indefinidamente","Escribe tus metas: las metas escritas tienen el doble de probabilidad de cumplirse"]'::jsonb, quiz_question='¿Cuál de estas es una meta financiera SMART?', quiz_options='[{"text":"Quiero ser rico algún día","correct":false},{"text":"Voy a ahorrar más este año","correct":false},{"text":"Ahorraré 200€/mes durante 18 meses para un fondo de emergencia de 3.600€","correct":true},{"text":"Dejar de gastar tanto en tonterías","correct":false}]'::jsonb WHERE id=61;

UPDATE submissions SET content='Las metas a corto plazo son para 1-2 años (fondo de emergencia, vacaciones, pago de deuda). A medio plazo, 3-5 años (coche, reforma, entrada de piso). A largo plazo, 10+ años (jubilación, independencia financiera).', tips='["Trabaja en los tres horizontes simultáneamente, no secuencialmente","Las metas cortas crean hábito y confianza para las grandes","Revisar metas a largo plazo cada año evita que se conviertan en sueños sin tracción"]'::jsonb, quiz_question='¿Por qué es importante tener metas en los tres horizontes temporales (corto, medio y largo plazo)?', quiz_options='[{"text":"Para diversificar el riesgo","correct":false},{"text":"Porque las de corto plazo generan hábito y las de largo aseguran el futuro, y ambas son necesarias","correct":true},{"text":"Por requisitos de los asesores financieros","correct":false},{"text":"Para pagar menos impuestos","correct":false}]'::jsonb WHERE id=62;

UPDATE submissions SET content='Cuando tienes varias metas compitiendo por el mismo dinero, hay que priorizarlas. Generalmente: fondo de emergencia → deuda cara → metas básicas → inversión a largo plazo.', tips='["Construye el fondo de emergencia antes de invertir agresivamente","Pagar deuda al 20% TAE es equivalente a una inversión garantizada al 20%","Una vez cubiertos los básicos, el orden de las demás metas es personal"]'::jsonb, quiz_question='¿Cuál debería ser la primera prioridad financiera antes que cualquier otra meta de ahorro?', quiz_options='[{"text":"Invertir en bolsa para el largo plazo","correct":false},{"text":"Comprar una vivienda","correct":false},{"text":"Construir un fondo de emergencia","correct":true},{"text":"Pagar el plan de pensiones","correct":false}]'::jsonb WHERE id=63;

UPDATE submissions SET content='Para una meta específica (vacaciones, coche, entrada de piso), calcula el importe total y divide entre los meses disponibles. Ese es tu ahorro mensual mínimo para esa meta.', tips='["Abre una cuenta separada con el nombre de la meta para mantener el foco","Automatiza la transferencia mensual el día de cobro","Si ahorras más de lo mínimo un mes, no lo celebres gastando más en otro"]'::jsonb, quiz_question='Si necesitas 6.000€ para una entrada de piso en 24 meses, ¿cuánto debes ahorrar mensualmente para esa meta?', quiz_options='[{"text":"150€/mes","correct":false},{"text":"200€/mes","correct":false},{"text":"250€/mes","correct":true},{"text":"300€/mes","correct":false}]'::jsonb WHERE id=64;

UPDATE submissions SET content='Visualizar con detalle el resultado de alcanzar una meta activa el sistema límbico y aumenta la motivación. No es magia; es neurociencia del comportamiento.', tips='["Pon una imagen de tu meta donde la veas cada día: fondo de pantalla, nevera, escritorio","Describe en un papel cómo te sientes cuando alcanzas la meta y léelo cuando flaquee la motivación","Combina visualización con planificación concreta; una sola no basta"]'::jsonb, quiz_question='¿Para qué sirve visualizar claramente el resultado de una meta financiera?', quiz_options='[{"text":"Para que el banco apruebe el préstamo más rápido","correct":false},{"text":"Porque la visualización detallada activa la motivación y refuerza el compromiso con la meta","correct":true},{"text":"No tiene base racional, es solo autoayuda","correct":false},{"text":"Para calcular el plazo más rápido","correct":false}]'::jsonb WHERE id=65;

UPDATE submissions SET content='Un sistema de rendición de cuentas (compañero de metas, asesor financiero, registro público) aumenta significativamente la tasa de cumplimiento de metas financieras.', tips='["Comparte una meta con alguien de confianza y programa revisiones mensuales","Un «compañero de metas» que también tiene sus propias metas crea responsabilidad mutua","Si llevas registro escrito de tu progreso, es más difícil hacer trampa con uno mismo"]'::jsonb, quiz_question='¿Cómo mejora un sistema de rendición de cuentas el cumplimiento de metas financieras?', quiz_options='[{"text":"Aumenta el rendimiento de las inversiones","correct":false},{"text":"Crea compromiso externo que refuerza el interno y hace más difícil abandonar","correct":true},{"text":"Permite deducciones fiscales adicionales","correct":false},{"text":"Elimina la necesidad de presupuestar","correct":false}]'::jsonb WHERE id=66;

UPDATE submissions SET content='Automatizar las transferencias de ahorro elimina la fricción y la decisión diaria. Si el dinero no llega a la cuenta corriente, no puedes gastarlo inconscientemente.', tips='["Programa la transferencia para el día de cobro, no para el final del mes","Empieza con un importe pequeño que no duele; auméntalo progresivamente","La automatización del ahorro es el único hack de productividad financiera que realmente funciona"]'::jsonb, quiz_question='¿Cuál es la ventaja principal de automatizar las transferencias de ahorro?', quiz_options='[{"text":"Genera intereses automáticamente más altos","correct":false},{"text":"Elimina la necesidad de tomar la decisión de ahorrar cada mes, reduciendo el riesgo de posponerlo","correct":true},{"text":"Lo requieren los bancos para productos de ahorro","correct":false},{"text":"Reduce los impuestos sobre el ahorro","correct":false}]'::jsonb WHERE id=67;

UPDATE submissions SET content='Las metas financieras deben revisarse y ajustarse ante cambios de vida: cambio de trabajo, relación, hijo, enfermedad. No son promesas inamovibles sino guías dinámicas.', tips='["Revisa tus metas al menos una vez al año y ante cualquier cambio importante","Ajustar una meta no es fracasar; es adaptarse a la realidad","Metas rígidas que no se cumplen desmotivan más que metas ajustadas con criterio"]'::jsonb, quiz_question='¿Qué deberías hacer con tus metas financieras al producirse un cambio importante en tu vida?', quiz_options='[{"text":"Ignorar el cambio y seguir con el plan original","correct":false},{"text":"Abandonar todas las metas y empezar desde cero","correct":false},{"text":"Revisar y ajustar las metas para que reflejen la nueva realidad","correct":true},{"text":"Dejar de ahorro hasta que la situación se estabilice","correct":false}]'::jsonb WHERE id=68;

UPDATE submissions SET content='Los hitos son metas intermedias en el camino a una meta grande. Alcanzarlos libera dopamina y mantiene la motivación en objetivos de largo plazo que tardan años en cumplirse.', tips='["Divide una meta de 5 años en hitos anuales o trimestrales","Celebra cada hito de forma proporcional (no gastes la mitad del ahorro al llegar a la mitad)","Los hitos también son puntos de revisión del plan"]'::jsonb, quiz_question='¿Para qué sirven los hitos en el camino hacia una meta financiera a largo plazo?', quiz_options='[{"text":"Para pagar menos impuestos por tramos","correct":false},{"text":"Para mantener la motivación y poder verificar el progreso en el camino","correct":true},{"text":"Para que el banco haga seguimiento","correct":false},{"text":"Son solo para metas de más de 100.000€","correct":false}]'::jsonb WHERE id=69;

UPDATE submissions SET content='La jubilación es la mayor meta financiera de la vida para la mayoría. Cuanto antes empieces a contribuir, más trabaja el interés compuesto a tu favor.', tips='["Empezar a los 30 con 200€/mes da más resultado que empezar a los 45 con 500€/mes","El sistema público de pensiones en España está bajo presión; diversificar con plan privado es prudente","Calcula cuánto necesitas para jubilarte: gastos estimados × 25 es una regla rápida"]'::jsonb, quiz_question='¿Por qué es importante empezar a planificar la jubilación lo antes posible?', quiz_options='[{"text":"Porque la seguridad social lo exige","correct":false},{"text":"Para aprovechar el efecto del interés compuesto durante más tiempo","correct":true},{"text":"Porque los planes de pensiones solo admiten aportaciones en edades tempranas","correct":false},{"text":"Los jóvenes pagan menos comisiones en fondos de pensiones","correct":false}]'::jsonb WHERE id=70;

UPDATE submissions SET content='Invertir en formación y habilidades tiene un retorno entre los más altos de cualquier inversión. Una habilidad que aumenta tu ingreso un 20% genera ese retorno de por vida.', tips='["Calcula el ROI de un curso: coste vs incremento esperado de ingresos durante los próximos años","La formación gratuita (YouTube, libros, comunidades) tiene el mejor ratio de todos","No toda formación es inversión; cursos sin aplicación práctica son gasto, no inversión"]'::jsonb, quiz_question='¿Qué hace que la inversión en formación y habilidades sea tan valiosa?', quiz_options='[{"text":"Tiene deducción fiscal siempre","correct":false},{"text":"El retorno en mayor capacidad de ingresos dura toda la vida laboral","correct":true},{"text":"Es la única inversión sin riesgo","correct":false},{"text":"Garantiza empleo en cualquier sector","correct":false}]'::jsonb WHERE id=71;

UPDATE submissions SET content='Ahorrar para experiencias (viajes, conciertos, formaciones, momentos especiales) es tan válido como ahorrar para activos. Las experiencias tienden a proporcionar bienestar más duradero que los objetos.', tips='["Crea un «fondo de experiencias» separado del de ahorro estructural","Planificar una experiencia con antelación la abarata significativamente (vuelos, alojamiento)","No confundas experiencia con gasto impulsivo; una experiencia planificada es una inversión en bienestar"]'::jsonb, quiz_question='Desde una perspectiva de bienestar, ¿qué tiende a generar más satisfacción duradera según la investigación?', quiz_options='[{"text":"Comprar objetos materiales de alta calidad","correct":false},{"text":"Las experiencias vividas como viajes o momentos especiales con personas cercanas","correct":true},{"text":"Tener el mayor saldo posible en la cuenta bancaria","correct":false},{"text":"Acumular más propiedades y activos","correct":false}]'::jsonb WHERE id=72;

UPDATE submissions SET content='La compra de vivienda es la mayor decisión financiera de la vida para la mayoría. Alquilar o comprar depende del mercado local, la estabilidad vital y el horizonte temporal.', tips='["La regla general: si planeas quedarte menos de 5-7 años, alquilar suele ser mejor","Incluye todos los costes de propiedad: hipoteca, comunidad, IBI, mantenimiento, seguro","En España, el coste de compraventa (impuestos + notaría) es del 10-15%; necesitas eso en ahorros previos"]'::jsonb, quiz_question='¿Cuál es un indicador clave para decidir entre comprar o alquilar vivienda?', quiz_options='[{"text":"El precio absoluto del inmueble","correct":false},{"text":"El horizonte temporal de permanencia en esa ciudad o zona","correct":true},{"text":"El número de habitaciones necesarias","correct":false},{"text":"El tipo de interés actual del BCE","correct":false}]'::jsonb WHERE id=73;

UPDATE submissions SET content='La libertad financiera es el punto donde tus activos generan suficientes ingresos pasivos para cubrir tus gastos, sin necesidad de trabajar por obligación. Es una meta, no un sueño.', tips='["Define TU número: gastos anuales × 25 (regla del 4% de retirada segura)","No es una meta de todo o nada; puedes ir hacia ella gradualmente reduciendo la dependencia del trabajo","La libertad financiera no significa no trabajar, sino poder elegir qué trabajar"]'::jsonb, quiz_question='¿Cuál es la definición más precisa de libertad financiera?', quiz_options='[{"text":"Tener más de 1 millón de euros ahorrados","correct":false},{"text":"No tener deudas de ningún tipo","correct":false},{"text":"Que tus activos generen suficientes ingresos para cubrir todos tus gastos sin depender del trabajo","correct":true},{"text":"Ganar más de 10.000€/mes","correct":false}]'::jsonb WHERE id=74;

UPDATE submissions SET content='Celebrar el progreso financiero refuerza los comportamientos positivos. Reconocer que llegaste a una meta, aunque sea pequeña, consolida el hábito de seguir avanzando.', tips='["Celebra de forma proporcional y sin deshacer el progreso","El reconocimiento no tiene que ser económico: compartirlo con alguien también vale","Un diario de metas completadas es motivador releer cuando la constancia flaquea"]'::jsonb, quiz_question='¿Por qué es importante celebrar y reconocer el progreso en metas financieras?', quiz_options='[{"text":"Para poder gastar el dinero ahorrado","correct":false},{"text":"Porque el reconocimiento del progreso refuerza el hábito y la motivación para continuar","correct":true},{"text":"Es un requisito de los asesores financieros","correct":false},{"text":"Para informar a hacienda de los objetivos cumplidos","correct":false}]'::jsonb WHERE id=75;

COMMIT;
