BEGIN;

-- ============================================================
-- POLO ESTE (Innovación/Trading) — IDs 151-225
-- ============================================================

-- Campaign: Introducción al Trading (IDs 151-165)
UPDATE submissions SET content='El trading es la compra y venta de activos financieros (acciones, divisas, criptomonedas, materias primas) con el objetivo de obtener beneficio de los movimientos de precio.', tips='["Trading ≠ inversión: el trading busca beneficio a corto/medio plazo; la inversión es largo plazo","La mayoría de traders minoristas pierde dinero; el conocimiento es la ventaja principal","Empezar con capital que puedes permitirte perder es una regla de supervivencia"]'::jsonb, quiz_question='¿Cuál es la diferencia principal entre trading e inversión a largo plazo?', quiz_options='[{"text":"El trading usa acciones y la inversión usa criptomonedas","correct":false},{"text":"El trading busca beneficio de movimientos de precio a corto plazo; la inversión busca retorno a largo plazo","correct":true},{"text":"La inversión es solo para instituciones financieras","correct":false},{"text":"El trading no tiene riesgo si se hace bien","correct":false}]'::jsonb WHERE id=151;

UPDATE submissions SET content='Los mercados principales son: renta variable (acciones), renta fija (bonos), divisas (forex), materias primas (commodities) y criptomonedas. Cada uno tiene sus propias dinámicas y horarios.', tips='["Las acciones cotizan en horario de mercado (9-17:30 CET en Europa, 14:30-21 CET en EE.UU.)","El forex opera 24h/5 días; las criptomonedas 24/7","Cada mercado tiene su propio nivel de volatilidad y liquidez"]'::jsonb, quiz_question='¿Qué mercado opera las 24 horas, los 7 días de la semana?', quiz_options='[{"text":"Bolsa de Nueva York","correct":false},{"text":"Mercado de divisas (Forex)","correct":false},{"text":"Mercado de criptomonedas","correct":true},{"text":"Mercado de materias primas","correct":false}]'::jsonb WHERE id=152;

UPDATE submissions SET content='El precio de un activo es el resultado del equilibrio entre compradores (demanda) y vendedores (oferta). El bid es el precio que el comprador paga; el ask es el precio al que el vendedor vende. La diferencia es el spread.', tips='["El spread es un coste implícito: siempre entras al ask y sales al bid","Mayor spread = menor liquidez = mayor coste por operación","En mercados muy líquidos (EUR/USD, BTC/USDT) el spread es mínimo"]'::jsonb, quiz_question='¿Qué representa el «spread» en un activo financiero?', quiz_options='[{"text":"La comisión del broker","correct":false},{"text":"La diferencia entre el precio de compra (ask) y el precio de venta (bid)","correct":true},{"text":"El impuesto sobre la operación","correct":false},{"text":"La variación diaria del precio","correct":false}]'::jsonb WHERE id=153;

UPDATE submissions SET content='Una orden de mercado se ejecuta inmediatamente al mejor precio disponible. Una orden limitada se ejecuta solo si el precio alcanza el nivel que especificas. Cada una tiene su momento óptimo.', tips='["Orden de mercado: velocidad de ejecución garantizada pero precio incierto","Orden limitada: precio garantizado pero no se garantiza la ejecución","En mercados ilíquidos o volátiles, usar órdenes de mercado puede ser muy caro por el slippage"]'::jsonb, quiz_question='¿Cuándo es preferible usar una orden limitada en lugar de una orden de mercado?', quiz_options='[{"text":"Cuando quieres ejecutar inmediatamente a cualquier precio","correct":false},{"text":"Cuando quieres controlar el precio de entrada y aceptas que puede no ejecutarse","correct":true},{"text":"Solo funciona en acciones, no en criptomonedas","correct":false},{"text":"Cuando el mercado está muy líquido","correct":false}]'::jsonb WHERE id=154;

UPDATE submissions SET content='El mercado spot es la compra/venta del activo real con entrega inmediata. Los derivados (futuros, opciones, perpetuos) son contratos sobre el precio futuro del activo y permiten apalancamiento.', tips='["En spot, lo que compras lo tienes: si cae a cero, pierdes lo invertido","Con futuros apalancados, puedes perder más de lo invertido","Para empezar: spot siempre, derivados solo con experiencia y comprensión del riesgo"]'::jsonb, quiz_question='¿Cuál es el riesgo adicional de operar con futuros apalancados frente al mercado spot?', quiz_options='[{"text":"Pagar más comisiones","correct":false},{"text":"Puedes perder más de tu inversión inicial debido al apalancamiento","correct":true},{"text":"Solo puedes ganar en mercados alcistas","correct":false},{"text":"Los futuros tienen menos liquidez que el spot","correct":false}]'::jsonb WHERE id=155;

UPDATE submissions SET content='Un broker o exchange es el intermediario que te da acceso al mercado. Se diferencian en comisiones, regulación, productos disponibles y seguridad. Elegir bien es crítico.', tips='["Para criptomonedas: exchanges regulados con seguros (Coinbase, Kraken, Binance)","Para acciones: brokers regulados por la CNMV, SEC o FCA","Nunca dejes más capital del necesario en un exchange; usa wallet propia para largo plazo"]'::jsonb, quiz_question='¿Cuál es el criterio más importante al elegir un broker o exchange para operar?', quiz_options='[{"text":"Que tenga la interfaz más moderna","correct":false},{"text":"Regulación y seguridad, comisiones, y productos disponibles","correct":true},{"text":"Que sea el más popular entre influencers","correct":false},{"text":"Que ofrezca el mayor apalancamiento","correct":false}]'::jsonb WHERE id=156;

UPDATE submissions SET content='Los mercados de acciones tienen horarios fijos de apertura y cierre. Los grandes eventos macroeconómicos (datos de empleo, inflación, decisiones del BCE/Fed) mueven los mercados en momentos concretos.', tips='["Los primeros y últimos 30 minutos de sesión suelen tener más volatilidad","Evita operar en los minutos previos a publicaciones importantes sin saber el dato","El horario europeo y americano se solapan: 14:30-17:30 CET es el período más activo"]'::jsonb, quiz_question='¿Por qué los primeros y últimos 30 minutos de la sesión bursátil suelen tener más volatilidad?', quiz_options='[{"text":"Por las vacaciones de los traders profesionales","correct":false},{"text":"Por la concentración de órdenes en apertura y cierre de grandes fondos e inversores institucionales","correct":true},{"text":"Por cambios automáticos en los sistemas informáticos","correct":false},{"text":"Por la diferencia horaria con Asia","correct":false}]'::jsonb WHERE id=157;

UPDATE submissions SET content='Una vela japonesa (candlestick) muestra en una sola barra: precio de apertura, cierre, máximo y mínimo de un período. Verde/blanca = subida; roja/negra = bajada. Son el lenguaje visual del precio.', tips='["OHLCV: Open, High, Low, Close, Volume — los 5 datos clave de cada vela","Una vela no te dice nada; el patrón de varias velas sí","El cuerpo de la vela (apertura-cierre) es más importante que las mechas (máximo-mínimo)"]'::jsonb, quiz_question='¿Qué información contiene una vela japonesa de 1 hora?', quiz_options='[{"text":"Solo el precio actual","correct":false},{"text":"El precio de apertura, cierre, máximo y mínimo de esa hora, y el volumen","correct":true},{"text":"El precio promedio de las últimas 24 horas","correct":false},{"text":"El volumen de operaciones del día","correct":false}]'::jsonb WHERE id=158;

UPDATE submissions SET content='La liquidez mide qué tan fácil es comprar o vender un activo sin mover su precio. Alta liquidez = spread pequeño, ejecución rápida. Baja liquidez = spread amplio, slippage posible.', tips='["El volumen es el indicador más directo de liquidez: mayor volumen = mayor liquidez","No operes activos con poco volumen si no entiendes el riesgo de slippage","Bitcoin y el S&P 500 son ejemplos de alta liquidez; altcoins pequeñas, de baja"]'::jsonb, quiz_question='¿Qué problema puede ocurrir al operar un activo con baja liquidez?', quiz_options='[{"text":"Las comisiones son más bajas","correct":false},{"text":"El precio puede moverse significativamente al entrar o salir (slippage)","correct":true},{"text":"No se puede hacer análisis técnico","correct":false},{"text":"Los impuestos son más altos","correct":false}]'::jsonb WHERE id=159;

UPDATE submissions SET content='Los brokers cobran de tres formas: comisión por operación (fija o %), spread (diferencia bid/ask), y swap/financiación nocturna en posiciones apalancadas. Los «cero comisiones» siempre cobran de alguna forma.', tips='["Calcula el coste total de cada operación antes de ejecutarla","Las comisiones pequeñas se acumulan y pueden comerse el beneficio en estrategias de alta frecuencia","Compara brokers por coste total de operación, no solo por la comisión visible"]'::jsonb, quiz_question='¿Cómo puede un broker ofrecer «comisión cero» y aun así obtener ingresos?', quiz_options='[{"text":"Es imposible, siempre hay comisión","correct":false},{"text":"A través del spread ampliado, financiación nocturna u otras comisiones indirectas","correct":true},{"text":"El broker es financiado por el gobierno","correct":false},{"text":"Vendiendo los datos de los traders a terceros exclusivamente","correct":false}]'::jsonb WHERE id=160;

UPDATE submissions SET content='El paper trading (operativa simulada con dinero ficticio) permite practicar estrategias sin riesgo real. Es el entrenamiento obligatorio antes de arriesgar capital real.', tips='["Opera en paper trading al menos 1-3 meses antes de usar dinero real","El paper trading no replica perfectamente la psicología del dinero real, pero educa la mecánica","Registra cada operación como si fuera real; el rigor en el papel predice el rigor real"]'::jsonb, quiz_question='¿Cuál es la limitación principal del paper trading respecto al trading real?', quiz_options='[{"text":"No tiene datos de mercado en tiempo real","correct":false},{"text":"No replica el impacto emocional del riesgo con dinero real","correct":true},{"text":"Solo funciona para criptomonedas","correct":false},{"text":"Las ganancias no son deducibles fiscalmente","correct":false}]'::jsonb WHERE id=161;

UPDATE submissions SET content='La psicología del trading es tan importante como la estrategia. El miedo y la codicia llevan a salir demasiado pronto o demasiado tarde. El control emocional es una ventaja competitiva.', tips='["FOMO (miedo a perderse el movimiento) y FUD (miedo, incertidumbre, duda) son trampas emocionales","Define tus entradas y salidas ANTES de abrir la posición, no durante","Un trader que no puede manejar 3 operaciones perdedoras seguidas sin emociones, no está listo"]'::jsonb, quiz_question='¿Qué es el FOMO en el contexto del trading?', quiz_options='[{"text":"Una estrategia de entrada basada en momentum","correct":false},{"text":"El miedo a perderse un movimiento, que lleva a entrar tarde en posiciones ya avanzadas","correct":true},{"text":"Un indicador técnico de sobrecompra","correct":false},{"text":"Una comisión por operaciones fuera de horario","correct":false}]'::jsonb WHERE id=162;

UPDATE submissions SET content='Un mercado alcista (bull market) sube sostenidamente durante tiempo; un mercado bajista (bear market) cae un 20%+ desde máximos y puede durar meses o años. Cada uno requiere estrategias diferentes.', tips='["En bull market, la mayoría de activos sube; en bear, la mayoría baja","Mantener cash o short en bear market es una posición válida, no cobardía","Los mejores años para construir posiciones son los bear markets"]'::jsonb, quiz_question='¿Cuándo se considera oficialmente que un mercado ha entrado en «bear market»?', quiz_options='[{"text":"Cuando cae un 5% en un día","correct":false},{"text":"Cuando cae un 20% o más desde sus máximos recientes de forma sostenida","correct":true},{"text":"Cuando el volumen de operaciones baja un 50%","correct":false},{"text":"Cuando el número de traders activos disminuye","correct":false}]'::jsonb WHERE id=163;

UPDATE submissions SET content='La capitalización de mercado (market cap) de un activo es precio × unidades en circulación. Es la métrica que mide el tamaño relativo de un activo y su peso en el mercado.', tips='["Bitcoin domina ~50% del market cap total de criptomonedas","Un proyecto con market cap pequeño tiene mayor potencial de subida y mayor riesgo","Nunca compares precios absolutos: una moneda a 0,001€ no es más barata que una a 50.000€"]'::jsonb, quiz_question='Si una criptomoneda tiene un precio de 2€ y 500 millones de unidades en circulación, ¿cuál es su market cap?', quiz_options='[{"text":"500 millones de euros","correct":false},{"text":"1.000 millones de euros","correct":true},{"text":"2.000 millones de euros","correct":false},{"text":"250 millones de euros","correct":false}]'::jsonb WHERE id=164;

UPDATE submissions SET content='El capital inicial en trading debe ser dinero que puedes permitirte perder completamente sin que afecte a tu vida. Empezar con 100-500€ y escalar con resultados reales es lo responsable.', tips='["Nunca uses dinero del fondo de emergencia, hipoteca o deuda para hacer trading","El tamaño del capital no define el aprendizaje; la calidad del proceso sí","Escala el capital solo cuando hayas demostrado rentabilidad durante al menos 3-6 meses"]'::jsonb, quiz_question='¿Cuál es la regla más importante sobre el capital inicial en trading?', quiz_options='[{"text":"Necesitas al menos 10.000€ para que valga la pena","correct":false},{"text":"Debe ser dinero que puedas permitirte perder totalmente sin afectar tu vida","correct":true},{"text":"Cuanto más capital, más rápido aprendes","correct":false},{"text":"El capital mínimo lo define el broker","correct":false}]'::jsonb WHERE id=165;

-- Campaign: Análisis Técnico (IDs 166-180)
UPDATE submissions SET content='Los gráficos de velas japonesas muestran visualmente la lucha entre compradores y vendedores. Cada vela cuenta una historia sobre quién controló el precio en ese período.', tips='["Una vela verde grande indica que los compradores dominaron claramente el período","Una mecha larga superior indica rechazo del precio alto: vendedores empujaron hacia abajo","Aprende primero 5-6 patrones clave en lugar de memorizar 100 patrones"]'::jsonb, quiz_question='¿Qué indica una vela con cuerpo pequeño y mechas largas en ambos extremos?', quiz_options='[{"text":"Una tendencia alcista muy fuerte","correct":false},{"text":"Indecisión en el mercado; compradores y vendedores están equilibrados","correct":true},{"text":"Una señal de venta inmediata","correct":false},{"text":"Alta liquidez en ese período","correct":false}]'::jsonb WHERE id=166;

UPDATE submissions SET content='El soporte es un nivel de precio donde históricamente el precio ha rebotado al alza (mucha demanda). La resistencia es donde el precio ha rebotado a la baja (mucha oferta). Son las zonas más importantes del análisis técnico.', tips='["Los niveles redondos (1.000, 50.000, 100) suelen actuar como soporte/resistencia psicológicos","Un soporte roto tiende a convertirse en resistencia y viceversa","Cuantas más veces se testea un nivel sin romperse, más fuerte se considera"]'::jsonb, quiz_question='¿Qué sucede normalmente cuando un nivel de soporte importante es roto con volumen alto?', quiz_options='[{"text":"El precio sube inmediatamente","correct":false},{"text":"El soporte roto tiende a convertirse en resistencia en el futuro","correct":true},{"text":"El activo queda suspendido de cotización","correct":false},{"text":"El volumen desaparece automáticamente","correct":false}]'::jsonb WHERE id=167;

UPDATE submissions SET content='Una línea de tendencia une mínimos crecientes (tendencia alcista) o máximos decrecientes (tendencia bajista). Operar en la dirección de la tendencia es estadísticamente más favorable.', tips='["«La tendencia es tu amiga hasta que se rompe» es una de las reglas más útiles del AT","Necesitas al menos 2-3 puntos de contacto para validar una línea de tendencia","Una ruptura de la línea de tendencia con volumen es una señal de cambio de dirección"]'::jsonb, quiz_question='¿Cuántos puntos de contacto se necesitan mínimo para validar una línea de tendencia?', quiz_options='[{"text":"1 punto","correct":false},{"text":"Al menos 2-3 puntos de contacto","correct":true},{"text":"5 puntos exactos","correct":false},{"text":"No importa el número de puntos","correct":false}]'::jsonb WHERE id=168;

UPDATE submissions SET content='La media móvil simple (SMA) promedia los últimos N cierres. La exponencial (EMA) da más peso a los datos recientes. Ambas suavizan el ruido y muestran la dirección de la tendencia.', tips='["SMA 200 en gráfico diario: activo sobre ella es alcista de largo plazo","EMA 20/50 cruce: EMA 20 cruza arriba a EMA 50 = señal alcista (golden cross)","Las medias móviles son indicadores rezagados; confirman tendencias, no las predicen"]'::jsonb, quiz_question='¿Qué se conoce como «golden cross» en análisis técnico?', quiz_options='[{"text":"Cuando el precio toca un máximo histórico","correct":false},{"text":"Cuando la media móvil corta (ej. EMA 20) cruza hacia arriba a la media larga (ej. EMA 50)","correct":true},{"text":"Cuando el volumen supera la media de 20 días","correct":false},{"text":"Cuando el RSI cruza el nivel 50","correct":false}]'::jsonb WHERE id=169;

UPDATE submissions SET content='El RSI (Índice de Fuerza Relativa) mide si un activo está sobrecomprado (>70) o sobrevendido (<30) en un período. No es una señal directa de entrada/salida sino de contexto.', tips='["RSI >70 no significa «vender ya»; en tendencias fuertes puede mantenerse meses en sobrecompra","RSI en sobrecompra + resistencia importante = señal más significativa","El RSI en marcos temporales altos (1D, 1W) es más fiable que en 5m o 15m"]'::jsonb, quiz_question='¿Qué significa que el RSI de un activo esté en 75?', quiz_options='[{"text":"El activo va a subir un 75% próximamente","correct":false},{"text":"El activo se encuentra en zona de sobrecompra","correct":true},{"text":"El activo tiene una tendencia bajista","correct":false},{"text":"El volumen es un 75% superior a la media","correct":false}]'::jsonb WHERE id=170;

UPDATE submissions SET content='El MACD (Moving Average Convergence Divergence) muestra la relación entre dos medias móviles. El cruce de la línea MACD con su señal, y el histograma, indican cambios de momentum.', tips='["MACD cruza arriba señal = momentum alcista emergente","Histograma positivo y creciendo = momentum alcista en aceleración","El MACD funciona mejor en mercados con tendencia; en rangos laterales genera señales falsas"]'::jsonb, quiz_question='¿En qué tipo de mercado funciona mejor el indicador MACD?', quiz_options='[{"text":"En mercados laterales sin tendencia","correct":false},{"text":"En mercados con tendencia clara (alcista o bajista)","correct":true},{"text":"Solo en mercados de divisas","correct":false},{"text":"En mercados con baja volatilidad únicamente","correct":false}]'::jsonb WHERE id=171;

UPDATE submissions SET content='El volumen confirma o niega los movimientos de precio. Una rotura de resistencia con volumen alto es válida; una rotura sin volumen es sospechosa y suele ser una trampa.', tips='["«El volumen precede al precio» es una de las observaciones más consistentes del AT","Una vela alcista grande con volumen muy bajo puede ser manipulación","El perfil de volumen (VPVR) muestra dónde se han hecho más operaciones históricamente"]'::jsonb, quiz_question='¿Por qué se dice que «el volumen confirma el precio» en análisis técnico?', quiz_options='[{"text":"Porque el volumen siempre sube antes que el precio","correct":false},{"text":"Porque las roturas de niveles significativas tienen respaldo de participación real del mercado","correct":true},{"text":"Por regulación de los mercados financieros","correct":false},{"text":"Porque el volumen determina el precio matemáticamente","correct":false}]'::jsonb WHERE id=172;

UPDATE submissions SET content='Los retrocesos de Fibonacci (23,6%, 38,2%, 50%, 61,8%, 78,6%) son niveles donde el precio tiende a pausar o rebotar tras un movimiento importante. Tienen validez estadística en muchos mercados.', tips='["El 61,8% (golden ratio) es el nivel de retroceso más respetado","Combina Fibonacci con soporte/resistencia previo para aumentar la validez de la zona","No uses Fibonacci en aislado; es una herramienta de confirmación, no de predicción"]'::jsonb, quiz_question='¿Cuál es el nivel de retroceso de Fibonacci considerado más importante o «golden ratio»?', quiz_options='[{"text":"23,6%","correct":false},{"text":"38,2%","correct":false},{"text":"50%","correct":false},{"text":"61,8%","correct":true}]'::jsonb WHERE id=173;

UPDATE submissions SET content='Los patrones de velas y gráfico (hombro-cabeza-hombro, triángulos, cuñas, doble techo, bandera) dan señales de continuación o reversión de tendencia. Tienen probabilidades estadísticas, no garantías.', tips='["El patrón HCH (hombro-cabeza-hombro) es uno de los patrones de reversión más fiables","Un triángulo simétrico puede romper en cualquier dirección; espera la rotura para actuar","Cuanto más tiempo tarda en formarse un patrón, más potente suele ser el movimiento posterior"]'::jsonb, quiz_question='¿Qué implica un patrón de «doble techo» en análisis técnico?', quiz_options='[{"text":"El precio va a continuar subiendo con fuerza","correct":false},{"text":"Una posible señal de reversión bajista tras no poder superar dos veces una resistencia","correct":true},{"text":"El activo pagará dividendos dos veces ese año","correct":false},{"text":"Una señal de consolidación lateral indefinida","correct":false}]'::jsonb WHERE id=174;

UPDATE submissions SET content='El marco temporal (timeframe) define la duración de cada vela. M1 (1 minuto) para scalping; H1-H4 para intradía; D1 para swing; W1 para inversión. Cada trader necesita el timeframe adecuado a su estrategia.', tips='["Cuanto menor el timeframe, más ruido y señales falsas","Empieza aprendiendo en H1 o H4: suficiente detalle sin el ruido del minuto","El timeframe define tu horizonte de gestión del trade: cuánto tiempo aguantas la posición abierta"]'::jsonb, quiz_question='¿Qué timeframe es más adecuado para una estrategia de swing trading (días a semanas)?', quiz_options='[{"text":"M1 (1 minuto)","correct":false},{"text":"M15 (15 minutos)","correct":false},{"text":"D1 (diario) o H4 (4 horas) para contexto","correct":true},{"text":"Tick chart","correct":false}]'::jsonb WHERE id=175;

UPDATE submissions SET content='El análisis multi-timeframe consiste en analizar el contexto en un timeframe mayor y buscar entradas en uno menor. La tendencia mayor filtra las señales del menor.', tips='["Regla: si en D1 es alcista, en H1 solo buscas entradas largas","La confluencia de señales en múltiples timeframes aumenta la probabilidad de éxito","Un setup en H1 contra la tendencia de D1 tiene probabilidades en contra"]'::jsonb, quiz_question='¿Cuál es la ventaja del análisis multi-timeframe?', quiz_options='[{"text":"Permite operar más mercados simultáneamente","correct":false},{"text":"El contexto del timeframe mayor filtra señales de menor calidad en el timeframe de entrada","correct":true},{"text":"Genera más señales de trading por día","correct":false},{"text":"Reduce automáticamente el riesgo por operación","correct":false}]'::jsonb WHERE id=176;

UPDATE submissions SET content='Una rotura (breakout) ocurre cuando el precio supera un nivel relevante. Un falso breakout (fakeout) es una rotura que regresa rápidamente dentro del rango. La confirmación con vela de cierre reduce las trampas.', tips='["Espera que la vela cierre por encima/debajo del nivel antes de considerar la rotura válida","Los falsos breakouts son frecuentes en niveles muy conocidos y muy vigilados","El retesteo del nivel roto como soporte antes de entrar es la entrada más conservadora"]'::jsonb, quiz_question='¿Cómo se puede filtrar un falso breakout (fakeout)?', quiz_options='[{"text":"Entrar siempre con orden de mercado nada más ver la rotura","correct":false},{"text":"Esperar la confirmación con cierre de vela sobre el nivel y posible retesteo","correct":true},{"text":"Usar solo RSI para confirmar","correct":false},{"text":"Los fakeouts solo ocurren en criptomonedas","correct":false}]'::jsonb WHERE id=177;

UPDATE submissions SET content='Una divergencia ocurre cuando el precio hace un nuevo máximo/mínimo pero el indicador (RSI, MACD) no lo confirma. Señala debilitamiento del momentum y posible reversión.', tips='["Divergencia bajista: precio hace máximo más alto, RSI hace máximo más bajo → posible techo","Divergencia alcista: precio hace mínimo más bajo, RSI hace mínimo más alto → posible suelo","Las divergencias son señales de alerta, no de entrada inmediata; busca confirmación adicional"]'::jsonb, quiz_question='¿Qué indica una divergencia bajista entre precio y RSI?', quiz_options='[{"text":"El RSI confirma la subida del precio","correct":false},{"text":"El precio hace un nuevo máximo pero el RSI no confirma, señalando debilitamiento alcista","correct":true},{"text":"Una señal de compra inmediata","correct":false},{"text":"Que el activo está sobrevendido","correct":false}]'::jsonb WHERE id=178;

UPDATE submissions SET content='Las Bandas de Bollinger (BB) son un canal dinámico formado por una media móvil central y dos bandas a ±2 desviaciones estándar. Miden la volatilidad relativa del activo.', tips='["Precio tocando banda superior en tendencia alcista → momentum, no sobrecompra automática","Compresión de bandas (squeeze) → explosión de volatilidad inminente","Las bandas de Bollinger funcionan mejor combinadas con otros indicadores"]'::jsonb, quiz_question='¿Qué indica una «compresión» de las Bandas de Bollinger?', quiz_options='[{"text":"El precio está en máximos históricos","correct":false},{"text":"La volatilidad se ha reducido y probablemente precede un movimiento explosivo","correct":true},{"text":"El activo va a caer","correct":false},{"text":"Los volúmenes han bajado al mínimo","correct":false}]'::jsonb WHERE id=179;

UPDATE submissions SET content='Un sistema de trading completo incluye: criterios de entrada, stop-loss, take profit, tamaño de posición y reglas de gestión. Sin sistema documentado, operas por emoción, no por estrategia.', tips='["Documenta cada componente del sistema antes de operar con dinero real","Backtestea el sistema con datos históricos para validar su edge estadístico","Un sistema mediocre aplicado con disciplina supera a uno excelente mal ejecutado"]'::jsonb, quiz_question='¿Cuál es el componente más importante de un sistema de trading?', quiz_options='[{"text":"Tener el indicador más sofisticado","correct":false},{"text":"Contar con todos los componentes (entrada, stop, TP, sizing) y aplicarlos con disciplina","correct":true},{"text":"Operar en el mercado más volátil","correct":false},{"text":"Tener acceso a información privilegiada","correct":false}]'::jsonb WHERE id=180;

-- Campaign: Trading con Bots (IDs 181-195)
UPDATE submissions SET content='El trading algorítmico usa software para ejecutar operaciones automáticamente según reglas predefinidas. Elimina el sesgo emocional y puede operar 24/7, pero requiere diseño, backtesting y supervisión.', tips='["Un bot es tan bueno como la estrategia que implementa","Los bots no predicen el mercado: ejecutan reglas. Si las reglas son malas, el bot amplifica las pérdidas","Empezar con bots simples y probados es más seguro que programar el propio desde cero"]'::jsonb, quiz_question='¿Cuál es la ventaja principal del trading algorítmico frente al trading manual?', quiz_options='[{"text":"Garantiza ganancias en todos los mercados","correct":false},{"text":"Elimina el sesgo emocional y permite operar de forma sistemática y consistente","correct":true},{"text":"No requiere conocimiento del mercado","correct":false},{"text":"Los reguladores lo tratan de forma más favorable fiscalmente","correct":false}]'::jsonb WHERE id=181;

UPDATE submissions SET content='Los tipos principales de bots son: grid (compra y vende en rangos de precio), DCA (promedia a la baja comprando a intervalos regulares), trend-following (sigue la tendencia) y arbitraje (explota diferencias de precio entre exchanges).', tips='["Grid: funciona bien en mercados laterales con oscilación","DCA: reduce el coste promedio de entrada pero acumula posición en bajadas","Arbitraje: requiere velocidad de ejecución y capital, difícil para minoristas"]'::jsonb, quiz_question='¿En qué tipo de mercado funciona mejor una estrategia de grid bot?', quiz_options='[{"text":"Mercados en tendencia alcista fuerte","correct":false},{"text":"Mercados laterales con oscilación de precio dentro de un rango","correct":true},{"text":"Mercados en caída libre","correct":false},{"text":"Solo en mercados de muy alta capitalización","correct":false}]'::jsonb WHERE id=182;

UPDATE submissions SET content='Los bots se conectan a los exchanges a través de APIs con clave pública y clave privada. La clave privada permite ejecutar órdenes y debe protegerse como una contraseña bancaria.', tips='["Nunca compartas tu API key privada con nadie","Activa solo los permisos necesarios: trading sí, retiro de fondos NO","Rota las API keys periódicamente; si sospechas compromiso, revócalas inmediatamente"]'::jsonb, quiz_question='¿Qué permiso NUNCA deberías activar en una API key destinada solo a un bot de trading?', quiz_options='[{"text":"Permiso de consulta de saldo","correct":false},{"text":"Permiso de crear órdenes","correct":false},{"text":"Permiso de retiro de fondos a wallet externa","correct":true},{"text":"Permiso de cancelar órdenes","correct":false}]'::jsonb WHERE id=183;

UPDATE submissions SET content='El backtesting aplica una estrategia a datos históricos para evaluar su rendimiento pasado. Es esencial para validar si una estrategia tiene ventaja estadística (edge) antes de usarla con dinero real.', tips='["El backtest pasado no garantiza resultados futuros, pero es la única validación objetiva disponible","Usa datos de al menos 1-2 años incluyendo distintos tipos de mercado (bull, bear, lateral)","Un backtest con muy pocas operaciones (menos de 50-100) no tiene validez estadística"]'::jsonb, quiz_question='¿Cuál es la limitación más importante del backtesting de estrategias?', quiz_options='[{"text":"Es muy costoso computacionalmente","correct":false},{"text":"El buen rendimiento histórico no garantiza el mismo rendimiento en el futuro","correct":true},{"text":"Solo funciona para estrategias de largo plazo","correct":false},{"text":"Los exchanges no permiten exportar datos históricos","correct":false}]'::jsonb WHERE id=184;

UPDATE submissions SET content='El overfitting (sobreajuste) ocurre cuando una estrategia se optimiza tanto para los datos históricos que pierde capacidad predictiva en datos nuevos. Es la trampa más común del backtesting.', tips='["Si una estrategia requiere 20+ parámetros para funcionar, probablemente está sobreajustada","Usa un conjunto de datos de validación «out-of-sample» que la estrategia no ha visto","Menos parámetros + lógica simple = estrategia más robusta"]'::jsonb, quiz_question='¿Cómo se puede detectar si una estrategia está sobreajustada (overfit)?', quiz_options='[{"text":"Funciona perfectamente en datos históricos pero falla en datos futuros no vistos","correct":true},{"text":"Tiene un ratio de ganancias superior al 90%","correct":false},{"text":"Opera con más de 10 activos simultáneamente","correct":false},{"text":"Usa más de 2 indicadores técnicos","correct":false}]'::jsonb WHERE id=185;

UPDATE submissions SET content='El paper trading de bots permite probar la estrategia en condiciones reales de mercado sin dinero real. Revela problemas que el backtesting no muestra: latencia, slippage, API errors.', tips='["Opera en paper trading al menos 1 mes antes de usar capital real con un bot nuevo","Monitoriza las métricas: ratio ganancia/pérdida, drawdown máximo, número de operaciones","Un bot que falla en paper trading fallará peor con dinero real"]'::jsonb, quiz_question='¿Qué problemas puede revelar el paper trading de bots que el backtesting no detecta?', quiz_options='[{"text":"Errores en la lógica de la estrategia","correct":false},{"text":"Problemas de latencia, slippage real y errores de conexión con la API","correct":true},{"text":"Fallos en el análisis técnico","correct":false},{"text":"Problemas fiscales de las operaciones","correct":false}]'::jsonb WHERE id=186;

UPDATE submissions SET content='Los parámetros de riesgo en un bot incluyen: tamaño máximo de posición, stop-loss global, número máximo de posiciones simultáneas y pérdida máxima diaria/semanal antes de pausar.', tips='["Define siempre una pérdida máxima diaria que detiene el bot automáticamente","El tamaño de posición es la palanca de riesgo más importante","Sin límites de riesgo programados, un bot puede perder todo el capital en horas en condiciones extremas"]'::jsonb, quiz_question='¿Por qué es crítico programar un límite de pérdida máxima diaria en un bot de trading?', quiz_options='[{"text":"Por requisitos regulatorios","correct":false},{"text":"Para proteger el capital en condiciones de mercado extremas que la estrategia no puede manejar","correct":true},{"text":"Para reducir las comisiones del exchange","correct":false},{"text":"Para cumplir con los términos del broker","correct":false}]'::jsonb WHERE id=187;

UPDATE submissions SET content='Las estrategias comunes de bots son: grid (rejilla de órdenes en rango), DCA (compras periódicas o escalonadas), trend-following (entrada en rotura de media móvil) y mean reversion (operar el regreso a la media).', tips='["Grid y DCA son estrategias de «acumulación» adecuadas para activos en los que crees a largo plazo","Trend-following funciona en mercados con tendencia; mean reversion en rangos","Combinar estrategias puede reducir la correlación y suavizar el equity curve"]'::jsonb, quiz_question='¿Para qué tipo de activo es más adecuada una estrategia DCA con bot?', quiz_options='[{"text":"Activos en los que no crees a largo plazo","correct":false},{"text":"Activos en los que crees a largo plazo y quieres acumular a precio promedio","correct":true},{"text":"Solo para stablecoins","correct":false},{"text":"Activos con alta volatilidad intradía siempre","correct":false}]'::jsonb WHERE id=188;

UPDATE submissions SET content='Los exchanges ofrecen APIs REST (petición-respuesta) y WebSocket (flujo en tiempo real). Los bots de alta frecuencia necesitan WebSocket; los de swing o DCA pueden usar REST.', tips='["Las API keys tienen límites de llamadas por minuto (rate limits); superar el límite bloquea el acceso","WebSocket es más eficiente para monitorizar precios en tiempo real","La documentación de la API del exchange es la referencia más importante al programar un bot"]'::jsonb, quiz_question='¿Qué tipo de conexión de API es más adecuada para un bot que necesita actualizaciones de precio en tiempo real?', quiz_options='[{"text":"API REST con polling cada segundo","correct":false},{"text":"WebSocket para recibir datos en streaming sin peticiones repetidas","correct":true},{"text":"API FIX Protocol","correct":false},{"text":"Webhook unidireccional","correct":false}]'::jsonb WHERE id=189;

UPDATE submissions SET content='Un bot en producción necesita monitorización constante: alertas de error, logs de operaciones, comprobación de conectividad y métricas de rendimiento. Los bots sin supervisión generan sorpresas desagradables.', tips='["Configura alertas de Telegram o email para errores críticos, operaciones abiertas anómalas y stop-loss activados","Revisa logs de operaciones al menos una vez al día","Ten un procedimiento documentado para detener el bot manualmente en caso de emergencia"]'::jsonb, quiz_question='¿Cuál es la práctica más importante para gestionar un bot de trading en producción?', quiz_options='[{"text":"Dejarlo correr sin intervención para no interferir","correct":false},{"text":"Monitorización activa con alertas de errores y revisión regular de logs","correct":true},{"text":"Reiniciarlo diariamente","correct":false},{"text":"Cambiar los parámetros constantemente según el mercado","correct":false}]'::jsonb WHERE id=190;

UPDATE submissions SET content='Un stop-loss automatizado en el bot cierra la posición si el precio cae hasta un nivel predefinido, limitando la pérdida máxima. Es la primera línea de defensa obligatoria en cualquier sistema automatizado.', tips='["El stop-loss debe estar definido ANTES de abrir la posición, nunca después","Un stop-loss «flotante» (trailing stop) permite acompañar la tendencia sin perder el beneficio acumulado","Nunca elimines un stop-loss porque «el precio volverá»; esa creencia destruye cuentas"]'::jsonb, quiz_question='¿Cuál es el error más peligroso relacionado con el stop-loss en un bot de trading?', quiz_options='[{"text":"Colocarlo muy ajustado al precio de entrada","correct":false},{"text":"Eliminarlo o moverlo más lejos porque «el precio volverá»","correct":true},{"text":"Usarlo en todos los trades","correct":false},{"text":"Configurarlo como orden limitada","correct":false}]'::jsonb WHERE id=191;

UPDATE submissions SET content='Las métricas clave de un bot son: tasa de acierto (% trades ganadores), ratio riesgo/recompensa, drawdown máximo (mayor caída desde un pico) y Sharpe ratio (retorno ajustado por riesgo).', tips='["Un bot con 40% de aciertos puede ser rentable si el ratio R:R es 1:3","El drawdown máximo es el indicador que más daño psicológico causa; ponlo en contexto","Un Sharpe ratio >1 indica retornos superiores al riesgo asumido"]'::jsonb, quiz_question='¿Puede un bot con solo un 40% de trades ganadores ser rentable a largo plazo?', quiz_options='[{"text":"No, necesitas más del 50% para ser rentable","correct":false},{"text":"Sí, si el beneficio promedio de los trades ganadores es suficientemente mayor que la pérdida promedio","correct":true},{"text":"Solo si opera en criptomonedas","correct":false},{"text":"No, la matemática no lo permite","correct":false}]'::jsonb WHERE id=192;

UPDATE submissions SET content='Las API keys de un exchange son credenciales de seguridad críticas. Almacenarlas en variables de entorno (no en el código), usar IP whitelisting y rotar periódicamente son prácticas básicas de seguridad.', tips='["Nunca hardcodees API keys en el código fuente ni las subas a GitHub","Usa siempre variables de entorno o un vault de secretos","IP whitelisting limita el uso de la key a tu servidor específico"]'::jsonb, quiz_question='¿Cuál es la práctica más importante para almacenar API keys de exchanges de forma segura?', quiz_options='[{"text":"Guardarlas en el código fuente del bot","correct":false},{"text":"Usar variables de entorno o vault de secretos, nunca hardcodeadas en el código","correct":true},{"text":"Compartirlas con el equipo para facilitar el mantenimiento","correct":false},{"text":"Guardarlas en un archivo de texto en el mismo servidor","correct":false}]'::jsonb WHERE id=193;

UPDATE submissions SET content='Los bots pueden fallar por: bugs en el código, errores de API del exchange, condiciones de mercado fuera del rango para el que fueron diseñados, o caídas de infraestructura. Tener un plan de contingencia es obligatorio.', tips='["Define qué posiciones abiertas cerrar manualmente si el bot falla","Haz pruebas de «kill switch» (cómo parar el bot de emergencia) periódicamente","Un bot diseñado para mercado lateral puede generar pérdidas grandes en tendencia fuerte"]'::jsonb, quiz_question='¿Por qué puede un bot que funciona bien en backtesting fallar en condiciones reales?', quiz_options='[{"text":"Porque los exchanges bloquean los bots exitosos","correct":false},{"text":"Por condiciones de mercado fuera del rango de diseño, errores de API, latencia o bugs no detectados","correct":true},{"text":"Porque los backtests siempre están mal calculados","correct":false},{"text":"Por restricciones regulatorias automáticas","correct":false}]'::jsonb WHERE id=194;

UPDATE submissions SET content='La supervisión humana es el complemento necesario de cualquier bot. Los bots ejecutan reglas; los humanos interpretan contexto (noticias, cisnes negros, cambios de mercado que el bot no puede anticipar).', tips='["Parar un bot durante eventos macroeconómicos importantes puede evitar pérdidas inesperadas","Revisa regularmente si las condiciones de mercado siguen siendo adecuadas para la estrategia del bot","Un bot+humano bien coordinados superan a un bot solo y a un humano solo en consistencia"]'::jsonb, quiz_question='¿Qué papel debe tener el trader humano en un sistema de trading automatizado?', quiz_options='[{"text":"Ninguno; la automatización total es el objetivo","correct":false},{"text":"Supervisión e interpretación de contexto que el bot no puede procesar (noticias, eventos extremos)","correct":true},{"text":"Ejecutar todas las operaciones manualmente igual que sin el bot","correct":false},{"text":"Solo recibir los beneficios al final del mes","correct":false}]'::jsonb WHERE id=195;

-- Campaign: DeFi y Web3 (IDs 196-210)
UPDATE submissions SET content='Una blockchain es una base de datos distribuida, inmutable y transparente donde se registran transacciones verificadas por una red de nodos. Bitcoin fue la primera blockchain funcional (2009).', tips='["Inmutable: lo que entra en la blockchain no puede modificarse ni borrarse","Descentralizada: no hay un servidor central ni una empresa que la controle","La transparencia es doble: todos pueden verificar, pero las identidades son pseudónimas"]'::jsonb, quiz_question='¿Cuál es la principal propiedad que hace a una blockchain diferente de una base de datos tradicional?', quiz_options='[{"text":"Es más rápida que cualquier base de datos convencional","correct":false},{"text":"Es descentralizada, inmutable y verificable sin necesidad de un intermediario central","correct":true},{"text":"Es completamente privada y anónima","correct":false},{"text":"Solo puede almacenar transacciones financieras","correct":false}]'::jsonb WHERE id=196;

UPDATE submissions SET content='Los smart contracts son programas que se ejecutan automáticamente en la blockchain cuando se cumplen condiciones predefinidas, sin necesidad de intermediarios. Ethereum fue el pionero en programabilidad.', tips='["Un smart contract es código: si hay un bug, no hay forma de «llamar al soporte»","Una vez desplegado, el contrato ejecuta exactamente lo que el código dice, para bien o para mal","Auditar el código de un smart contract antes de interactuar con él es práctica de seguridad básica"]'::jsonb, quiz_question='¿Qué hace que un smart contract sea «trustless» (sin necesidad de confianza)?', quiz_options='[{"text":"Que está regulado por instituciones financieras","correct":false},{"text":"Que su ejecución es automática según el código, sin posibilidad de intervención o manipulación humana","correct":true},{"text":"Que está firmado por abogados","correct":false},{"text":"Que utiliza encriptación de grado militar","correct":false}]'::jsonb WHERE id=197;

UPDATE submissions SET content='DeFi (Finanzas Descentralizadas) es el ecosistema de servicios financieros (préstamos, trading, ahorro, derivados) construidos sobre blockchain con smart contracts, sin intermediarios como bancos.', tips='["DeFi no tiene «atención al cliente»: si pierdes el acceso a tu wallet, nadie puede recuperarla","El TVL (Total Value Locked) indica cuánto capital hay comprometido en los protocolos DeFi","Mayor rendimiento en DeFi = mayor riesgo: audita siempre el protocolo antes de depositar"]'::jsonb, quiz_question='¿Cuál es la principal diferencia entre DeFi y los servicios financieros tradicionales (CeFi)?', quiz_options='[{"text":"DeFi es más rápido siempre","correct":false},{"text":"DeFi elimina los intermediarios centralizados usando smart contracts en blockchain","correct":true},{"text":"DeFi está regulado por los bancos centrales","correct":false},{"text":"DeFi solo funciona con Bitcoin","correct":false}]'::jsonb WHERE id=198;

UPDATE submissions SET content='Un DEX (exchange descentralizado) como Uniswap o dYdX permite intercambiar tokens directamente entre wallets, sin depositar en un exchange centralizado. Las órdenes se ejecutan contra pools de liquidez.', tips='["En un DEX, tú siempre controlas tus fondos: no hay riesgo de quiebra del exchange","El slippage en DEX puede ser alto si la liquidez del pool es baja","Los DEX de criptomonedas no requieren KYC (identificación), los CEX sí"]'::jsonb, quiz_question='¿Cuál es la principal ventaja de seguridad de un DEX respecto a un exchange centralizado (CEX)?', quiz_options='[{"text":"Los DEX tienen más pares de trading disponibles","correct":false},{"text":"En un DEX los fondos permanecen en tu propia wallet; no hay riesgo de hackeo del exchange","correct":true},{"text":"Los DEX tienen comisiones cero siempre","correct":false},{"text":"Los DEX están regulados por la SEC","correct":false}]'::jsonb WHERE id=199;

UPDATE submissions SET content='Los pools de liquidez son contratos inteligentes donde proveedores depositan pares de tokens para que otros usuarios puedan intercambiarlos. A cambio, los proveedores reciben comisiones de las operaciones.', tips='["El impermanent loss es el riesgo específico de los pools: si los precios divergen mucho, pierdes vs solo mantener","La ratio 50/50 de un pool se ajusta automáticamente mediante el AMM (Automated Market Maker)","Los pools con stablecoins tienen menos impermanent loss pero también menos comisiones"]'::jsonb, quiz_question='¿Qué es el «impermanent loss» en un pool de liquidez?', quiz_options='[{"text":"Las comisiones del gas en Ethereum","correct":false},{"text":"La pérdida potencial respecto a simplemente mantener los tokens, causada por la divergencia de precios en el pool","correct":true},{"text":"Un impuesto especial sobre la liquidez","correct":false},{"text":"La pérdida de liquidez al retirar fondos antes de tiempo","correct":false}]'::jsonb WHERE id=200;

UPDATE submissions SET content='El yield farming es la práctica de mover activos entre protocolos DeFi para maximizar el rendimiento (APY). Puede generar altos retornos pero también conlleva riesgos de smart contract, liquidez e impermanent loss.', tips='["APY del 1.000% suele indicar muy alto riesgo de rugpull o colapso del protocolo","Los protocolos más antiguos y auditados son más seguros, aunque con menor APY","Diversifica entre varios protocolos; nunca concentres en uno aunque el APY sea tentador"]'::jsonb, quiz_question='¿Qué riesgo específico del yield farming no existe en la banca tradicional?', quiz_options='[{"text":"El riesgo de variación del tipo de interés","correct":false},{"text":"El riesgo de smart contract: bugs o exploits que pueden vaciar el protocolo","correct":true},{"text":"El riesgo de inflación","correct":false},{"text":"El riesgo de impago del prestatario","correct":false}]'::jsonb WHERE id=201;

UPDATE submissions SET content='El staking es bloquear tokens para participar en la validación de la blockchain (Proof of Stake) o para obtener recompensas en un protocolo. Es una forma de generar rendimiento pasivo sobre criptoactivos.', tips='["El staking nativo (en la propia blockchain) es más seguro que el staking en protocolos de terceros","Verifica el período de «unbonding» (tiempo de espera para retirar): puede ser de días a semanas","Las recompensas de staking tributan como rendimiento del capital mobiliario en España"]'::jsonb, quiz_question='¿Cuál es el riesgo principal específico del staking en protocolos de terceros vs staking nativo?', quiz_options='[{"text":"No hay diferencia de riesgo","correct":false},{"text":"El riesgo adicional de smart contract del protocolo intermediario, además del riesgo de la blockchain base","correct":true},{"text":"El staking en protocolos terceros paga menos","correct":false},{"text":"No está permitido fiscalmente","correct":false}]'::jsonb WHERE id=202;

UPDATE submissions SET content='Las stablecoins son criptomonedas diseñadas para mantener un valor estable, usualmente 1:1 con el dólar. Existen respaldadas por fiat (USDC, USDT), por activos crypto (DAI) o algorítmicas (alto riesgo).', tips='["USDC y USDT son las más usadas; están respaldadas por reservas reales auditables","Las stablecoins algorítmicas (como Terra/LUNA) demostraron que pueden colapsar a cero en días","Aun en stablecoins hay riesgo: contrapartida, desacople, censura o hack"]'::jsonb, quiz_question='¿Por qué las stablecoins algorítmicas son consideradas las más arriesgadas de su categoría?', quiz_options='[{"text":"Porque tienen las comisiones más altas","correct":false},{"text":"Porque su estabilidad depende de algoritmos e incentivos que pueden colapsar si pierden la confianza","correct":true},{"text":"Porque no están disponibles en todos los exchanges","correct":false},{"text":"Porque el gobierno las regula más estrictamente","correct":false}]'::jsonb WHERE id=203;

UPDATE submissions SET content='Los NFTs (tokens no fungibles) son activos digitales únicos en blockchain que certifican la propiedad de un ítem digital. Pueden representar arte, música, juegos, credenciales o contratos.', tips='["El NFT certifica propiedad en la blockchain, no los derechos de copyright del contenido","La mayoría de NFTs de arte especulativo de 2021-22 han perdido >95% de su valor","Los NFTs tienen utilidad real como tickets, credenciales, gaming assets y contratos"]'::jsonb, quiz_question='¿Qué certifica exactamente un NFT de arte digital?', quiz_options='[{"text":"Los derechos de copyright completos sobre la obra","correct":false},{"text":"La propiedad registrada en blockchain de ese token específico, no necesariamente los derechos de reproducción","correct":true},{"text":"La autenticidad física de la obra","correct":false},{"text":"Que el archivo digital no puede copiarse","correct":false}]'::jsonb WHERE id=204;

UPDATE submissions SET content='Una hot wallet está conectada a internet (MetaMask, app móvil); es conveniente pero vulnerable a ataques. Una cold wallet (Ledger, Trezor) está offline; es más segura para guardar grandes cantidades.', tips='["Regla básica: en hot wallet solo lo que usas activamente; en cold wallet los ahorros","Una cold wallet no tiene contraseña de «recuperación» con un banco; la seed phrase ES tu única clave","Si pierdes la seed phrase, pierdes el acceso permanentemente"]'::jsonb, quiz_question='¿Qué cantidad de criptoactivos debería guardarse en una hot wallet?', quiz_options='[{"text":"Todos los activos para mayor comodidad","correct":false},{"text":"Solo los activos que se usan activamente; el resto en cold wallet","correct":true},{"text":"Nunca nada; las hot wallets son inseguras siempre","correct":false},{"text":"Solo stablecoins","correct":false}]'::jsonb WHERE id=205;

UPDATE submissions SET content='La seed phrase (frase semilla) es una secuencia de 12 o 24 palabras que permite recuperar una wallet. Es la llave maestra de todos tus activos en esa wallet. Su seguridad es absoluta e intransferible.', tips='["Guarda la seed phrase en papel físico, nunca en foto, nube o dispositivo electrónico","Haz al menos 2 copias físicas en lugares diferentes y seguros","Ninguna plataforma legítima te pedirá tu seed phrase jamás"]'::jsonb, quiz_question='¿Qué deberías hacer si una plataforma te pide tu seed phrase para «verificar» tu wallet?', quiz_options='[{"text":"Proporcionarla si la plataforma parece oficial","correct":false},{"text":"Nunca proporcionarla; es una estafa segura","correct":true},{"text":"Darles solo las primeras 6 palabras","correct":false},{"text":"Preguntar al soporte técnico si es normal","correct":false}]'::jsonb WHERE id=206;

UPDATE submissions SET content='El gas es el coste de computación en Ethereum por ejecutar una transacción o smart contract. Se paga en ETH (o en la moneda nativa de la red). Las Layer 2 reducen este coste drásticamente.', tips='["El coste de gas varía según la congestión de la red: al hablar de «gas price» y «gas limit»","Revisa el gas price en etherscan.io antes de hacer transacciones grandes","Las horas de menor actividad de la red tienen gas más barato"]'::jsonb, quiz_question='¿Qué determina el precio del gas en una transacción de Ethereum?', quiz_options='[{"text":"El valor del token que estás enviando","correct":false},{"text":"La congestión de la red y la complejidad computacional de la transacción","correct":true},{"text":"Las comisiones fijas establecidas por la fundación Ethereum","correct":false},{"text":"El precio del ETH en ese momento","correct":false}]'::jsonb WHERE id=207;

UPDATE submissions SET content='Los principales riesgos en DeFi son: exploits de smart contracts (hackeos), rugpulls (el equipo abandona y se lleva los fondos), impermanent loss y riesgo de regulación.', tips='["El 70% del valor robado en crypto proviene de exploits de smart contracts","Un protocolo con 1 semana de vida y 500% APY es una red flag de rugpull","Diversificar en múltiples protocolos auditados reduce pero no elimina estos riesgos"]'::jsonb, quiz_question='¿Qué es un «rugpull» en el contexto de DeFi?', quiz_options='[{"text":"Una estrategia de trading bajista","correct":false},{"text":"Cuando el equipo de un proyecto abandona y drena los fondos de los inversores","correct":true},{"text":"Un tipo de exploit técnico de smart contract","correct":false},{"text":"Una corrección de precio del 20% o más","correct":false}]'::jsonb WHERE id=208;

UPDATE submissions SET content='Las Layer 2 (Polygon, Arbitrum, Optimism, zkSync) son redes construidas sobre Ethereum que procesan transacciones más rápido y barato, luego las consolidan en la capa base para seguridad.', tips='["Usar Layer 2 reduce los costes de gas en 10-100x frente a la mainnet de Ethereum","Los fondos en L2 tienen el mismo nivel de seguridad final que en L1 si el bridge es seguro","La mayoría de DeFi activo hoy ocurre en L2, no en mainnet de Ethereum"]'::jsonb, quiz_question='¿Cuál es el beneficio principal de las soluciones Layer 2 para los usuarios de DeFi?', quiz_options='[{"text":"Mayor anonimato en las transacciones","correct":false},{"text":"Transacciones más rápidas y baratas manteniendo la seguridad de Ethereum","correct":true},{"text":"Acceso a más pares de trading que en L1","correct":false},{"text":"Exención de impuestos sobre las ganancias","correct":false}]'::jsonb WHERE id=209;

UPDATE submissions SET content='La regulación de criptomonedas está en evolución en todo el mundo. En España y Europa, el reglamento MiCA (2024) establece el marco regulatorio para criptoactivos, incluyendo emisores y proveedores de servicios.', tips='["MiCA crea un marco legal único para cripto en toda la UE desde 2024","Los exchanges que operan en España/UE deben estar registrados y cumplir KYC/AML","La claridad regulatoria de MiCA es positiva para la adopción institucional a largo plazo"]'::jsonb, quiz_question='¿Qué introduce el reglamento MiCA en Europa respecto a las criptomonedas?', quiz_options='[{"text":"Prohíbe las criptomonedas en toda la UE","correct":false},{"text":"Crea un marco regulatorio uniforme para criptoactivos y proveedores de servicios en toda la UE","correct":true},{"text":"Permite solo Bitcoin y Ethereum","correct":false},{"text":"Establece un impuesto único del 30% sobre todas las ganancias","correct":false}]'::jsonb WHERE id=210;

-- Campaign: Gestión del Riesgo (IDs 211-225)
UPDATE submissions SET content='El ratio riesgo/recompensa (R:R) es la relación entre lo que arriesgas en una operación y lo que esperas ganar. Un R:R de 1:2 significa que arriesgas 1 para ganar 2. Es la base del edge a largo plazo.', tips='["Con un R:R de 1:2 y 40% de aciertos, la estrategia es rentable","Nunca abras una posición con R:R inferior a 1:1,5 mínimo","El R:R se calcula antes de entrar, no durante"]'::jsonb, quiz_question='Si arriesgas 100€ en una operación con R:R de 1:3, ¿cuál es el beneficio potencial?', quiz_options='[{"text":"100€","correct":false},{"text":"200€","correct":false},{"text":"300€","correct":true},{"text":"400€","correct":false}]'::jsonb WHERE id=211;

UPDATE submissions SET content='El sizing de posición define cuánto capital arriesgas en cada operación. La regla del 1-2% indica que nunca deberías arriesgar más del 1-2% de tu capital total en un solo trade.', tips='["Con la regla del 1%: 10 trades perdedores seguidos te quitan solo el 10% del capital","Mayor sizing amplifica tanto ganancias como pérdidas; no compensa el riesgo psicológico","Calcula siempre el sizing ANTES de entrar, basándote en la distancia al stop-loss"]'::jsonb, quiz_question='¿Cuánto capital total deberías arriesgar como máximo en una sola operación según la regla común de gestión de riesgo?', quiz_options='[{"text":"El 10% del capital disponible","correct":false},{"text":"El 5% del capital disponible","correct":false},{"text":"El 1-2% del capital disponible","correct":true},{"text":"El 50% si estás muy seguro de la operación","correct":false}]'::jsonb WHERE id=212;

UPDATE submissions SET content='El stop-loss es una orden que cierra automáticamente una posición cuando el precio alcanza un nivel predefinido de pérdida. Es la herramienta más importante de protección del capital.', tips='["Coloca el stop-loss en un nivel técnicamente significativo, no en un importe redondo","Nunca muevas el stop-loss más lejos para «darle más espacio»; eso elimina su función","El stop-loss no es una predicción; es el precio al que admites que estabas equivocado"]'::jsonb, quiz_question='¿Dónde es más efectivo colocar un stop-loss desde el punto de vista técnico?', quiz_options='[{"text":"En un importe fijo de euros de pérdida","correct":false},{"text":"En un nivel técnico relevante (soporte, swing low) que invalide la tesis de la operación","correct":true},{"text":"Siempre 10 pips por debajo del precio de entrada","correct":false},{"text":"No usar stop-loss para no ser sacado prematuramente","correct":false}]'::jsonb WHERE id=213;

UPDATE submissions SET content='El take profit (TP) es el nivel de precio donde cierras la posición con beneficio. Definirlo antes de entrar evita la codicia que lleva a no cerrar cuando el mercado da lo prometido.', tips='["El TP puede ser parcial: cerrar el 50% en el primer objetivo y el 50% en el segundo","Un trailing stop (stop-loss que sigue el precio) es una alternativa al TP fijo","La resistencia previa es el punto más natural para un TP"]'::jsonb, quiz_question='¿Qué emoción evita principalmente tener un take profit predefinido?', quiz_options='[{"text":"El miedo a perder","correct":false},{"text":"La codicia que lleva a no cerrar cuando el mercado ha dado el beneficio esperado","correct":true},{"text":"La impaciencia al esperar la entrada","correct":false},{"text":"La envidia de otros traders","correct":false}]'::jsonb WHERE id=214;

UPDATE submissions SET content='La diversificación en trading distribuye el capital entre varios activos o estrategias no correlacionados para reducir el impacto de una posición perdedora sobre el portfolio total.', tips='["Diversificar entre activos correlacionados (ej. BTC y ETH) no reduce el riesgo real","Diversificar entre estrategias (tendencia + mean reversion) reduce la correlación del portfolio","La sobrediversificación diluye las buenas ideas y hace imposible el seguimiento"]'::jsonb, quiz_question='¿Por qué diversificar entre BTC y ETH no reduce significativamente el riesgo del portfolio?', quiz_options='[{"text":"Porque ambos tienen el mismo precio","correct":false},{"text":"Porque están altamente correlacionados: cuando uno baja, el otro generalmente también baja","correct":true},{"text":"Porque solo uno de ellos puede subir a la vez","correct":false},{"text":"Por restricciones regulatorias","correct":false}]'::jsonb WHERE id=215;

UPDATE submissions SET content='La correlación entre activos mide si se mueven juntos (+1) o inversamente (-1). Activos con baja correlación entre sí crean carteras más robustas porque los movimientos no se amplifican.', tips='["BTC y el S&P 500 tienen correlación moderada y variable (aumenta en crisis)","Gold y renta variable históricamente tienen correlación negativa (pero no siempre)","La correlación cambia con el tiempo: lo que era poco correlacionado puede no serlo en crisis"]'::jsonb, quiz_question='¿Qué ocurre con las correlaciones entre activos en momentos de crisis severa del mercado?', quiz_options='[{"text":"Las correlaciones tienden a cero porque cada activo actúa de forma independiente","correct":false},{"text":"Las correlaciones tienden a 1: casi todos los activos caen juntos cuando hay pánico","correct":true},{"text":"Solo los activos de renta fija mantienen su correlación","correct":false},{"text":"Las correlaciones se vuelven negativas","correct":false}]'::jsonb WHERE id=216;

UPDATE submissions SET content='El drawdown es la caída desde el punto de máximo beneficio hasta el punto de mínimo antes de una recuperación. El drawdown máximo (max DD) es el peor escenario histórico del sistema o portfolio.', tips='["Un drawdown del 50% requiere un +100% para recuperarse: la matemática del drawdown es asimétrica","Conoce tu drawdown máximo tolerado antes de operar; si supera ese nivel, detén el sistema","Los sistemas con drawdown máximo >20-30% son psicológicamente difíciles de mantener"]'::jsonb, quiz_question='Si tu portfolio sufre un drawdown del 50%, ¿qué retorno necesitas para volver al punto de partida?', quiz_options='[{"text":"50%","correct":false},{"text":"75%","correct":false},{"text":"100%","correct":true},{"text":"25%","correct":false}]'::jsonb WHERE id=217;

UPDATE submissions SET content='El criterio de Kelly calcula el porcentaje óptimo del capital a arriesgar por operación basándose en la tasa de aciertos y el ratio R:R. En la práctica se usa el «half Kelly» para mayor seguridad.', tips='["Kelly completo maximiza el crecimiento pero con drawdowns enormes; usa 1/4 o 1/2 Kelly en práctica","La fórmula: f* = (p × b - q) / b donde p=prob acierto, q=prob fallo, b=ratio R","Con datos de calidad real, Kelly da el sizing más fundamentado matemáticamente"]'::jsonb, quiz_question='¿Por qué se recomienda usar «half Kelly» en lugar del Kelly completo en trading?', quiz_options='[{"text":"Porque el Kelly completo está prohibido por los reguladores","correct":false},{"text":"Porque el Kelly completo maximiza el crecimiento pero genera drawdowns psicológicamente insostenibles","correct":true},{"text":"Porque el Kelly completo solo funciona en casinos","correct":false},{"text":"Porque reduce las comisiones del broker","correct":false}]'::jsonb WHERE id=218;

UPDATE submissions SET content='El riesgo emocional es el mayor enemigo del trader: el miedo lleva a cortar beneficios demasiado pronto; la codicia lleva a aguantar pérdidas. Desarrollar ecuanimidad es tan importante como la estrategia.', tips='["Sigue el plan predefinido independientemente de lo que «sientas» durante la operación","Después de 3 pérdidas seguidas, tómate un descanso antes de la siguiente operación","El trading journal ayuda a identificar los patrones emocionales que dañan el rendimiento"]'::jsonb, quiz_question='¿Qué práctica ayuda más a gestionar el riesgo emocional en el trading?', quiz_options='[{"text":"Operar más cantidad para recuperar pérdidas rápido","correct":false},{"text":"Seguir un plan predefinido con reglas claras y llevar un journal para detectar sesgos emocionales","correct":true},{"text":"Ver las posiciones abiertas constantemente","correct":false},{"text":"Operar solo en horas de alto volumen","correct":false}]'::jsonb WHERE id=219;

UPDATE submissions SET content='Un diario de trading registra cada operación: fecha, activo, razonamiento de entrada, resultado y lo que aprendiste. Es la herramienta más infrautilizada y más valiosa para mejorar.', tips='["Registra también los trades que no tomaste y por qué; así detectas el FOMO y el miedo","Revisa el diario semanalmente buscando patrones: ¿en qué condiciones pierdes más? ¿cuándo ganas?","La calidad del razonamiento, no solo el P&L, es lo que más debes registrar"]'::jsonb, quiz_question='¿Qué es lo más valioso que un diario de trading debería registrar además del P&L?', quiz_options='[{"text":"Solo las operaciones ganadoras para inspiración","correct":false},{"text":"El razonamiento y contexto de cada entrada: por qué entraste y qué pasó vs lo esperado","correct":true},{"text":"Los datos de volumen del mercado","correct":false},{"text":"Las noticias del día en que se operó","correct":false}]'::jsonb WHERE id=220;

UPDATE submissions SET content='El overtrading es abrir más posiciones de las que tu sistema y capital pueden gestionar adecuadamente. Aumenta las comisiones, el riesgo y el estrés sin mejorar el rendimiento.', tips='["Menos operaciones de mayor calidad siempre superan a muchas de baja calidad","Si sientes la necesidad compulsiva de operar, no hay setup: es emocional","Define cuántas operaciones máximas tienes abiertas simultáneamente y respétalo"]'::jsonb, quiz_question='¿Cuál de estas señales indica que un trader está overtradingo?', quiz_options='[{"text":"Opera solo en los mejores setups que cumplen todos los criterios del sistema","correct":false},{"text":"Abre posiciones por aburrimiento, FOMO o para «recuperar» pérdidas del día","correct":true},{"text":"Revisa el mercado 3 veces al día","correct":false},{"text":"Tiene más de 5 activos en seguimiento","correct":false}]'::jsonb WHERE id=221;

UPDATE submissions SET content='El apalancamiento multiplica tanto las ganancias como las pérdidas. Con x10 de apalancamiento, una caída del 10% elimina el 100% del capital invertido.', tips='["El apalancamiento es una herramienta para traders avanzados, no para principiantes","Empieza sin apalancamiento o con x2 máximo hasta dominar la gestión de riesgo","El exchange liquida tu posición automáticamente al llegar al punto de liquidación"]'::jsonb, quiz_question='Con un apalancamiento de x10, ¿qué movimiento del precio en tu contra liquida completamente tu posición?', quiz_options='[{"text":"Un movimiento del 50%","correct":false},{"text":"Un movimiento del 20%","correct":false},{"text":"Un movimiento del 10%","correct":true},{"text":"Un movimiento del 100%","correct":false}]'::jsonb WHERE id=222;

UPDATE submissions SET content='Los cisnes negros son eventos extremos, impredecibles y de alto impacto que los modelos de riesgo convencionales no contemplan. En trading, son los crashes repentinos, hackeos masivos o colapsos de protocolo.', tips='["El COVID crash (marzo 2020) y el colapso de Terra/LUNA (mayo 2022) son ejemplos de cisnes negros en trading","Mantener siempre una reserva de capital fuera del mercado protege ante eventos extremos","Los stops y límites de pérdida son la única protección parcial contra cisnes negros"]'::jsonb, quiz_question='¿Cuál es la mejor protección ante un evento de «cisne negro» en un portfolio de trading?', quiz_options='[{"text":"Un análisis técnico muy preciso","correct":false},{"text":"Siempre tener stops activos, mantener una reserva de capital y diversificar entre activos no correlacionados","correct":true},{"text":"Operar solo en mercados altamente regulados","correct":false},{"text":"No es posible protegerse de los cisnes negros de ninguna forma","correct":false}]'::jsonb WHERE id=223;

UPDATE submissions SET content='El hedging es abrir una posición opuesta o en activos correlacionados negativamente para compensar el riesgo de la posición principal. Es una «póliza de seguro» que tiene un coste.', tips='["Hedging con opciones (puts) permite proteger posiciones largas sin cerrarlas","El coste del hedge (prima) es el precio de dormir tranquilo","Hedging complejo requiere comprensión profunda; un stop-loss es el hedge más simple y efectivo"]'::jsonb, quiz_question='¿Qué es el hedging en el contexto de la gestión de riesgo en trading?', quiz_options='[{"text":"Una estrategia para maximizar beneficios en tendencias alcistas","correct":false},{"text":"Abrir posiciones diseñadas para compensar las pérdidas de otras posiciones en caso de movimiento adverso","correct":true},{"text":"Diversificar el portfolio entre 20 activos distintos","correct":false},{"text":"Usar apalancamiento para cubrir pérdidas previas","correct":false}]'::jsonb WHERE id=224;

UPDATE submissions SET content='Un sistema de trading sostenible combina estrategia sólida, gestión de riesgo estricta, psicología estable y mejora continua. Sin los cuatro pilares, cualquier ganancia es temporal.', tips='["La sostenibilidad se mide en años, no en semanas; desconfía de resultados espectaculares a corto","Un sistema que no puedes seguir emocionalmente en las malas rachas no es sostenible para ti","El objetivo final no es el trade perfecto, es el proceso consistente que produce resultados positivos en el tiempo"]'::jsonb, quiz_question='¿Cuál es el indicador más fiable de que un sistema de trading es sostenible a largo plazo?', quiz_options='[{"text":"Haber tenido un mes con +100% de retorno","correct":false},{"text":"Rendimiento positivo consistente durante al menos 12-24 meses con drawdowns dentro de los parámetros esperados","correct":true},{"text":"Que otros traders lo usen","correct":false},{"text":"Que esté basado en inteligencia artificial","correct":false}]'::jsonb WHERE id=225;

COMMIT;
