BEGIN;

-- ============================================================
-- POLO OESTE (Seguridad) — IDs 226-300
-- ============================================================

-- Campaign: Seguros y Protección (IDs 226-240)
UPDATE submissions SET content='Los seguros transfieren el riesgo de eventos económicamente devastadores a una aseguradora a cambio de una prima. Son la base de la protección financiera ante imprevistos graves.', tips='["Asegura lo que no puedes permitirte perder o reconstruir por ti mismo","Un seguro no es inversión; es protección del patrimonio ya construido","El coste del seguro es siempre menor que el riesgo que cubre cuando ocurre lo imprevisto"]'::jsonb, quiz_question='¿Cuál es el principio fundamental que justifica contratar un seguro?', quiz_options='[{"text":"Para obtener rentabilidad sobre la prima pagada","correct":false},{"text":"Para transferir el coste de un riesgo potencialmente devastador a cambio de una prima predecible","correct":true},{"text":"Porque la ley lo exige para todos los tipos","correct":false},{"text":"Para reducir la base imponible del IRPF","correct":false}]'::jsonb WHERE id=226;

UPDATE submissions SET content='El seguro de vida de riesgo paga un capital a los beneficiarios si el asegurado fallece. El de ahorro/inversión combina protección con un componente financiero. Para protección pura, el de riesgo es más eficiente y barato.', tips='["El seguro de vida es necesario si tienes personas dependientes de tus ingresos","El capital asegurado debería cubrir al menos 5-10 años de los gastos del hogar","Los seguros de vida unit-linked o mixtos tienen costes ocultos altos; compara con alternativas de inversión"]'::jsonb, quiz_question='¿Para qué persona es más necesario un seguro de vida?', quiz_options='[{"text":"Para una persona soltera sin dependientes","correct":false},{"text":"Para una persona con hipoteca e hijos dependientes de sus ingresos","correct":true},{"text":"Solo para personas mayores de 50 años","correct":false},{"text":"Para quienes tienen más de 100.000€ en ahorros","correct":false}]'::jsonb WHERE id=227;

UPDATE submissions SET content='El seguro de salud privado complementa la sanidad pública: menor tiempo de espera, más especialistas y habitación individual. No reemplaza la seguridad social, pero puede ser valioso según el perfil.', tips='["Compara el coste anual con el coste de las consultas privadas que realmente usarías","Los seguros colectivos (empresa, colegio profesional) suelen ser más baratos que los individuales","Revisa las exclusiones: preexistencias, períodos de carencia y copagos antes de contratar"]'::jsonb, quiz_question='¿Cuál es la principal ventaja del seguro de salud privado frente a la sanidad pública en España?', quiz_options='[{"text":"Mayor calidad médica garantizada","correct":false},{"text":"Menores tiempos de espera y más acceso a especialistas de forma ágil","correct":true},{"text":"Cubre todas las enfermedades sin exclusiones","correct":false},{"text":"Es obligatorio para trabajadores autónomos","correct":false}]'::jsonb WHERE id=228;

UPDATE submissions SET content='El seguro de hogar cubre daños a la estructura (continente) y al contenido del inmueble. El seguro del propietario y del inquilino son diferentes: el inquilino debe asegurar su contenido y responsabilidad civil.', tips='["Si eres inquilino, el seguro del propietario cubre la estructura, NO tu contenido","La responsabilidad civil del hogar cubre daños que causes a terceros (inundación al vecino)","Revisa el valor real del continente y del contenido; subasegurar tiene consecuencias en el cobro"]'::jsonb, quiz_question='Si eres inquilino en un piso, ¿qué cubre el seguro del propietario del inmueble?', quiz_options='[{"text":"Tus pertenencias personales dentro del piso","correct":false},{"text":"La estructura del edificio, no el contenido del inquilino","correct":true},{"text":"Tu responsabilidad civil frente a terceros","correct":false},{"text":"Todos los daños que causes en el piso","correct":false}]'::jsonb WHERE id=229;

UPDATE submissions SET content='El seguro de coche es obligatorio en España (responsabilidad civil). Los niveles son: RC básica, a terceros ampliado, a todo riesgo (con o sin franquicia). La elección depende del valor del vehículo.', tips='["Para coches viejos (valor <3.000-4.000€), a terceros ampliado suele ser más eficiente que todo riesgo","La franquicia reduce la prima mensual; considera si podrías asumir esa cantidad en caso de siniestro","Compara al menos 3-4 aseguradoras anualmente; la lealtad en seguros no suele ser recompensada"]'::jsonb, quiz_question='¿Para qué tipo de vehículo tiene más sentido económico contratar un seguro a todo riesgo?', quiz_options='[{"text":"Para coches muy viejos de poco valor","correct":false},{"text":"Para coches de alto valor donde el coste de reparación o sustitución sería elevado","correct":true},{"text":"Para motos de pequeña cilindrada","correct":false},{"text":"El todo riesgo siempre es mejor independientemente del vehículo","correct":false}]'::jsonb WHERE id=230;

UPDATE submissions SET content='El seguro de incapacidad temporal (IT) o invalidez permanente cubre la pérdida de ingresos si no puedes trabajar por enfermedad o accidente. Es uno de los más infracontratados y de los más necesarios.', tips='["La prestación pública de IT es ~60-75% del salario; la diferencia puede ser difícil de asumir","Los autónomos tienen cobertura de IT más limitada que los asalariados","El período de carencia (cuántos días esperar antes del cobro) es clave en la comparación de productos"]'::jsonb, quiz_question='¿Por qué el seguro de incapacidad temporal es especialmente importante para trabajadores autónomos?', quiz_options='[{"text":"Porque los autónomos ganan más y necesitan mayor cobertura","correct":false},{"text":"Porque la protección pública de los autónomos en IT es más limitada que la de los asalariados","correct":true},{"text":"Porque es obligatorio para autónomos por ley","correct":false},{"text":"Porque los autónomos tienen más accidentes","correct":false}]'::jsonb WHERE id=231;

UPDATE submissions SET content='El seguro de protección de ingresos (PPI) o de desempleo cubre las cuotas de préstamos o gastos fijos si pierdes el trabajo o sufres incapacidad. Suele ofrecerse vinculado a hipotecas o préstamos.', tips='["Lee las exclusiones cuidadosamente: muchos PPI no cubren despidos voluntarios o contratos temporales","El coste del PPI vinculado a hipotecas puede ser muy alto; compara con alternativas","Un fondo de emergencia sólido puede hacer innecesario el PPI en muchos casos"]'::jsonb, quiz_question='¿Cuál es la alternativa más común al seguro de protección de ingresos (PPI) para cubrir el riesgo de desempleo?', quiz_options='[{"text":"Tener varias tarjetas de crédito","correct":false},{"text":"Un fondo de emergencia equivalente a 3-6 meses de gastos esenciales","correct":true},{"text":"Otro préstamo personal de reserva","correct":false},{"text":"Invertir en bolsa agresivamente","correct":false}]'::jsonb WHERE id=232;

UPDATE submissions SET content='El seguro de responsabilidad civil profesional (RC Profesional) cubre los daños económicos que puedas causar a clientes por errores u omisiones en tu trabajo. Obligatorio en algunas profesiones, muy recomendable en muchas más.', tips='["Freelancers, consultores, médicos, abogados, arquitectos: la RC profesional es básica","Un error profesional sin cobertura puede derivar en una demanda que arruine tu patrimonio","Compara el límite de cobertura con el tamaño de los proyectos que gestionas"]'::jsonb, quiz_question='¿Qué cubre el seguro de responsabilidad civil profesional?', quiz_options='[{"text":"Los daños físicos que sufras en el trabajo","correct":false},{"text":"Los perjuicios económicos que causes a clientes por errores u omisiones profesionales","correct":true},{"text":"Los accidentes de tráfico en desplazamientos de trabajo","correct":false},{"text":"Los equipos informáticos que uses en tu trabajo","correct":false}]'::jsonb WHERE id=233;

UPDATE submissions SET content='La letra pequeña de una póliza define las exclusiones (qué no cubre), los períodos de carencia (cuándo empieza la cobertura) y las franquicias (parte que asumes tú). Ignorarla lleva a sorpresas desagradables.', tips='["Lee siempre el condicionado general y particular antes de firmar","Pregunta explícitamente por las principales exclusiones del producto","Una cobertura barata con muchas exclusiones puede ser peor que una cara sin ellas"]'::jsonb, quiz_question='¿Qué es un «período de carencia» en un seguro?', quiz_options='[{"text":"El tiempo máximo que la aseguradora puede tardar en pagar","correct":false},{"text":"El período inicial tras contratar el seguro durante el cual algunos riesgos no están cubiertos","correct":true},{"text":"El tiempo de vigencia máximo de la póliza","correct":false},{"text":"El plazo para presentar una reclamación","correct":false}]'::jsonb WHERE id=234;

UPDATE submissions SET content='Estar subasegurado (capital asegurado inferior al valor real del bien) activa la «regla proporcional»: la aseguradora paga solo en la proporción que el capital asegurado representa sobre el valor real.', tips='["Actualiza el valor asegurado cada año, especialmente con la inflación","Si tu casa vale 200.000€ pero la tienes asegurada en 100.000€, cobrarás solo el 50% de cualquier siniestro","El sobreaseguro también existe: no cobrarás más que el valor real del bien"]'::jsonb, quiz_question='Si tienes un coche valorado en 20.000€ pero asegurado en 10.000€ (subasegurado), ¿cuánto cobrarás por un siniestro total?', quiz_options='[{"text":"20.000€ (el valor real del coche)","correct":false},{"text":"10.000€ (el capital asegurado)","correct":true},{"text":"15.000€ (la media entre ambos)","correct":false},{"text":"Nada, el subaseguro anula la póliza","correct":false}]'::jsonb WHERE id=235;

UPDATE submissions SET content='Los seguros son una partida del plan financiero, no un gasto opcional. El orden lógico es: vida (si tienes dependientes), salud, hogar, auto, RC profesional, incapacidad.', tips='["El error es pagar seguros innecesarios antes de tener los esenciales","Revisa toda la cartera de seguros anualmente y elimina duplicidades","El presupuesto de seguros debería ser el 5-10% de los ingresos brutos como referencia orientativa"]'::jsonb, quiz_question='¿Cuál es el primer seguro que debería contratar una persona con hijos dependientes y una hipoteca?', quiz_options='[{"text":"Seguro de coche","correct":false},{"text":"Seguro de vida que cubra la hipoteca y los años de dependencia de los hijos","correct":true},{"text":"Seguro dental","correct":false},{"text":"Seguro de viaje anual","correct":false}]'::jsonb WHERE id=236;

UPDATE submissions SET content='Comparar seguros anualmente puede reducir el coste un 20-40% sin perder cobertura. Los comparadores online (Acierto, Rastreator, Tuseguro) facilitan el proceso.', tips='["Usa la comparación anual como negociación con tu aseguradora actual: a veces igualan el precio","Los descuentos de fidelidad raramente compensan los aumentos de prima anuales","Compara coberturas específicas, no solo el precio final"]'::jsonb, quiz_question='¿Con qué frecuencia deberías comparar las condiciones de tus seguros en el mercado?', quiz_options='[{"text":"Solo cuando tengas un siniestro","correct":false},{"text":"Al menos una vez al año, antes de la renovación automática","correct":true},{"text":"Cada 5 años es suficiente","correct":false},{"text":"Nunca si estás satisfecho con la cobertura","correct":false}]'::jsonb WHERE id=237;

UPDATE submissions SET content='Los beneficiarios de un seguro de vida son las personas designadas para cobrar el capital en caso de fallecimiento del asegurado. Deben estar actualizados y correctamente designados en la póliza.', tips='["Actualiza los beneficiarios al casarte, divorciarte, tener hijos o fallecer un beneficiario","Si no designas beneficiarios, el capital pasa a los herederos legales (proceso más largo)","Los beneficiarios de seguros de vida no forman parte de la herencia ni tributan como tal"]'::jsonb, quiz_question='¿Qué ocurre con el capital del seguro de vida si no se designan beneficiarios en la póliza?', quiz_options='[{"text":"El dinero pasa automáticamente al cónyuge siempre","correct":false},{"text":"El capital pasa a los herederos legales según las normas de sucesión, con un proceso más largo","correct":true},{"text":"La aseguradora se queda el capital","correct":false},{"text":"Se devuelven las primas pagadas","correct":false}]'::jsonb WHERE id=238;

UPDATE submissions SET content='El proceso de reclamación de un siniestro requiere: notificar a la aseguradora en plazo, documentar todos los daños y conservar pruebas. La gestión deficiente del proceso puede resultar en cobros parciales.', tips='["Notifica el siniestro en las primeras 24-48h siempre que sea posible","Fotografía todos los daños antes de repararlos","Si el perito de la aseguradora infravalora el siniestro, puedes solicitar un segundo perito independiente"]'::jsonb, quiz_question='¿Cuál es el error más común al gestionar un siniestro con la aseguradora?', quiz_options='[{"text":"Notificarlo demasiado rápido","correct":false},{"text":"Reparar o tirar los objetos dañados antes de documentar y notificar el siniestro","correct":true},{"text":"Pedir un segundo perito","correct":false},{"text":"Contactar directamente con la compañía en lugar del mediador","correct":false}]'::jsonb WHERE id=239;

UPDATE submissions SET content='El autoseguro consiste en asumir ciertos riesgos por cuenta propia con reservas específicas, en lugar de trasladarlos a una aseguradora. Es viable para riesgos pequeños y frecuentes con un fondo de reserva suficiente.', tips='["Un fondo de emergencia sólido es una forma de autoseguro para riesgos cotidianos","El autoseguro no tiene sentido para riesgos catastróficos (fallecimiento, gran invalidez)","Si el coste del siniestro no te arruinaría, evalúa si la prima del seguro vale la pena"]'::jsonb, quiz_question='¿Para qué tipo de riesgo tiene más sentido el concepto de «autoseguro»?', quiz_options='[{"text":"Para el riesgo de fallecimiento prematuro","correct":false},{"text":"Para riesgos de impacto económico manejable que podrías cubrir con tus propias reservas","correct":true},{"text":"Para la pérdida total de la vivienda","correct":false},{"text":"Para la invalidez permanente","correct":false}]'::jsonb WHERE id=240;

-- Campaign: Planificación Patrimonial (IDs 241-255)
UPDATE submissions SET content='La planificación patrimonial es el proceso de construir, proteger y transferir el patrimonio de forma organizada y eficiente a lo largo de la vida. Va más allá de invertir: incluye seguros, fiscalidad y sucesión.', tips='["El patrimonio es el conjunto de activos menos los pasivos (deudas)","Empezar a planificar el patrimonio no requiere ser rico; es para cualquier nivel de riqueza","La planificación patrimonial previene conflictos familiares y minimiza el impacto fiscal"]'::jsonb, quiz_question='¿Qué es el patrimonio neto de una persona?', quiz_options='[{"text":"El total de todos los ingresos anuales","correct":false},{"text":"La suma de todos los activos (bienes y derechos) menos todos los pasivos (deudas)","correct":true},{"text":"El valor del piso y los ahorros únicamente","correct":false},{"text":"Los ingresos del último año fiscal","correct":false}]'::jsonb WHERE id=241;

UPDATE submissions SET content='El patrimonio neto se calcula restando las deudas de los activos. Calcularlo cada año revela si realmente estás construyendo riqueza neta o simplemente moviéndola.', tips='["Activos: vivienda, coche, cuentas, inversiones, plan de pensiones, joyas, negocios","Pasivos: hipoteca, préstamos, deudas de tarjetas, cualquier obligación financiera","Un patrimonio neto creciente es el indicador más honesto del progreso financiero"]'::jsonb, quiz_question='Si tienes 200.000€ en activos (piso 150.000, ahorros 30.000, coche 20.000) y 80.000€ de hipoteca pendiente, ¿cuál es tu patrimonio neto?', quiz_options='[{"text":"200.000€","correct":false},{"text":"150.000€","correct":false},{"text":"120.000€","correct":true},{"text":"80.000€","correct":false}]'::jsonb WHERE id=242;

UPDATE submissions SET content='La asignación de activos (asset allocation) distribuye el patrimonio entre diferentes clases (renta variable, renta fija, inmuebles, liquidez, alternativos) para equilibrar riesgo y retorno según el perfil y horizonte.', tips='["La regla clásica «100 menos tu edad = % en renta variable» es un punto de partida, no una ley","Cuanto mayor sea tu horizonte temporal, más renta variable puedes tolerar","Revisa la asignación al menos una vez al año y cuando cambien tus circunstancias"]'::jsonb, quiz_question='¿Qué factor influye más en la asignación adecuada de activos entre renta variable y fija?', quiz_options='[{"text":"El volumen total del patrimonio","correct":false},{"text":"El horizonte temporal y la tolerancia al riesgo del inversor","correct":true},{"text":"El nivel actual de los tipos de interés","correct":false},{"text":"El país de residencia fiscal","correct":false}]'::jsonb WHERE id=243;

UPDATE submissions SET content='Los inmuebles pueden ser un activo de patrimonio sólido (revalorización + renta) o una trampa (iliquidez, costes ocultos, vacancia). Su peso en el patrimonio debe estar justificado y equilibrado.', tips='["El inmueble en propiedad es también un pasivo: hipoteca, IBI, comunidad, mantenimiento","Diversificar entre inmuebles y activos financieros reduce la concentración de riesgo","Los REITs permiten exposición inmobiliaria con liquidez sin comprar una propiedad"]'::jsonb, quiz_question='¿Cuál es el principal riesgo de tener todo el patrimonio concentrado en bienes inmuebles?', quiz_options='[{"text":"El pago del IBI puede ser muy alto","correct":false},{"text":"La iliquidez: no puedes convertir rápidamente parte del inmueble en efectivo si lo necesitas","correct":true},{"text":"Los inmuebles nunca se revalorizan","correct":false},{"text":"Los seguros del hogar son obligatorios y caros","correct":false}]'::jsonb WHERE id=244;

UPDATE submissions SET content='Ser propietario de un negocio es uno de los activos patrimoniales más potentes, pero también uno de los más concentrados e ilíquidos. Diversificar fuera del negocio es prudente desde el principio.', tips='["No pongas todo tu patrimonio en tu negocio; diversifica en activos financieros independientes","El negocio puede valer cero mañana; los activos externos son tu red de seguridad","Planifica la salida del negocio (venta, sucesión, cierre) desde el primer día"]'::jsonb, quiz_question='¿Por qué un empresario debería invertir parte de su patrimonio fuera de su propio negocio?', quiz_options='[{"text":"Por obligaciones fiscales","correct":false},{"text":"Para diversificar el riesgo: si el negocio fracasa, el patrimonio externo proporciona seguridad","correct":true},{"text":"Porque el negocio no genera rendimientos","correct":false},{"text":"Porque los bancos lo exigen para conceder crédito","correct":false}]'::jsonb WHERE id=245;

UPDATE submissions SET content='Los ingresos pasivos (dividendos, alquileres, regalías, intereses) son los que no requieren tiempo activo una vez construidos. Son la base de la independencia financiera.', tips='["Construir ingresos pasivos requiere tiempo activo al principio; no son instantáneos","Los dividendos de acciones y los alquileres son las formas más comunes de ingreso pasivo","El objetivo: que tus ingresos pasivos superen tus gastos esenciales"]'::jsonb, quiz_question='¿Cuál es la característica definitoria de un ingreso pasivo?', quiz_options='[{"text":"Que sea dinero recibido sin haber trabajado nunca","correct":false},{"text":"Que genere flujo de caja continuo sin requerir tiempo activo proporcional una vez construido","correct":true},{"text":"Que esté exento de impuestos","correct":false},{"text":"Que sea superior al salario laboral","correct":false}]'::jsonb WHERE id=246;

UPDATE submissions SET content='La fiscalidad eficiente de las inversiones (diferimiento, deducciones, vehículos fiscalmente ventajosos) puede aumentar significativamente el rendimiento neto sin asumir más riesgo.', tips='["Las ganancias no realizadas no tributan: diferir la venta reduce la carga fiscal","Los planes de pensiones permiten diferir impuestos hasta la jubilación (deducción en IRPF)","Invertir a través de sociedades puede tener ventajas fiscales para patrimonios grandes"]'::jsonb, quiz_question='¿Por qué diferir la venta de una inversión rentable puede ser fiscalmente ventajoso?', quiz_options='[{"text":"Porque los activos siempre suben con el tiempo","correct":false},{"text":"Porque la ganancia no tributada sigue generando rendimiento hasta que se realice","correct":true},{"text":"Porque hacienda no controla las ganancias antiguas","correct":false},{"text":"No hay ventaja fiscal en diferir la venta","correct":false}]'::jsonb WHERE id=247;

UPDATE submissions SET content='La planificación sucesoria define cómo se transmitirá el patrimonio en caso de fallecimiento: testamento, nombramientos de beneficiarios, donaciones en vida, seguros de vida. Sin planificación, la ley lo decide.', tips='["Sin testamento, la ley distribuye la herencia según el orden legal de herederos","Un testamento notarial es válido aunque sea sencillo; el coste es de 50-150€","La planificación sucesoria no es solo para ricos; cualquiera con bienes o dependientes la necesita"]'::jsonb, quiz_question='¿Qué ocurre si una persona fallece sin testamento en España?', quiz_options='[{"text":"El Estado se queda todos los bienes automáticamente","correct":false},{"text":"La ley establece quiénes heredan según el orden legal de sucesión intestada","correct":true},{"text":"El cónyuge recibe todo sin importar otras circunstancias","correct":false},{"text":"El notario decide quién hereda","correct":false}]'::jsonb WHERE id=248;

UPDATE submissions SET content='El poder notarial permite que otra persona tome decisiones financieras y legales en tu nombre si quedas incapacitado. Es especialmente importante en mayores o al acometer viajes o cirugías de riesgo.', tips='["Hay poderes generales (todo) y especiales (para actos concretos como vender un inmueble)","Designa a una persona de total confianza; el poder notarial es una responsabilidad enorme","La tutela judicial es el proceso alternativo cuando no hay poder notarial previo; es más lento y costoso"]'::jsonb, quiz_question='¿Para qué sirve designar un poder notarial preventivo?', quiz_options='[{"text":"Para evitar pagar impuestos sobre donaciones","correct":false},{"text":"Para que otra persona pueda gestionar tus asuntos legales y financieros si quedas incapacitado","correct":true},{"text":"Para acelerar el proceso de herencia","correct":false},{"text":"Para transferir la propiedad de bienes en vida","correct":false}]'::jsonb WHERE id=249;

UPDATE submissions SET content='Los fideicomisos y fundaciones son estructuras legales que separan la propiedad de los activos de su disfrute y gestión. Permiten proteger patrimonio, planificar la sucesión y gestionar donaciones con eficiencia fiscal.', tips='["En España, las SICAV y algunas sociedades de inversión tienen función similar a los trusts anglosajones","Las fundaciones privadas son útiles para patrimonios muy grandes con objetivos benéficos o familiares","Estas estructuras requieren asesoramiento legal especializado y tienen costes de mantenimiento"]'::jsonb, quiz_question='¿Cuál es la principal ventaja de un fideicomiso o trust para la planificación patrimonial?', quiz_options='[{"text":"Permiten no pagar impuestos de forma ilegal","correct":false},{"text":"Separan la propiedad del disfrute, facilitando la protección y transmisión del patrimonio con planificación","correct":true},{"text":"Solo sirven para patrimonio invertido en bolsa","correct":false},{"text":"Son gratuitos y no requieren mantenimiento","correct":false}]'::jsonb WHERE id=250;

UPDATE submissions SET content='La donación en vida puede ser fiscalmente eficiente en algunos casos, permite ver el uso del dinero y reduce la masa hereditaria. En España, tributa por el Impuesto de Donaciones (variable por comunidad autónoma).', tips='["En algunas CCAA (Madrid, Canarias) las donaciones a hijos tienen bonificaciones muy elevadas","Las donaciones en vida reducen el patrimonio hereditario, pudiendo reducir el impuesto de sucesiones","Consulta siempre con un asesor fiscal antes de donar importes significativos"]'::jsonb, quiz_question='¿Por qué puede ser fiscalmente conveniente donar parte del patrimonio en vida en lugar de heredar?', quiz_options='[{"text":"Las donaciones siempre están exentas de impuestos","correct":false},{"text":"En algunas comunidades autónomas las donaciones a hijos tienen bonificaciones fiscales favorables","correct":true},{"text":"Las donaciones en vida no tributan nunca","correct":false},{"text":"El receptor de la donación paga menos IRPF","correct":false}]'::jsonb WHERE id=251;

UPDATE submissions SET content='Las reuniones familiares de finanzas alinean a los miembros del hogar en objetivos, gastos y planificación. En familias con patrimonio significativo, la educación financiera de los hijos es parte de la preservación del patrimonio.', tips='["Una reunión de finanzas familiar mensual de 30 minutos puede evitar años de conflictos","Los hijos que aprenden a gestionar dinero en casa tienen mejor salud financiera de adultos","La transparencia financiera en pareja es un predictor de solidez de la relación"]'::jsonb, quiz_question='¿Cuál es el beneficio principal de celebrar reuniones familiares regulares sobre las finanzas del hogar?', quiz_options='[{"text":"Es un requisito de la asesoría financiera","correct":false},{"text":"Alinear objetivos, detectar desviaciones y educar a todos los miembros en gestión financiera","correct":true},{"text":"Permite negociar hipotecas con mejores condiciones","correct":false},{"text":"Genera deducciones fiscales por planificación familiar","correct":false}]'::jsonb WHERE id=252;

UPDATE submissions SET content='Un asesor financiero independiente (no vinculado a productos) puede aportar valor cuando el patrimonio es complejo, hay grandes cambios de vida o se necesita planificación fiscal especializada.', tips='["Busca asesores «fee-only» que cobran por el servicio, no por comisión de productos que venden","Un asesor bueno te hace preguntas sobre tus objetivos antes de proponer productos","Compara al menos 2-3 asesores; los honorarios y el enfoque varían mucho"]'::jsonb, quiz_question='¿Qué tipo de asesor financiero tiene menos conflictos de interés en sus recomendaciones?', quiz_options='[{"text":"El que cobra comisión de los productos que vende","correct":false},{"text":"El asesor «fee-only» que cobra honorarios fijos directamente al cliente","correct":true},{"text":"El empleado de una entidad bancaria","correct":false},{"text":"El que trabaja para una aseguradora","correct":false}]'::jsonb WHERE id=253;

UPDATE submissions SET content='Una revisión patrimonial anual actualiza el inventario de activos y pasivos, evalúa la rentabilidad de cada componente y ajusta la asignación según los cambios de vida y mercado.', tips='["Usa un documento o hoja de cálculo simple: activos, valor actual, pasivos, patrimonio neto","Compara con el año anterior: ¿creció el patrimonio neto? ¿cómo y por qué?","La revisión anual detecta activos olvidados (planes de pensiones antiguos, depósitos) y pasivos innecesarios"]'::jsonb, quiz_question='¿Qué debería incluir una revisión patrimonial anual completa?', quiz_options='[{"text":"Solo revisar las cuentas bancarias","correct":false},{"text":"Actualizar el inventario de todos los activos y pasivos, evaluar rendimientos y ajustar la asignación","correct":true},{"text":"Solo calcular los impuestos a pagar","correct":false},{"text":"Solo revisar la cartera de inversiones","correct":false}]'::jsonb WHERE id=254;

UPDATE submissions SET content='La riqueza generacional se construye cuando el patrimonio crece más rápido de lo que se consume y se transmite eficientemente a la siguiente generación. Requiere educación financiera, planificación y tiempo.', tips='["El tiempo y el interés compuesto son las herramientas más poderosas para la riqueza generacional","La educación financiera de los hijos es una inversión de alto retorno para el patrimonio familiar","La primera generación construye, la segunda mantiene, la tercera suele consumir: romper el ciclo requiere cultura financiera"]'::jsonb, quiz_question='¿Cuál es el factor más determinante para construir riqueza generacional?', quiz_options='[{"text":"Tener ingresos muy altos","correct":false},{"text":"La combinación de tiempo, interés compuesto y transmisión de educación financiera entre generaciones","correct":true},{"text":"Heredar una empresa familiar","correct":false},{"text":"Invertir exclusivamente en inmuebles","correct":false}]'::jsonb WHERE id=255;

-- Campaign: Fondos de Pensiones (IDs 256-270)
UPDATE submissions SET content='El sistema público de pensiones en España funciona por reparto: los trabajadores actuales pagan las pensiones de los jubilados actuales. Con el envejecimiento poblacional, su sostenibilidad a largo plazo es el mayor debate de política social.', tips='["La ratio trabajadores/pensionistas ha caído de 4:1 a menos de 2:1 en 40 años","La pensión pública será probablemente menor en términos reales para las generaciones jóvenes actuales","No descartes la pensión pública, pero tampoco cuentes con que será suficiente sola"]'::jsonb, quiz_question='¿Cómo funciona el sistema de pensiones público de reparto en España?', quiz_options='[{"text":"Cada trabajador acumula un fondo propio que recibe al jubilarse","correct":false},{"text":"Las cotizaciones de los trabajadores activos financian directamente las pensiones de los jubilados actuales","correct":true},{"text":"El Estado invierte las cotizaciones en bolsa para generar rendimiento","correct":false},{"text":"Las empresas crean fondos individuales para cada empleado","correct":false}]'::jsonb WHERE id=256;

UPDATE submissions SET content='Los planes de pensiones privados son vehículos de ahorro a largo plazo con ventaja fiscal en las aportaciones (deducibles en IRPF) pero con rescate tributando como rendimientos del trabajo.', tips='["Deducción máxima en IRPF: 1.500€/año en planes individuales (límite 2023-25)","El rescate al jubilarse tributa como rendimientos del trabajo, no como capital: puede ser desventajoso","La iliquidez del plan (solo se rescata en jubilación, desempleo o enfermedad grave) es una limitación importante"]'::jsonb, quiz_question='¿Cuál es la principal ventaja fiscal de un plan de pensiones en España?', quiz_options='[{"text":"Las ganancias generadas dentro del plan están exentas de impuestos siempre","correct":false},{"text":"Las aportaciones anuales son deducibles en la base imponible del IRPF hasta ciertos límites","correct":true},{"text":"El rescate en jubilación está exento de impuestos","correct":false},{"text":"No pagan comisiones de gestión","correct":false}]'::jsonb WHERE id=257;

UPDATE submissions SET content='Las aportaciones a planes de pensiones reducen la base imponible del IRPF, generando un ahorro fiscal inmediato. La rentabilidad del plan debe superar la inflación y las comisiones para crear valor real.', tips='["El ahorro fiscal inmediato puede reinvertirse: es la verdadera palanca del plan de pensiones","Con marginal del 40%, aportar 1.000€ al plan «te cuesta» realmente 600€ (ahorro fiscal de 400€)","Compara las comisiones de gestión: diferencias del 1% en comisión pueden costar décadas de rentabilidad"]'::jsonb, quiz_question='Si estás en el tramo del 37% del IRPF y aportas 1.000€ a un plan de pensiones, ¿cuánto te devuelve Hacienda aproximadamente?', quiz_options='[{"text":"100€","correct":false},{"text":"200€","correct":false},{"text":"370€","correct":true},{"text":"500€","correct":false}]'::jsonb WHERE id=258;

UPDATE submissions SET content='El interés compuesto hace que el dinero invertido genere rendimientos que a su vez generan más rendimientos. A largo plazo, el efecto es exponencial. Empezar pronto es la variable más poderosa.', tips='["100€/mes durante 30 años al 7% = ~121.000€. Los últimos 10 años generan más que los primeros 20","El interés compuesto requiere no tocar el capital: los rescates parciales destruyen el efecto","Visualiza el crecimiento con una calculadora de interés compuesto para motivarte"]'::jsonb, quiz_question='¿Por qué el interés compuesto es exponencial y no lineal?', quiz_options='[{"text":"Porque los tipos de interés siempre suben","correct":false},{"text":"Porque los rendimientos se suman al capital y generan rendimientos adicionales sobre ellos mismos","correct":true},{"text":"Por regulación de los bancos centrales","correct":false},{"text":"Porque las comisiones bajan con el tiempo","correct":false}]'::jsonb WHERE id=259;

UPDATE submissions SET content='Empezar a los 30 con 100€/mes al 7% genera más capital a los 65 que empezar a los 45 con 300€/mes. El tiempo importa más que la cantidad aportada.', tips='["Cada año que retrases el inicio de tu plan de pensiones tiene un coste enorme al final","Aunque sea poco, empezar hoy supera siempre a esperar a poder aportar más","La procrastinación en el ahorro para la jubilación es el error financiero más costoso a largo plazo"]'::jsonb, quiz_question='¿Qué factor tiene más impacto en el resultado final de un plan de pensiones a largo plazo?', quiz_options='[{"text":"El importe aportado mensualmente","correct":false},{"text":"El tiempo durante el cual se mantiene la aportación gracias al interés compuesto","correct":true},{"text":"El tipo de activos elegidos","correct":false},{"text":"El nivel salarial del titular","correct":false}]'::jsonb WHERE id=260;

UPDATE submissions SET content='Los fondos de pensiones pueden invertir en renta variable (más riesgo, más potencial), renta fija (más estable, menos retorno) o mixtos. El perfil de riesgo debe ajustarse al horizonte temporal: más agresivo en joven, más conservador al acercarse la jubilación.', tips='["A 30+ años de jubilación: renta variable pura o agresiva","A 10 años de jubilación: empieza a rotar hacia renta fija","A 5 años de jubilación: perfil conservador o muy conservador para proteger lo acumulado"]'::jsonb, quiz_question='¿Qué perfil de inversión es más adecuado para un plan de pensiones cuando faltan más de 25 años para la jubilación?', quiz_options='[{"text":"Perfil conservador con predominio de renta fija","correct":false},{"text":"100% en depósitos bancarios garantizados","correct":false},{"text":"Perfil dinámico con alto peso en renta variable global","correct":true},{"text":"Fondo monetario para no correr riesgos","correct":false}]'::jsonb WHERE id=261;

UPDATE submissions SET content='Las comisiones de gestión y depósito del plan de pensiones se descuentan del rendimiento anual. Una diferencia del 1% en comisiones puede suponer hasta el 20% menos de capital acumulado en 30 años.', tips='["Los planes de pensiones indexados tienen comisiones mucho más bajas (0,1-0,3%) que los activos (1-2%)","Compara siempre la TER (Total Expense Ratio) al elegir un plan","El Ministerio de Economía obliga a publicar todas las comisiones de forma clara"]'::jsonb, quiz_question='¿Qué impacto tienen las comisiones anuales del 1% vs 0,2% en un plan de pensiones a 30 años?', quiz_options='[{"text":"Diferencia mínima, menos del 5% del capital final","correct":false},{"text":"Una diferencia significativa, potencialmente 15-20% menos de capital acumulado con la comisión mayor","correct":true},{"text":"Las comisiones se compensan con mejores resultados del gestor activo","correct":false},{"text":"Las comisiones no afectan al rendimiento final","correct":false}]'::jsonb WHERE id=262;

UPDATE submissions SET content='En España, las aportaciones a planes de pensiones reducen la base imponible del IRPF hasta 1.500€/año. Las aportaciones al plan de empleo del cónyuge tienen límite adicional de 1.000€.', tips='["El límite de 1.500€ aplica al total de planes individuales y de empleo del trabajador","Las aportaciones a PPA (planes de previsión asegurados) también computan en el límite","Los mayores beneficiados son los de tramos altos de IRPF (37-47%)"]'::jsonb, quiz_question='¿Cuál es el límite máximo de deducción fiscal en IRPF para un plan de pensiones individual en España (2024)?', quiz_options='[{"text":"3.000€/año","correct":false},{"text":"1.500€/año","correct":true},{"text":"8.000€/año","correct":false},{"text":"Sin límite si no supera el 30% de los rendimientos","correct":false}]'::jsonb WHERE id=263;

UPDATE submissions SET content='El plan de empresa (plan de pensiones de empleo) es aportado total o parcialmente por el empleador. Es una ventaja salarial en especie fiscalmente eficiente para ambas partes.', tips='["Si tu empresa ofrece plan de empresa con «matching», aprovéchalo siempre: es dinero gratis","Las aportaciones del empleador al plan de empleo tienen límites fiscales propios (hasta 8.500€/año del empleador)","Cambiando de empresa, el plan de pensiones de empleo puede traspasarse"]'::jsonb, quiz_question='¿Por qué se considera el plan de pensiones de empresa con «matching» una ventaja especialmente valiosa?', quiz_options='[{"text":"Porque tiene mejores rendimientos que los planes individuales","correct":false},{"text":"Porque la empresa aporta dinero adicional para tu jubilación que de otro modo no recibirías","correct":true},{"text":"Porque está exento de cotizaciones sociales siempre","correct":false},{"text":"Porque no tributa en el rescate","correct":false}]'::jsonb WHERE id=264;

UPDATE submissions SET content='Los planes de pensiones son portables: puedes traspasarlos entre entidades y entre planes sin tributar por el traspaso. Esto permite buscar mejores condiciones de rentabilidad y comisiones sin penalización fiscal.', tips='["El traspaso entre planes no tributa; solo tributa el rescate final","Aprovecha la portabilidad para buscar planes con menores comisiones o mejor gestión","Al traspasar, verifica que el nuevo plan tiene un perfil de riesgo adecuado a tu horizonte"]'::jsonb, quiz_question='¿Qué ocurre fiscalmente cuando traspasas un plan de pensiones de una entidad a otra?', quiz_options='[{"text":"Tributas por las ganancias acumuladas en ese momento","correct":false},{"text":"El traspaso no genera tributación; solo tributa el rescate final","correct":true},{"text":"Pagas una penalización del 10% del capital","correct":false},{"text":"Debes declararlo en el IRPF como ingreso","correct":false}]'::jsonb WHERE id=265;

UPDATE submissions SET content='La jubilación anticipada (FIRE: Financial Independence, Retire Early) requiere un patrimonio de aproximadamente 25 veces los gastos anuales y una tasa de retirada segura del 4%. Es ambicioso pero alcanzable con disciplina.', tips='["Con gastos de 20.000€/año necesitas ~500.000€ de patrimonio (regla del 4%)","La tasa del 4% asume un portfolio mixto (60% RV / 40% RF) con rebalanceo anual","Cuanto antes te jubiles, más años de retiro debes financiar; considera tasa del 3% para 40+ años de retiro"]'::jsonb, quiz_question='Según la regla del 4%, ¿cuánto patrimonio necesitas para cubrir gastos anuales de 25.000€?', quiz_options='[{"text":"250.000€","correct":false},{"text":"500.000€","correct":false},{"text":"625.000€","correct":true},{"text":"1.000.000€","correct":false}]'::jsonb WHERE id=266;

UPDATE submissions SET content='Los planes de pensiones tienen desventajas respecto a fondos de inversión: menor liquidez (solo se rescatan en casos específicos), el rescate tributa como rendimientos del trabajo (tipo marginal), y hay límites de aportación.', tips='["Para patrimonios grandes, los fondos de inversión indexados pueden ser más eficientes que los planes","El plan de pensiones es más atractivo cuanto mayor sea tu tipo marginal del IRPF","Un plan de pensiones con baja comisión + fondo indexado fuera del plan es la combinación óptima para muchos"]'::jsonb, quiz_question='¿En qué aspecto fiscal están los fondos de inversión en ventaja sobre los planes de pensiones?', quiz_options='[{"text":"Los fondos de inversión tienen mejores rentabilidades","correct":false},{"text":"El rescate de fondos tributa como ganancia patrimonial (15-23%), mientras el plan tributa como rendimientos del trabajo (tipo marginal, potencialmente más alto)","correct":true},{"text":"Los fondos de inversión no tributan en vida","correct":false},{"text":"Los fondos no tienen comisiones de gestión","correct":false}]'::jsonb WHERE id=267;

UPDATE submissions SET content='Revisar el rendimiento del plan de pensiones anualmente permite comparar con benchmarks del mercado y detectar si la gestión activa justifica su mayor coste frente a alternativas indexadas.', tips='["Compara tu plan con el índice que replica (MSCI World, Ibex) para ver si el gestor añade valor","Cambia de plan si consistentemente rinde por debajo del benchmark tras comisiones","El rendimiento de un año no es suficiente; evalúa mínimo 3-5 años"]'::jsonb, quiz_question='¿Contra qué deberías comparar el rendimiento de tu plan de pensiones para evaluar si es bueno?', quiz_options='[{"text":"Contra el interés de los depósitos bancarios","correct":false},{"text":"Contra el índice de mercado que el plan pretende replicar o batir, después de comisiones","correct":true},{"text":"Contra la inflación únicamente","correct":false},{"text":"Contra otros planes del mismo banco","correct":false}]'::jsonb WHERE id=268;

UPDATE submissions SET content='La inflación erosiona el poder adquisitivo del ahorro. Un plan de pensiones invertido en activos reales (renta variable) protege mejor de la inflación que uno en renta fija o depósitos.', tips='["Con inflación del 3% anual, el poder adquisitivo se reduce a la mitad en 24 años","La renta variable históricamente ha rentado por encima de la inflación a largo plazo","Tener parte del plan en commodities o inmuebles (REITs) también protege de inflación"]'::jsonb, quiz_question='¿Qué tipo de activos protege mejor el ahorro en un plan de pensiones frente a la inflación a largo plazo?', quiz_options='[{"text":"Renta fija gubernamental a largo plazo","correct":false},{"text":"Renta variable diversificada global","correct":true},{"text":"Depósitos bancarios garantizados","correct":false},{"text":"Fondo monetario en euros","correct":false}]'::jsonb WHERE id=269;

UPDATE submissions SET content='La tasa de retirada segura (SWR, Safe Withdrawal Rate) es el porcentaje del patrimonio que puedes retirar anualmente sin riesgo de agotar el capital. El estudio Trinity establece el 4% como referencia para horizontes de 30 años.', tips='["Para retiros de 40+ años, algunos expertos recomiendan 3-3,5% por mayor horizonte temporal","La SWR asume un portfolio bien diversificado y rebalanceo anual","En años de mercado bajista, retirar un importe fijo es mejor que un porcentaje fijo del portfolio"]'::jsonb, quiz_question='¿Qué significa una tasa de retirada segura del 4%?', quiz_options='[{"text":"Tu portfolio subirá un 4% anual garantizado","correct":false},{"text":"Puedes retirar el 4% del patrimonio inicial cada año y estadísticamente no agotarás el capital en 30 años","correct":true},{"text":"Solo puedes gastar el 4% de tus ingresos en ocio","correct":false},{"text":"Necesitas reservar el 4% para impuestos en la jubilación","correct":false}]'::jsonb WHERE id=270;

-- Campaign: Diversificación Defensiva (IDs 271-285)
UPDATE submissions SET content='La diversificación reduce el riesgo distribuyendo el capital entre activos que no se mueven siempre en la misma dirección. «No pongas todos los huevos en la misma cesta» tiene base matemática sólida.', tips='["La diversificación es la única «comida gratis» en finanzas: reduce riesgo sin reducir retorno esperado","Solo protege de riesgo no sistemático (riesgo de empresa); el riesgo de mercado afecta a todos","La diversificación tiene rendimientos decrecientes: 20-30 activos dan casi el mismo beneficio que 100"]'::jsonb, quiz_question='¿Contra qué tipo de riesgo protege principalmente la diversificación?', quiz_options='[{"text":"Contra el riesgo de caída general del mercado","correct":false},{"text":"Contra el riesgo específico de una empresa o sector que afecte solo a esa inversión","correct":true},{"text":"Contra la inflación","correct":false},{"text":"Contra los tipos de interés","correct":false}]'::jsonb WHERE id=271;

UPDATE submissions SET content='Las principales clases de activos son: renta variable (acciones), renta fija (bonos), inmuebles (REITs), materias primas (oro, petróleo), divisas y activos alternativos. Cada uno tiene un perfil de riesgo-retorno diferente.', tips='["La renta variable tiene el mayor retorno histórico a largo plazo pero con mayor volatilidad","Los bonos reducen la volatilidad pero también el retorno esperado a largo plazo","Tener múltiples clases de activos reduce la correlación del portfolio global"]'::jsonb, quiz_question='¿Cuál de estas combinaciones ofrece mayor diversificación real entre clases de activos?', quiz_options='[{"text":"50% en Apple y 50% en Microsoft","correct":false},{"text":"25% acciones, 25% bonos, 25% REITs y 25% oro","correct":true},{"text":"100% en el índice S&P 500","correct":false},{"text":"10 empresas del sector tecnológico estadounidense","correct":false}]'::jsonb WHERE id=272;

UPDATE submissions SET content='La diversificación geográfica distribuye inversiones entre diferentes países y regiones para reducir el riesgo-país (crisis específica de una economía). Un portfolio solo en España o EE.UU. tiene alta concentración geográfica.', tips='["Un índice global (MSCI World) da exposición a 1.500+ empresas de 23 países desarrollados","Los mercados emergentes (China, India, Brasil) añaden diversificación y mayor potencial pero más riesgo","Invertir «solo en lo que conozco» (home bias) es un sesgo que reduce la diversificación"]'::jsonb, quiz_question='¿Qué riesgo específico reduce la diversificación geográfica?', quiz_options='[{"text":"La inflación global","correct":false},{"text":"El riesgo-país: que una crisis económica o política afecte a toda una economía nacional","correct":true},{"text":"El riesgo de tipo de cambio siempre","correct":false},{"text":"El riesgo de empresa individual","correct":false}]'::jsonb WHERE id=273;

UPDATE submissions SET content='La diversificación sectorial distribuye las inversiones entre diferentes sectores económicos (tecnología, sanidad, consumo, energía, finanzas). Evita la sobre-exposición a un sector que puede caer en conjunto.', tips='["Si el 80% de tu portfolio es tecnología, una caída del sector (como 2022) te afecta masivamente","Los índices amplios ya incluyen diversificación sectorial automática","Sectores defensivos (consumo básico, utilities, sanidad) caen menos en crisis que los cíclicos"]'::jsonb, quiz_question='¿Qué sectores se consideran «defensivos» en términos de resistencia a las crisis económicas?', quiz_options='[{"text":"Tecnología y criptomonedas","correct":false},{"text":"Consumo básico (alimentación), utilities (electricidad/agua) y sanidad","correct":true},{"text":"Energía y materias primas","correct":false},{"text":"Bancario y constructor","correct":false}]'::jsonb WHERE id=274;

UPDATE submissions SET content='Los bonos (renta fija) prestan dinero a gobiernos o empresas a cambio de un tipo de interés periódico y la devolución del principal al vencimiento. Son menos volátiles que las acciones pero con menor retorno esperado.', tips='["Los bonos gubernamentales de países seguros (Alemania, EE.UU.) son los menos arriesgados","Los bonos corporativos de alta calidad (investment grade) pagan más que los gubernamentales","Los bonos de alto rendimiento (high yield o «junk bonds») pagan más pero con riesgo de impago elevado"]'::jsonb, quiz_question='¿Cuál es la relación general entre el tipo de interés de un bono y su riesgo de impago?', quiz_options='[{"text":"A mayor tipo de interés, menor riesgo","correct":false},{"text":"A mayor tipo de interés, mayor riesgo percibido de impago del emisor","correct":true},{"text":"No hay relación entre tipo de interés y riesgo","correct":false},{"text":"Solo los bonos gubernamentales pagan intereses","correct":false}]'::jsonb WHERE id=275;

UPDATE submissions SET content='El oro es considerado un activo refugio que tiende a mantener su valor en periodos de crisis, inflación alta o inestabilidad geopolítica. No genera flujo de caja pero actúa como seguro del portfolio.', tips='["El oro no paga dividendos ni intereses; su valor es la percepción de reserva de valor","Una asignación del 5-10% en oro reduce la volatilidad del portfolio en crisis","Los ETFs de oro son la forma más eficiente de invertir en él sin custodia física"]'::jsonb, quiz_question='¿Por qué el oro se considera un activo «refugio» en momentos de crisis?', quiz_options='[{"text":"Porque siempre sube durante las recesiones económicas","correct":false},{"text":"Porque históricamente mantiene su valor y actúa inversamente a activos de riesgo en momentos de pánico","correct":true},{"text":"Porque está respaldado por todos los bancos centrales","correct":false},{"text":"Porque su precio lo fija el gobierno","correct":false}]'::jsonb WHERE id=276;

UPDATE submissions SET content='Los REITs (Real Estate Investment Trusts) son fondos que invierten en inmuebles y cotizan en bolsa como acciones. Permiten exposición inmobiliaria con liquidez diaria y diversificación entre muchos inmuebles.', tips='["Los REITs están obligados por ley a distribuir al menos el 90% de sus beneficios como dividendo","Son una forma de invertir en inmobiliario sin el capital y la gestión de comprar una propiedad","Los REITs suelen caer en entornos de subida de tipos de interés (correlación negativa con bonos)"]'::jsonb, quiz_question='¿Cuál es la principal ventaja de los REITs frente a la inversión directa en inmuebles?', quiz_options='[{"text":"Siempre tienen mayor rentabilidad","correct":false},{"text":"Liquidez diaria y diversificación inmobiliaria sin necesitar capital para comprar una propiedad completa","correct":true},{"text":"No pagan impuestos sobre los alquileres","correct":false},{"text":"Son más seguros que los bonos gubernamentales","correct":false}]'::jsonb WHERE id=277;

UPDATE submissions SET content='Los fondos indexados y ETFs replican la composición de un índice (S&P 500, MSCI World, IBEX 35) de forma pasiva, con comisiones muy bajas. Son la recomendación casi universal para inversores a largo plazo.', tips='["El 90% de los fondos de gestión activa no supera al índice de referencia tras comisiones a 15 años","Un ETF del MSCI World da exposición a 1.600+ empresas de 23 países con comisión de ~0,1%","«La inversión más sencilla y más rentable para la mayoría es un fondo indexado global»: John Bogle"]'::jsonb, quiz_question='¿Por qué los fondos indexados tienden a superar a la mayoría de fondos de gestión activa a largo plazo?', quiz_options='[{"text":"Porque los gestores activos son poco profesionales","correct":false},{"text":"Por sus comisiones bajas y la dificultad de superar consistentemente al mercado tras costes","correct":true},{"text":"Porque siempre están invertidos en las mejores empresas","correct":false},{"text":"Por regulación favorable de los gobiernos","correct":false}]'::jsonb WHERE id=278;

UPDATE submissions SET content='El Dollar Cost Averaging (DCA) o inversión periódica invierte una cantidad fija en intervalos regulares (mensualmente) independientemente del precio. Reduce el riesgo de invertir todo en el peor momento.', tips='["Con DCA, compras más participaciones cuando los precios son bajos y menos cuando son altos","No requiere predecir el mercado: elimina el market timing","La inversión mensual automatizada es la implementación más práctica del DCA"]'::jsonb, quiz_question='¿Cuál es la principal ventaja del DCA (inversión periódica fija) frente a invertir todo de golpe?', quiz_options='[{"text":"Siempre genera mayor rentabilidad que invertir todo de una vez","correct":false},{"text":"Reduce el riesgo de invertir todo el capital en el peor momento del mercado","correct":true},{"text":"Elimina las comisiones de brokerage","correct":false},{"text":"Garantiza no perder dinero en el corto plazo","correct":false}]'::jsonb WHERE id=279;

UPDATE submissions SET content='El rebalanceo del portfolio restaura la asignación objetivo tras las variaciones del mercado. Si las acciones subieron mucho y ahora son el 70% vs el 60% objetivo, vendes un poco y compras lo que bajó.', tips='["El rebalanceo anual o semestral es suficiente para la mayoría de carteras","El rebalanceo por bandas (cuando un activo se desvía >5% del objetivo) es más eficiente","Rebalancear en cuentas con diferimiento fiscal (pensiones, ISA) evita el impacto fiscal de las ventas"]'::jsonb, quiz_question='¿Cuál es el objetivo del rebalanceo periódico de un portfolio?', quiz_options='[{"text":"Vender siempre en máximos y comprar en mínimos","correct":false},{"text":"Restaurar la asignación de activos objetivo cuando los movimientos del mercado la han alterado","correct":true},{"text":"Maximizar el número de transacciones para aprovechar el mercado","correct":false},{"text":"Eliminar activos con pérdidas del portfolio","correct":false}]'::jsonb WHERE id=280;

UPDATE submissions SET content='La correlación entre activos mide si se mueven juntos o en sentido opuesto. Activos con correlación cercana a -1 se mueven en sentidos opuestos y se complementan para reducir la volatilidad total.', tips='["Correlación +1: perfectamente correlacionados; no reduce riesgo","Correlación 0: independientes; diversificación óptima","Correlación -1: perfectamente inversos; cobertura perfecta (rara en la práctica)"]'::jsonb, quiz_question='¿Qué tipo de correlación entre dos activos ofrece el mayor beneficio de diversificación?', quiz_options='[{"text":"Correlación +1 (perfectamente correlacionados)","correct":false},{"text":"Correlación 0 o negativa (se mueven independientemente o en sentidos opuestos)","correct":true},{"text":"Correlación +0,8 (muy correlacionados)","correct":false},{"text":"La correlación no importa en la diversificación","correct":false}]'::jsonb WHERE id=281;

UPDATE submissions SET content='Las acciones defensivas son de empresas que venden bienes o servicios esenciales (Nestlé, Procter & Gamble, Johnson & Johnson) con demanda estable en cualquier ciclo económico. Caen menos en crisis.', tips='["Las defensivas amortiguan la caída en recesiones pero suben menos en mercados alcistas","Empresas de consumo básico, farmacéuticas y utilities son los sectores más defensivos","Un portfolio muy defensivo sacrifica retorno a largo plazo por menor volatilidad"]'::jsonb, quiz_question='¿Por qué las acciones de empresas de consumo básico (comida, higiene) son consideradas «defensivas»?', quiz_options='[{"text":"Porque tienen mucho cash en caja","correct":false},{"text":"Porque su demanda es relativamente constante independientemente del ciclo económico","correct":true},{"text":"Porque son empresas del sector militar","correct":false},{"text":"Porque nunca bajan de precio","correct":false}]'::jsonb WHERE id=282;

UPDATE submissions SET content='Los bonos ligados a la inflación (TIPS en EE.UU., bonos indexados) ajustan el principal y los cupones según el IPC. Protegen el poder adquisitivo del capital en entornos inflacionarios.', tips='["Los TIPS son emitidos por el gobierno de EE.UU. y son prácticamente libres de riesgo de crédito","En entornos de inflación alta, los TIPS superan a los bonos nominales","En deflación, los TIPS pueden rentarmente peor que los bonos convencionales"]'::jsonb, quiz_question='¿Cómo protegen los bonos ligados a la inflación el poder adquisitivo del inversor?', quiz_options='[{"text":"Pagando siempre un tipo de interés del 5% o más","correct":false},{"text":"Ajustando el capital y los cupones según la inflación real, preservando el poder adquisitivo","correct":true},{"text":"Invirtiendo los cupones en activos reales automáticamente","correct":false},{"text":"Garantizando el precio de compra al vencimiento","correct":false}]'::jsonb WHERE id=283;

UPDATE submissions SET content='La liquidez del portfolio es la capacidad de convertir activos en efectivo rápidamente sin pérdida de valor. Mantener un 5-15% en activos líquidos (fondos monetarios, depósitos) permite aprovechar oportunidades y afrontar imprevistos.', tips='["Sin liquidez en cartera, una emergencia puede obligarte a vender activos en el peor momento","La liquidez del portfolio y el fondo de emergencia son capas diferentes de protección","En mercados bajistas, la liquidez disponible permite comprar activos a precios atractivos"]'::jsonb, quiz_question='¿Por qué mantener cierta liquidez en el portfolio de inversión es una estrategia defensiva?', quiz_options='[{"text":"Porque los activos líquidos siempre tienen mayor rendimiento","correct":false},{"text":"Permite afrontar imprevistos y aprovechar oportunidades sin vender otros activos a mal precio","correct":true},{"text":"Por obligación regulatoria para inversores privados","correct":false},{"text":"Para pagar las comisiones de los fondos","correct":false}]'::jsonb WHERE id=284;

UPDATE submissions SET content='El portfolio permanente de Harry Browne distribuye el 25% cada uno entre acciones (crecimiento), bonos largos (deflación/estabilidad), oro (inflación) y cash (crisis). Funciona bien en todos los entornos económicos.', tips='["El portfolio permanente sacrifica retorno máximo por consistencia en todos los escenarios","En 50 años históricamente no ha tenido pérdidas en ningún período de 5 años","Es una estrategia de «all-weather» para quien prioriza la protección sobre el crecimiento"]'::jsonb, quiz_question='¿Cuál es el principio detrás del «portfolio permanente» de Harry Browne?', quiz_options='[{"text":"Maximizar el retorno en mercados alcistas","correct":false},{"text":"Tener activos que funcionan bien en cada uno de los cuatro entornos económicos posibles","correct":true},{"text":"Invertir el 100% en los activos con mayor rentabilidad histórica","correct":false},{"text":"Rebalancear el portfolio cada semana","correct":false}]'::jsonb WHERE id=285;

-- Campaign: Herencias y Fiscalidad (IDs 286-300)
UPDATE submissions SET content='El impuesto de sucesiones en España grava la herencia recibida. Es un impuesto cedido a las comunidades autónomas, por lo que varía enormemente: Madrid o Canarias tienen bonificaciones casi totales; otras comunidades pueden llegar al 34%.', tips='["Descubre qué bonificaciones aplica tu comunidad autónoma antes de planificar la herencia","Las reducciones varían por parentesco: cónyuge e hijos tienen mayor reducción que hermanos o sobrinos","La planificación sucesoria puede reducir drásticamente el impuesto pagado de forma totalmente legal"]'::jsonb, quiz_question='¿Por qué el impuesto de sucesiones varía tanto entre comunidades autónomas en España?', quiz_options='[{"text":"Porque cada comunidad tiene una moneda diferente","correct":false},{"text":"Porque es un impuesto cedido a las CCAA que pueden establecer sus propias bonificaciones y reducciones","correct":true},{"text":"Porque el gobierno central lo distribuye de forma desigual","correct":false},{"text":"No varía: es igual en toda España","correct":false}]'::jsonb WHERE id=286;

UPDATE submissions SET content='Las ganancias patrimoniales tributan en el IRPF cuando vendes un activo por más de lo que pagaste. El tipo varía: 19% hasta 6.000€ de ganancia, 21% de 6.000 a 50.000€, 23% de 50.000 a 200.000€, 27% por encima.', tips='["Solo tributa cuando realizas la venta; las ganancias latentes no tributan","Las pérdidas patrimoniales pueden compensarse con ganancias del mismo año o los 4 siguientes","La inflación puede crear «ganancias nominales» que en realidad son pérdidas reales"]'::jsonb, quiz_question='Según la escala del IRPF, ¿a qué tipo tributaría una ganancia patrimonial de 10.000€ en España (2024)?', quiz_options='[{"text":"19% sobre los 10.000€ completos","correct":false},{"text":"19% sobre los primeros 6.000€ y 21% sobre los 4.000€ restantes","correct":true},{"text":"21% sobre los 10.000€ completos","correct":false},{"text":"Solo el 15%","correct":false}]'::jsonb WHERE id=287;

UPDATE submissions SET content='Los dividendos, intereses de cuentas y cupones de bonos son rendimientos del capital mobiliario. Tributan en el IRPF en la misma escala que las ganancias patrimoniales (base del ahorro): 19-28%.', tips='["Los dividendos de acciones europeas suelen tener retención en origen que luego se puede deducir","Los ETFs de acumulación reinvierten los dividendos automáticamente, diferiendo el pago de impuestos","Los intereses de cuentas y depósitos tributan aunque sean bajos: el banco hace retención del 19%"]'::jsonb, quiz_question='¿Qué diferencia fiscal existe entre un ETF de distribución (que paga dividendos) y uno de acumulación?', quiz_options='[{"text":"No hay diferencia fiscal","correct":false},{"text":"El ETF de acumulación reinvierte sin tributación inmediata; el de distribución genera tributación al recibir los dividendos","correct":true},{"text":"El ETF de acumulación siempre paga más impuestos","correct":false},{"text":"Los ETFs de distribución están exentos de impuestos","correct":false}]'::jsonb WHERE id=288;

UPDATE submissions SET content='El tax-loss harvesting (cosecha de pérdidas) vende activos en pérdidas para compensar ganancias patrimoniales del mismo ejercicio, reduciendo la factura fiscal. Las pérdidas que sobran compensan hasta 4 años futuros.', tips='["Vende el activo en pérdidas, realiza el beneficio fiscal y luego recompra un activo similar (no el mismo antes de 2 meses: norma antielusión)","Funciona bien en portfolios grandes; en pequeños, el coste de transacción puede superar el beneficio fiscal","Planificarlo en el cuarto trimestre permite conocer las ganancias del año antes de actuar"]'::jsonb, quiz_question='¿Cuál es el objetivo del tax-loss harvesting?', quiz_options='[{"text":"Evitar pagar impuestos de forma ilegal","correct":false},{"text":"Realizar pérdidas para compensar ganancias y reducir la factura fiscal de forma legal","correct":true},{"text":"Maximizar el número de transacciones para reducir los impuestos","correct":false},{"text":"Traspasar fondos entre cuentas bancarias","correct":false}]'::jsonb WHERE id=289;

UPDATE submissions SET content='En el IRPF español, las inversiones tienen un tratamiento diferente según el tipo de rendimiento: los dividendos e intereses van a la base del ahorro; los rendimientos de fondos de inversión, al rescate. La fiscalidad influye en la elección de vehículos.', tips='["Los fondos de inversión permiten traspasar entre fondos sin tributar: es la mayor ventaja fiscal de los fondos","Los planes de pensiones difieren la tributación hasta el rescate (tributan como trabajo)","La optimización fiscal de las inversiones puede añadir 0,5-1% de rentabilidad neta anual"]'::jsonb, quiz_question='¿Cuál es la ventaja fiscal exclusiva de los fondos de inversión frente a los ETFs en España?', quiz_options='[{"text":"Los fondos de inversión están exentos de impuestos","correct":false},{"text":"Se pueden traspasar entre fondos sin tributar por las ganancias hasta el momento del rescate final","correct":true},{"text":"Los fondos de inversión pagan menos comisiones de gestión","correct":false},{"text":"Los fondos no tienen que declararse en el IRPF","correct":false}]'::jsonb WHERE id=290;

UPDATE submissions SET content='En España, las ganancias por criptomonedas tributan como ganancias patrimoniales en el IRPF. Cada intercambio (crypto-crypto, crypto-fiat) es un hecho imponible. La información debe declararse en el modelo 721 si supera 50.000€.', tips='["Llevar un registro detallado de cada operación de crypto con fecha, precio de compra y precio de venta es obligatorio","El intercambio de Bitcoin por Ethereum tributa igual que vender Bitcoin por euros","Las pérdidas en crypto pueden compensarse con ganancias de otros activos del mismo año"]'::jsonb, quiz_question='¿Cuándo tributa un intercambio de Bitcoin por Ethereum en España?', quiz_options='[{"text":"Solo al convertir a euros","correct":false},{"text":"Inmediatamente al realizar el intercambio, como si vendieras Bitcoin por euros","correct":true},{"text":"Las criptomonedas no tributan en España","correct":false},{"text":"Solo si la ganancia supera 1.000€","correct":false}]'::jsonb WHERE id=291;

UPDATE submissions SET content='Un testamento notarial es el documento legal que expresa la voluntad de distribución del patrimonio. En España hay tres cuartas partes de la herencia (legítimas) con distribución legalmente restringida.', tips='["La legítima estricta (1/3 del patrimonio) debe ir a hijos o descendientes obligatoriamente","El tercio de mejora puede asignarse libremente entre los hijos","El tercio de libre disposición se puede dejar a quien se quiera, incluyendo no familiares"]'::jsonb, quiz_question='¿Qué parte de la herencia puede el testador asignar libremente a quien quiera en España?', quiz_options='[{"text":"El 100% del patrimonio","correct":false},{"text":"La mitad del patrimonio","correct":false},{"text":"Un tercio del patrimonio (tercio de libre disposición)","correct":true},{"text":"Nada; todo va a hijos obligatoriamente","correct":false}]'::jsonb WHERE id=292;

UPDATE submissions SET content='La sucesión intestada (sin testamento) en España sigue un orden legal: primero los descendientes (hijos, nietos), luego ascendientes (padres), luego el cónyuge, y finalmente otros parientes. Sin testamento, la ley decide.', tips='["En parejas de hecho sin testamento, el conviviente puede no heredar nada según la CCAA","Hacer testamento es una responsabilidad hacia tus personas cercanas, no solo para ricos","Un testamento simple puede hacerse con un notario por menos de 150€"]'::jsonb, quiz_question='¿Qué ocurre con la herencia si una persona fallece sin testamento y tiene pareja de hecho pero no cónyuge en España?', quiz_options='[{"text":"La pareja de hecho hereda todo igual que un cónyuge","correct":false},{"text":"Depende de la comunidad autónoma, y en muchas la pareja de hecho no hereda nada sin testamento","correct":true},{"text":"La herencia va al Estado automáticamente","correct":false},{"text":"Los amigos más cercanos son llamados a heredar","correct":false}]'::jsonb WHERE id=293;

UPDATE submissions SET content='Los activos digitales (criptomonedas, cuentas online, contraseñas, wallets) son heredables pero requieren acceso. Sin instrucciones claras, los herederos pueden no poder acceder a ellos nunca.', tips='["Crea un «sobre de emergencia» con instrucciones de acceso a tus activos digitales importantes","Para criptomonedas: la seed phrase es la clave; guárdala en un lugar físico seguro con instrucciones","Incluye activos digitales en el testamento y en un inventario separado con instrucciones de acceso"]'::jsonb, quiz_question='¿Por qué los activos digitales requieren planificación especial en la herencia?', quiz_options='[{"text":"Porque están exentos del impuesto de sucesiones","correct":false},{"text":"Porque sin las credenciales de acceso, los herederos pueden no poder recuperarlos nunca","correct":true},{"text":"Porque solo pueden heredarlos los menores de edad","correct":false},{"text":"Porque el Estado los confisca automáticamente","correct":false}]'::jsonb WHERE id=294;

UPDATE submissions SET content='Las donaciones en vida permiten transmitir el patrimonio con menor impacto fiscal en algunas comunidades autónomas. Los pactos sucesorios (en comunidades que los permiten) pueden mejorar aún más la eficiencia fiscal.', tips='["Madrid y Canarias tienen bonificaciones de hasta el 99% en donaciones padres-hijos","Un pacto sucesorio en comunidades como Cataluña o País Vasco puede ser muy eficiente","La planificación sucesoria es un campo muy específico; la asesoría de un abogado fiscalista vale la inversión"]'::jsonb, quiz_question='¿En qué se diferencia una donación de un pacto sucesorio en planificación de herencias?', quiz_options='[{"text":"No hay diferencia, son lo mismo","correct":false},{"text":"La donación transmite el bien en vida inmediatamente; el pacto sucesorio fija las condiciones de la transmisión para cuando ocurra el fallecimiento","correct":true},{"text":"El pacto sucesorio está prohibido en España","correct":false},{"text":"Las donaciones solo sirven para inmuebles","correct":false}]'::jsonb WHERE id=295;

UPDATE submissions SET content='Un seguro de vida puede usarse como herramienta de planificación hereditaria: el capital asegurado se paga directamente a los beneficiarios designados, sin pasar por el proceso de herencia y con tratamiento fiscal específico.', tips='["En España, los seguros de vida tienen reducción propia en sucesiones (hasta 9.195€ por cada beneficiario en algunas CCAA)","El capital del seguro no forma parte de la masa hereditaria si hay beneficiarios designados","Es especialmente útil para dar liquidez inmediata a los herederos mientras se tramita la herencia"]'::jsonb, quiz_question='¿Qué ventaja tiene usar un seguro de vida como herramienta de planificación hereditaria?', quiz_options='[{"text":"El beneficiario no paga impuestos nunca","correct":false},{"text":"El capital se paga directamente al beneficiario sin pasar por el proceso de herencia, aportando liquidez inmediata","correct":true},{"text":"El seguro de vida evita completamente el impuesto de sucesiones","correct":false},{"text":"Solo lo pueden usar las empresas","correct":false}]'::jsonb WHERE id=296;

UPDATE submissions SET content='Las estrategias legales de planificación fiscal incluyen: diferir ganancias, compensar pérdidas, usar vehículos fiscalmente eficientes (planes de pensiones, fondos de inversión) y optimizar el timing de ventas entre ejercicios.', tips='["La planificación fiscal es diferente de la evasión fiscal: una es legal, la otra es delito","Revisa tu situación fiscal antes del 31 de diciembre para aplicar estrategias de ese ejercicio","Un asesor fiscal especializado en inversiones puede pagar su coste con el ahorro generado"]'::jsonb, quiz_question='¿Cuál es la diferencia entre planificación fiscal legal y evasión fiscal?', quiz_options='[{"text":"No hay diferencia, ambas buscan pagar menos impuestos","correct":false},{"text":"La planificación usa herramientas legales para optimizar; la evasión oculta información o incumple la ley","correct":true},{"text":"La planificación fiscal solo la pueden hacer las empresas","correct":false},{"text":"La evasión fiscal es legal si el importe es pequeño","correct":false}]'::jsonb WHERE id=297;

UPDATE submissions SET content='La fiscalidad internacional aplica cuando tienes activos o ingresos en otros países o cuando cambias tu residencia fiscal. Los convenios de doble imposición evitan que tributes dos veces por los mismos ingresos.', tips='["Cambiar de residencia fiscal no es inmediato en España: debes probar la residencia efectiva con facturas, contratos, etc.","Los dividendos de acciones extranjeras tienen retención en origen; recuperarla requiere declaración","Los «nómadas digitales» con ingresos en múltiples países deben asesorarse sobre dónde tienen obligación fiscal real"]'::jsonb, quiz_question='¿Qué protegen los convenios de doble imposición entre países?', quiz_options='[{"text":"Que los ciudadanos no pagen impuestos en el extranjero","correct":false},{"text":"Que los mismos ingresos o ganancias no tributen íntegramente en dos países simultáneamente","correct":true},{"text":"La privacidad de las inversiones internacionales","correct":false},{"text":"Que los tipos impositivos sean iguales en todos los países firmantes","correct":false}]'::jsonb WHERE id=298;

UPDATE submissions SET content='El Modelo 720 obliga a declarar bienes y derechos en el extranjero que superen 50.000€ en cualquiera de tres categorías: cuentas bancarias, valores (acciones, fondos), e inmuebles. El incumplimiento tiene sanciones muy elevadas.', tips='["El Modelo 720 es informativo: no genera impuesto por tenerlo, solo obliga a declarar","El Modelo 721 es su equivalente para criptomonedas en el extranjero (desde 2024)","Si tienes activos en el extranjero sobre esos umbrales, consulta con un asesor fiscal; las multas por no declarar son muy altas"]'::jsonb, quiz_question='¿Qué obligación crea el Modelo 720 para los residentes fiscales en España?', quiz_options='[{"text":"Pagar un impuesto adicional del 20% sobre activos en el extranjero","correct":false},{"text":"Declarar informáticamente los bienes y derechos en el extranjero que superen 50.000€ en cada categoría","correct":true},{"text":"Repatriar todos los fondos del extranjero","correct":false},{"text":"Solo aplica a empresas, no a particulares","correct":false}]'::jsonb WHERE id=299;

UPDATE submissions SET content='Un asesor fiscal especializado en inversiones y herencias puede identificar oportunidades de ahorro fiscal que superen con creces su coste. La complejidad fiscal aumenta con el patrimonio y la diversificación internacional.', tips='["Para patrimonios simples, el software de declaración de la renta es suficiente","A partir de cierto umbral (inversiones, inmuebles, herencias, activos en el extranjero), el asesor fiscaliza la inversión","Un buen asesor explica las opciones, no decide por ti; las decisiones finales siempre son tuyas"]'::jsonb, quiz_question='¿En qué situación tiene más valor económico contratar un asesor fiscal especializado en inversiones?', quiz_options='[{"text":"Cuando tienes solo una cuenta bancaria y un trabajo","correct":false},{"text":"Cuando tienes inversiones, inmuebles, activos en el extranjero, herencias o cambios importantes de vida","correct":true},{"text":"Solo cuando hacienda te manda una notificación","correct":false},{"text":"Nunca; la información online es suficiente","correct":false}]'::jsonb WHERE id=300;

COMMIT;
